### ISSUE TITLE
Trashing doesn't put the correct trashing timestamp 

### ISSUE THREAD

**Issue by joemaro** [leo-arch/CliFM#101]
Trash a file and look at the timestamp in (for example) `nemo` and the timestamp for then the file was trashed is january 1st 1970 ...

CliFM 1.4 (Jan 17, 2022)

**Comment by leo-arch** [comment]
Hi @joemaro. Thanks for reporting this. I'll take a look at it.

**Comment by joemaro** [comment]
also the `trash-list` in `clifm` shows `????-??-?? ??:??:?? /directory/filename` for files trashed in `clifm`

**Comment by leo-arch** [comment]
Ok. It should be working now.
