### ISSUE TITLE
interactive help : pattern not found

### ISSUE THREAD

**Issue by chimay** [leo-arch/CliFM#103]
**Describe the bug**
see issue title

**To Reproduce**
1. run 'ih'
2. choose `standard input`
3. manpage is opened but pager does not find the pattern

it happens also with `rationale`

**Desktop (please complete the following information):**
 - OS: linux
 - Terminal : kitty
 - CliFM version :  612334b 
- Installation source : Git

**Comment by leo-arch** [comment]
Hi @chimay. Thanks for reporting.

Should be fixed now.

**Comment by chimay** [comment]
glad to help ! nice idea, the tag system btw.

**Comment by leo-arch** [comment]
Still working on it. You know, new features, new bugs. Please report if you find anything unexpected, even if you have some suggestion for this new system.

**Comment by chimay** [comment]
I'll let you know, of course !
