### ISSUE TITLE
using full file path in tags links ?

### ISSUE THREAD

**Issue by chimay** [leo-arch/CliFM#104]
**Is your feature request related to a problem? Please describe.**
`ta **/*.sh :script` complains about non existent directories

**Describe the solution you'd like**
let's say we want to tag : 

```
/full/path/of/file
```

instead of creating a link like this:

```
tagdir/file -> /full/path/of/file
```

in the tag dir, you could do :

```
tagdir/full:path:of:file -> /full/path/of/file
```

just replacing the slashes by colons, or any other char (or chars sequence)
non frequently used in file names.

advantages :

- no clash of file having same name in distinct dirs
- no error when adding a file in a subdir : `ta subdir/file :mytag`

drawback :

- you need to escape the special char with backslash if it appears in the file name

alternative 1 :  really create the subdirs in the tag directory :

```
tagdir/full/path/of/file -> /full/path/of/file
```

advantage : no need to escape a special char

drawback : needs to sweep all subtree in tagdir when applying a command on the tagged files

alternative 2 : instead of a tagdir, use a tag file containing the list of tagged files :

```
profiles/default/tagfiles/mytag
--------------------
/.../.../file-1
/.../.../file-2
...
```

advantage : no special char, no looong subtree

drawback : may be slower on the file system, i don't know

**Comment by leo-arch** [comment]
Hi @chimay. Nice suggestions! Thanks.

I think I'll give a try to the colons approach (dots could fit the bill as well). Besides avoiding file names conflict, it provides another advantage: no need to resolve symlinks target. We only need to replace colons/dots by a slash. I like it.
The tags file idea is cool. Slower (opening/closing files is always slower), but hardly noticeable. Maybe.

**Comment by chimay** [comment]
I can't wait to see this !

**Comment by leo-arch** [comment]
Done. Give it a try now. Finally followed the colons approach.

**Comment by chimay** [comment]
great ! now you can do things like :

```
ta **/*.zsh :script-zsh
```

I had no compatilibity issue with the old sylink system, all seem well, thanks !
