### ISSUE TITLE
macOS Port won't compile

### ISSUE THREAD

**Issue by juanandresgs** [leo-arch/CliFM#106]
**Describe the bug**
Super excited about the MacOS port. That said, it's not compiling on my end. If I run 'gmake', I get a bunch of warnings and errors (C99 incompatible implicit function declarations mostly). Attached the error dump. I'm guessing there's an issue here with the LIBS_Darwin include folders but I've tried a few different options and gotten the same results.

**To Reproduce**
git clone clifm repo
run gmake

**Expected behavior**
Compiled binary for MacOS

**Desktop (please complete the following information):**
MacOS 12.2.1, Apple M1 Max, GNU Make 4.3 (Built for x86_64-apple-darwin20.1.0), zsh on iterm2, 
CliFM v 1.4 Alma, from Git

**Additional context**
https://github.com/leo-arch/clifm/pull/105
[clifm_errors.txt](https://github.com/leo-arch/clifm/files/8217629/clifm_errors.txt)

**Comment by leo-arch** [comment]
Thanks for reporting @juanandresgs. @l2dy, could you please take a look at this?

**Comment by l2dy** [comment]
You need to follow instructions [here](https://github.com/leo-arch/clifm/pull/105#issuecomment-1063147732). If you don't want to use MacPorts, you'll have to modify LIBS_Darwin by hand for now.

**Comment by leo-arch** [comment]
Maybe it's my fault, maybe he's following the instructions I added to the docs (https://github.com/leo-arch/clifm/wiki/Introduction#d-macos). Though I'm not sure where these instructions deviate from those given by you. Feel free to edit them if necessary.
