### ISSUE TITLE
Install rules for CMake

### ISSUE THREAD

**Issue by l2dy** [leo-arch/CliFM#110]
**Is your feature request related to a problem? Please describe.**
`CMakeLists.txt` should have install rules matching the following section in Makefile to get feature parity with `make install`.

https://github.com/leo-arch/clifm/blob/c03e0a8566973c80d1ac9f7100505dd54bea23dd/Makefile#L40-L65

**Comment by leo-arch** [comment]
Hi @l2dy. I added install instructions for `cmake`.

Install as follows:
```sh
git clone https://github.com/leo-arch/clifm.git
cd clifm
cmake . -B cmake-build
sudo cmake --build  cmake-build -t install
```

To uninstall, run:

```sh
sudo make uninstall
```

Will this impact on the `Portfile` for MacOS?

**Comment by l2dy** [comment]
> Will this impact on the `Portfile` for MacOS?

Yes, I can remove the destroot section in Portfile and let the cmake 1.1 PortGroup handle it. Files other than the clifm binary will be installed correctly.

For the record, here is a list of files installed after modifying the Portfile, source commit is ed8c39dfb0489c03f5a50b5238b963d4eefe85d4.

```
/opt/local/man/man1/clifm.1
/opt/local/bin/clifm
/opt/local/share/icons/hicolor/scalable/apps/clifm.svg
/opt/local/share/applications/clifm.desktop
/opt/local/share/zsh/site-functions/_clifm
/opt/local/share/bash-completion/completions/clifm
/opt/local/share/clifm/keybindings.cfm
/opt/local/share/clifm/plugins/fzfhist.sh
/opt/local/share/clifm/plugins/plugins-helper
/opt/local/share/clifm/plugins/pdf_viewer.sh
/opt/local/share/clifm/plugins/fdups.sh
/opt/local/share/clifm/plugins/git_status.sh
/opt/local/share/clifm/plugins/clip.sh
/opt/local/share/clifm/plugins/mime_list.sh
/opt/local/share/clifm/plugins/colors.sh
/opt/local/share/clifm/plugins/music_player.sh
/opt/local/share/clifm/plugins/jumper.sh
/opt/local/share/clifm/plugins/fzfdirhist.sh
/opt/local/share/clifm/plugins/fzfdesel.sh
/opt/local/share/clifm/plugins/batch_copy.sh
/opt/local/share/clifm/plugins/dragondrop.sh
/opt/local/share/clifm/plugins/fzcd.sh
/opt/local/share/clifm/plugins/update.sh
/opt/local/share/clifm/plugins/BFG.cfg
/opt/local/share/clifm/plugins/fzfsel.sh
/opt/local/share/clifm/plugins/finder.sh
/opt/local/share/clifm/plugins/img_viewer.sh
/opt/local/share/clifm/plugins/BFG.sh
/opt/local/share/clifm/plugins/kbgen.c
/opt/local/share/clifm/plugins/batch_create.sh
/opt/local/share/clifm/plugins/wallpaper_setter.sh
/opt/local/share/clifm/plugins/ihelp.sh
/opt/local/share/clifm/plugins/rgfind.sh
/opt/local/share/clifm/plugins/fzfnav.sh
/opt/local/share/clifm/plugins/vid_viewer.sh
/opt/local/share/clifm/nets.cfm
/opt/local/share/clifm/colors/light.cfm
/opt/local/share/clifm/colors/default.cfm
/opt/local/share/clifm/clifmrc
/opt/local/share/clifm/actions.cfm
/opt/local/share/clifm/functions/subshell_notice.sh
/opt/local/share/clifm/functions/file_picker.sh
/opt/local/share/clifm/functions/cd_on_quit.sh
/opt/local/share/clifm/prompts.cfm
/opt/local/share/clifm/readline.cfm
/opt/local/share/clifm/mimelist.cfm
```

Edit: MacPorts will automatically gzip the man pages, so clifm.1 will become clifm.1.gz when actually installed.

**Comment by leo-arch** [comment]
Looks fine. Good to know about the auto-gzip'ing feature: though manpages work uncompressed as well, it's always better to have them gzip'ped.

So, if there's no other issue in this regard, we can close this issue.

Btw, install instructions are still the same, isn't it?

**Comment by l2dy** [comment]
> So, if there's no other issue in this regard, we can close this issue.

Sure. Thanks for implementing installation in CMake! CMake is much easier to deal with than handcrafted Makefile with hard-coded flags that need to be overridden, for example `-march=native` is not welcomed in MacPorts because we distribute binaries for others to install on their machine.

> Btw, install instructions are still the same, isn't it?

Yes, no change to `sudo port install clifm`. I will update the Portfile after next release.
