### ISSUE TITLE
Exit on Ctrl-D (EOF)

### ISSUE THREAD

**Issue by l2dy** [leo-arch/CliFM#111]
**Is your feature request related to a problem? Please describe.**
Most shells exit on EOF, clifm should follow the convention.

**Describe the solution you'd like**
Exit on Ctrl-D (EOF).

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by leo-arch** [comment]
This feature exists, but isn't enabled by default. To enable it run clifm as follows:

```
clifm --control-d-exits
```

**Comment by l2dy** [comment]
> This feature exists, but isn't enabled by default. To enable it run clifm as follows:
> 
> ```
> clifm --control-d-exits
> ```

Are there any reasons for not enabling it by default?

BTW, both Ctrl-D and <kbd>F12</kbd> should print a newline before exit.

**Comment by leo-arch** [comment]
> Are there any reasons for not enabling it by default?

Not really. I just get the impression that it's easy for the user to accidentally quit CliFM when editing the command line, where keybinds like `Ctrl-a` and `Ctrl-e` are common.

> Both Ctrl-D and F12 should print a newline before exit

No problem.

EDIT: Done.

**Comment by l2dy** [comment]
> > Are there any reasons for not enabling it by default?
> 
> Not really. I just get the impression that it's easy for the user to accidentally quit CliFM when editing the command line, where keybinds like `Ctrl-a` and `Ctrl-e` are common.

I'd recommend either

1. enable it by default, or
2. print a message on Ctrl-d to tell the user how to enable it (and maybe how to suppress the message) in clifmrc.

**Comment by leo-arch** [comment]
Exit on EOF is now enabled by default. You can use `--no-control-d-exit` to disable it.

**Comment by l2dy** [comment]
Thanks!
