### ISSUE TITLE
Aliases set in clifmrc do not work as expected

### ISSUE THREAD

**Issue by ashprice** [leo-arch/CliFM#112]
For some reason I am unable to use any aliases set in my clifmrc. Example alias:
`alias yt="yt-dlp --add-metadata --all-subs -f 'bestvideo[height<=2160]+bestaudio/bestvideo+bestaudio' --write-description --sub-lang en -i -o '%(upload_date)s-%(title)s.%(ext)s'"`

I receive the following error:

`sh: line 1: yt: command not found`

Logs are unilluminating. `[2022-03-29T11:16:29+0100] /home/hearth:yt`

I have two other issues, I am unsure if they are related but I will mention them here instead of opening other issues for now - first I am unable to pass commands to transmission-cli - trying to pause or resume the download of torrent fails (in this case, a FreeBSD ISO), but it works as expected if I pass the command from regular shell. 

Second, I have abnormally high CPU usage from clifm seemingly at random - specifically one thread of my CPU goes to 100% and just sits there, occasionally swapping in for a different thread.

All other shell commands pass fine, with so I am not sure what is going on here.

**Comment by leo-arch** [comment]
Hi @ashprice! First of all, thanks for reporting.

I'll take a look at the aliases and transmission-cli issues. As to the high CPU usage, I'll keep an eye on it: to fix it, I need to reproduce it first. If you can provide more info (installed version, when it happens, what's you config, terminal, etc) that would be useful.

**Comment by leo-arch** [comment]
Never used `yt-dlp` before. What parameters are you passing to the `yt` alias? Whenever I run the exact same alias I get this:

```
<0> $ yt
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
```

which seems expected behavior.

EDIT: Have you tried with simple aliases like `alias ls="ls -a"`? I need to know if the problem you're facing is coming from the aliases function as such or just from some specific alias.

**Comment by leo-arch** [comment]
Trying `transmission-cli`. I successfully downloaded a torrent file from within `clifm` via `transmission-remote -a TORRENT_FILE `. I was also able to pause and resume the download with `transmission-remote -t ID --stop` and `transmission-remote -t ID --start` respectively. Which commands are you using exactly?

**Comment by leo-arch** [comment]
#### Report

Setup: Archlinux, openbox, xterm, clifm 1.5.1 (fresh AUR install)

```
<0> $ alias
ls -> ls --color=auto -hNA --group-directories-first
lsblk -> /usr/bin/lsblk -i
sudo -> /usr/bin/sudo 
yt -> yt-dlp --add-metadata --all-subs -f 'bestvideo[height<=2160]+bestaudio/bestvideo+bestaudio' --write-description --sub-lang en -i -o '%(upload_date)s-%(title)s.%(ext)s'

<0> $ yt https://www.youtube.com/watch?v=NdHjsT3FK8w
[youtube] NdHjsT3FK8w: Downloading webpage
[youtube] NdHjsT3FK8w: Downloading android player API JSON
[info] NdHjsT3FK8w: Downloading 1 format(s): 248+251
[info] Writing video description to: 20220329-Terminal is NEEDED to use Linux.description
[download] Destination: 20220329-Terminal is NEEDED to use Linux.f248.webm
[download] 100% of 64.34MiB in 00:09
[download] Destination: 20220329-Terminal is NEEDED to use Linux.f251.webm
[download] 100% of 12.85MiB in 00:01
[Merger] Merging formats into "20220329-Terminal is NEEDED to use Linux.webm"
Deleting original file 20220329-Terminal is NEEDED to use Linux.f248.webm (pass -k to keep)
Deleting original file 20220329-Terminal is NEEDED to use Linux.f251.webm (pass -k to keep)
[Metadata] Adding metadata to "20220329-Terminal is NEEDED to use Linux.webm"
```

**Comment by ashprice** [comment]
**Setup**: Arch 5.16.16-arch1-1, dwm, st, clifm 1.5 - I guess I installed from source, I don't actually remember, so I've switched to clifm-git in the AUR. 

A simpler alias, like `ls="ls -al"` works as expected. However, one with an argument like `mv='mv -t /home/hearth/testdir/` passed with some file as an argument does not work. 

yt-dlp commands are passed with URL arguments. A minimal working example (simpler than the above):

`yt-dlp https://www.youtube.com/watch?v=L1ung0wil9Y` <- works as expected, both in regular shell and in clifm.

`alias yt='yt-dlp'` + `yt https://www.youtube.com/watch?v=L1ung0wil9Y` <- works in shell, not in clifm (I can preemptively confirm it is set in different/the correct config files!)

More elaborate commands with arguments with yt-dlp do not work. Regular shell commands work fine if I type them out, it's only aliases that I am having problems with, except for transmission. 

--- 

I have also tested with a MacOS install; all aliases work as expected there, regardless of how complex. 

Here again transmission fails to stop and start torrents on command, whether this is passed with an alias like `alias tran='transmission-remote'` + `tran -t 1 --stop` or as a regular argument, though _adding_ a torrent from a magnet link works as expected. 

This time setup is: MacOS 12.0.1, kernel 21.1.0, iterm2, clifm 1.5.1 installed from source. 

--- 

I should note that in both cases, I do get a message:

`localhost:9091/transmission/rpc/ responded: "success"`

when I try to stop and start something, but nothing happens. So it seems at least that the alias and transmission issues are separate.

--- **An update in writing this post**

So in troubleshooting I noticed something - running `alias` in clifmrc returned _no aliases_. So, I go about investigating and find that, if I strip out all my aliases, I can get aliases to work with a more minimal config file (I should have done this before) - but, I can only get _some_ aliases to work, and I don't see a pattern. EG:

```
alias ka="killall"
```

works as expected, as does

```
alias ka="killall"
alias test="echo test worked"
```

but 

```
alias ka="killall"
alias sudo="sudo "
alias	mkd="mkdir -pv"
```

fails to print anything after 'ka' and 'sudo,' ie.:

```
 $ alias
ka -> killall
sudo -> sudo
```

```
alias ka="killall"
alias	mkd="mkdir -pv"
```

only prints 'ka' and

```
alias ka="killall"
alias	yt="yt-dlp --add-metadata --all-subs -f \'bestvideo[height<=2160]+bestaudio/bestvideo+bestaudio\' --write-description --sub-lang en -i -o \'%(upload_date)s-%(title)s.%(ext)s\'"
```
or

```
alias ka="killall"
alias	rc="mv -t /home/heart/test/"
```
only prints 'ka'. 

I hope this post isn't too disorganised and if I can clarify anything or provide any other info, please let me know!

**Comment by ashprice** [comment]
Ah - writing this post has uncovered the issue: those weird tabs/spaces! They didn't show in neovim or in the markdown editor here before I posted. Deleting them and putting in a normal space fixed everything. 

Bit of an anticlimatic issue, I guess. 

That leaves only transmission - shall I open a different issue for that? (I also can't get image preview to work in iterm2 - I'm not sure if this is strictly a clifm issue though...)

**Comment by leo-arch** [comment]
Great! Yes, we better close this issue and open a new one for transmission, so that we keep a better track of our issues.

As to image preview on iterm2, you can open a separate issue as well.
