### ISSUE TITLE
trouble with bookmarks with spaces in directory name

### ISSUE THREAD

**Issue by deathtrip** [leo-arch/CliFM#114]
**Describe the bug**
When i try to add a bookmark of a directory with a space in it i get a `No such file or directory` error.
Editing bookmarks.cfm works, but sometimes the name is not displayed in the menu, only the shortcut. Seems to happen the first few times i run bm after starting clifm.

**To Reproduce**
1. Run bm a ELN or directory name with space in it
2. See error: `No such file or directory`

Also:
1. Add bookmark manually in bookmarks.cfm
2. The name is not displayed in the bookmarks menu

**Expected behavior**
Bookmarks should be added and displayed correctly.

**Desktop:**
 - OS: Arch Linux
 - Terminal: tested in kitty & alacritty
 - CliFM version: 1.5.1
- Installation source: AUR

**Additional context**
Another improvement would be to display the directory contents again after quiting the bookmarks menu with "q", as right now you still see the bookmark shortcuts.

**Comment by leo-arch** [comment]
Hi @deathtrip. Thanks for reporting! Fixing this issue should be fairly simple, but one never knows. I'll keep you informed.

**Comment by leo-arch** [comment]
Done. Please reinstall, using the latest version from the AUR (`clifm-git`), give it a try, and let me know.

**Comment by deathtrip** [comment]
Just tested it and the bookmarking works fine.
Also thanks for fixing the list display after quiting the bookmarks menu, i just found out that it also happens when you type a wrong bookmark shortcut. You should consider leaving the user in the bookmark menu in that case, as they'll most likely want to retry.

**Comment by leo-arch** [comment]
> You should consider leaving the user in the bookmark menu in that case [wrong bookmark]

Done @deathtrip. If it works as intended you can close this issue.

**Comment by deathtrip** [comment]
I would skip the "Press any key to continue..." step, and just print the error, unless it's somehow needed.

On another note i noticed the "No such file or directory" bookmark error behaves just like the wrong bookmark error before the fix, and it seems to me the bookmark name is not displayed when the folder can't be found.

Besides that everything works fine, i didn't close it just yet, to make sure you read the above points.

**Comment by leo-arch** [comment]
Hi @deathtrip. I rewrote the bookmarks interface taking your insights into account. I think it's quite better now.

**Comment by deathtrip** [comment]
Yep. All working fine over here, so i'm gonna close this now.
Thanks for all the fixes.
