### ISSUE TITLE
segmentation fault if the directory is deleted while clifm is inside it

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#115]
after cleaning some torrents i tried to go back one folder and got a segmentation fault
i believe its possible to prevent this by saving the path list and just going back until a folder thats still exist is there

**Comment by leo-arch** [comment]
Hi @DNDEBUG. Thanks for reporting! I'll try to replicate this behavior and let you know.

EDIT: Could you please be more specific as to how you were going back? `cd` command, autocd, <kbd>Shift-left</kbd>? Also, did you remove a parent directory, or just a directory in the directory history list?

**Comment by leo-arch** [comment]
Have been trying to reproduce this issue. No luck. Tried this:

```
# Create a directory:
n testdir/

# cd into it:
testdir/

# Once in it, remove it:
r .
```

No matter how I try, CliFM always takes me to the first existent and accessible parent directory automatically.

**Comment by DNDEBUG** [comment]
2 terminals
terminal 1 mkdir testdir
Terminal 2 clifm into testdir
terminal 1 rmdir testdir
terminal 2 ..
segmentation fault

**Comment by leo-arch** [comment]
Reproduced and solved. Please confirm and close this issue.

**Comment by DNDEBUG** [comment]
yep, confirmed
keep the good work
