### ISSUE TITLE
Option to have a list of programs in the clifmrc

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#116]
add an option on clifmrc to list what programs clifm can run instead of having to read everythign from $PATH
this would also help to prevent mistakes or wasting time with tab

also an option to make the name of the binaries explicit
so the user will have to explicitly tipe the name of the binary to be able to run it

and clifm causes some mistakes with options from other programs
i noticed it with wget and aria2c
so it would be good to only accept the programs options after the name of the program
and if the user wnats to use something from clifm he will have to specify
lets say i want to do somethign with the file 20

program option option $20
i don't know how you could do that and i don't think using $ is a good idea
maybe $ELN20

so the moment i tipe the program name clifm stops listening unless i set some flag to use clifm options

**Comment by leo-arch** [comment]
Hi @DNDEBUG. Sometimes conflicts with external command might arise, true. But CliFM already provides some mechanisms to avoid them:

1. Disable/enable external commands via the [ext command](https://github.com/leo-arch/clifm/wiki/Introduction#ext-on-off-status)
2. Prevent all CliFM expansions (`sel` keyword, ELN's, etc) by prepending  `;` to your command. Example:
```
;chmod 600 sel 
```
In this case, neither `600`nor `sel` will be expanded; the command is sent as is to the system shell

3. Use a backslash to explicitly avoid ELN expansions:
```
chmod \600 file
```

**NOTE**: Bear in mind that numbers will only be expanded provided there's such ELN in the current files list. For example, `600` won't be expanded if there are less than 600 files in files list.

**Comment by DNDEBUG** [comment]
ight very cool

**Comment by leo-arch** [comment]
So, can we close this issue?

**Comment by DNDEBUG** [comment]
wait, one more thing
is it possible to specify a type of file for each directory?
for cue sheets for songs i want to open using mpv
but cue sheets for ps1 games i want to open with mednafen
so is is possible to specify that any cue inside ~/Games/* should be opened by mednafen?

**Comment by leo-arch** [comment]
That can be made per file name/MIME type, though not per directories. Just edit the mime file to your liking (`mm edit`). You'll find details and examples in the file itself.

**Comment by leo-arch** [comment]
Take a look at the [documentation](https://github.com/leo-arch/clifm/wiki/Specifics#resource-opener) too.

**Comment by DNDEBUG** [comment]
also, does sending a file to the trash copies the file then deletes the original or moves the file and renames it?
because i tried to send to the trash 2 big files and my system got unusable for some seconds 
i think clifm tried to copy the 2 files to thr trash at the same time

**Comment by leo-arch** [comment]
Don't remember right now. I'll take a look at it as soon as I'm back home.

**Comment by leo-arch** [comment]
You were right. I was using the `cp`/`rm` approach to trash files. Switched to a single `mv` command.

**Comment by DNDEBUG** [comment]
:sunglasses: nice, 3 problems found so far
i am trying to use clifm as my default file manager, havent found much motive to use pcmanfm again
won't remove it yet
unless i find a way to open clifm as default
for example on transmission if i doucle click on a folder, it will open pcmanfm in the folder i clicked
i don't know if its possible to do the same with clifm

**Comment by DNDEBUG** [comment]
i also want to ask for a feature
something like a temporary bookmark
the user can create a bookmark that will only exist in one session
will not interfere with other session
and when the session is closed the bookmar disappears

**Comment by leo-arch** [comment]
Of course it is. There's a [desktop file](https://github.com/leo-arch/clifm/blob/master/misc/clifm.desktop) for that that should be installed upon clifm installation. If you were just compiling from source, you only need to place the corresponding desktop file in `XDG_DATA_DIRS/applications` (usually, `/usr/share/applications` or `/usr/local/share/applications`).

**Comment by leo-arch** [comment]
As to temporary bookmarks, there is no such thing in CliFM, but it do provides [profiles](https://github.com/leo-arch/clifm/wiki/Specifics#profiles) and [pinned dirs](https://github.com/leo-arch/clifm/wiki/Introduction#pin-filedir). Finally, you can also make use of the [stealth mode](https://github.com/leo-arch/clifm/wiki/Specifics#stealth-mode) for a single session: it will start with default values, nothing will be read from nor written to disk, so bookmarks created in a stealth session will only last for that single session.

**Comment by DNDEBUG** [comment]
seems like it does work, but it is opening clifm in the background

**Comment by DNDEBUG** [comment]
tried Exec=$TERM clifm, didn't work
Exec=foot -e clifm did work

**Comment by leo-arch** [comment]
Nice to hear it works. But it should work out of the box. The `Terminal=true` field is supposed to instruct the launching application to run the command specified in `Exec` in a new terminal window. For exampĺe, if I run Thunar and click on `Open with CliFM` in the `Open with menu`, CliFM is launched on lxterminal (which I guess is the first terminal Thunar found available).

**Comment by DNDEBUG** [comment]
weirdly it didn't work, i don't know why
my $TERM is correct, it should be used
might be a problem with xdg

**Comment by leo-arch** [comment]
Or maybe some wayland related stuff (still on the old X11 here).

**Comment by DNDEBUG** [comment]
ah yeah, :disappointed: i left x11
wayland has become goodenough already
might be something related

**Comment by leo-arch** [comment]
Thank you very much for reporting these issues @DNDEBUG! If everything's fine now, please close this issue.

**Comment by DNDEBUG** [comment]
one last question
are you making sure to clean the code?
i saw that the binary was slowly growing and growing
and at one point the size went down dramatically
and i haven't changed the build options

**Comment by leo-arch** [comment]
I've been doing no big code changes lately, but mostly fixing bugs and little improvements here and there. The binary size is currently around 700Kb, depending on your compilation flags. Though it is always possible to shrink the code down, to make it faster and smaller, I really try to keep the code [clean, secure, and performant](https://github.com/leo-arch/clifm/tree/master/src#2-code-quality).

So, I'm not sure what the cause of that size decrement could be. But in any case, better down than up, isn't it?

**Comment by DNDEBUG** [comment]
i was just worried that you might forget some feature, function or code you don't need anymore and it is just there doing nothing

**Comment by leo-arch** [comment]
Well, that's always a possibility that, however, I try to firmly avoid.

**Comment by DNDEBUG** [comment]
nothing to ask for now, i'll close it and report if i find any other problem
