### ISSUE TITLE
Irrelevant text

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#119]
"The following is just a list of available commands and possible parameters. "
"For a complete description of each of these commands run 'cmd' (or press F2) "
"or consult the manpage (F1). You can also try the **'ih'** action to run the "
"interactive help plugin (it depends on FZF). Just enter **'ih'**, that's it.\n"

**Comment by leo-arch** [comment]
This text is aimed to inform the user about the various ways of getting help about commands in CliFM. Maybe it could rephrased, but I still think it's useful. Any proposal, alternative?

**Comment by DNDEBUG** [comment]
remove "Just enter 'ih', that's it"
you have 'ih' twice in the text

**Comment by leo-arch** [comment]
Got it.

**Comment by DNDEBUG** [comment]
i am making a tranlation, so i noticed it

**Comment by leo-arch** [comment]
Rephrased like this: 
```
You can also try the interactive help plugin (it depends on FZF): just enter 'ih', that's it.
```

**Comment by DNDEBUG** [comment]
:sunglasses: keep the good work

**Comment by leo-arch** [comment]
> I am making a translation

That's great! Portuguese I guess?

**Comment by DNDEBUG** [comment]
yes

**Comment by leo-arch** [comment]
Thanks!
