### ISSUE TITLE
Questions about trashing

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#120]
have you made sure that deleting stuff in the trash only deletes files there?
might be dangerous if for example a symbolic link directs to ~ and clifm deletes someone's home folder
also is there an option to print a list of files being deleted?
also clifm should ask for confirmation when deleting a file outside the trash

**Comment by leo-arch** [comment]
> have you made sure that deleting stuff in the trash only deletes files there?

When removing trashed files, via `t del`, **rm**(1) is executed over the parameters passed to the `t` command (which could only be actually trashed files, and thereby nothing outside the trash dir).

 > might be dangerous if for example a symbolic link directs to ~

**rm**(1), as made explicit by the corresponding *BSD manpages, do not derefence symlinks, that is, it removes the symlink as such, not its target.

> is there an option to print a list of files being deleted?

**rm**(1) has an option for this (`-v`). Though not used by CliFM's `r` command (which uses `rm -dIr` for directories and `rm -I` for files), you can always use the regular `rm` command appending the `-v` switch, or you can set an alias to it, say `alias r='rm -v'`, in the configuration file.

> clifm should ask for confirmation when deleting a file outside the trash

The `r` command uses the `-I` switch, which, according to the (Linux) manpage:

> prompt once before removing more than three files, or  when removing  recursively;  less intrusive than -i, while still giving protection against most mistakes

Again, you can create an alias to customize files deletion to whatever command/parameters you feel comfortable with.

**Comment by DNDEBUG** [comment]
aight
now about finding files
is it possible to use fzf in clifm to search files recursively into a folder?
i got a bunch of files i have to move and delete
but found no plugin to do it

**Comment by leo-arch** [comment]
You can recursively search files in CliFM (tough not via FZF) using the `-x` parameter to the quick search function (`/`):

```
/PATTERN -x
```

As to a plugin to do this via FZF, it's definitely a nice idea.

**Comment by DNDEBUG** [comment]
/PATTERN -x 
lists the files
but would be good something like
fzfthing del
selecet the files, then del eletes it
same for selection and moving

**Comment by leo-arch** [comment]
A FZF selection plugin already exists: `fzfsel`, bound to the `*` action (only works for the current dir).  `fzfnav`, bound to the `-` action, can select files as well, but allows you to navigate the file system: just select the files with TAB, and then press Ctrl-s to confirm selection. Selected files will be sent to CliFM's selection box. Then you operate on these files via the `sel` keyword (`r sel` or `m sel DIR`)

**Comment by leo-arch** [comment]
Added a [new plugin](https://github.com/leo-arch/clifm/blob/master/plugins/recur_rm.sh). Run it as `rrm PATTERN`, for example, `rrm *.pdf`. It recursively searches for files matching PATTERN (starting in the current directory). Select the files you want to be deleted (pressing <kbd>TAB</kbd>) and confirm selection pressing <kbd>Enter</kbd>). You'll be asked for confirmation; press `y` to actually remove selected files.

**NB**: Though I tried it myself and everything works fine, please try this plugin in a testing directory. It's new and might be bugged.

**Comment by DNDEBUG** [comment]
rrm not found

**Comment by leo-arch** [comment]
I forgot to update the default actions file. 

Update the file manually (running `actions edit`). Add `rrm` as follows:

```
rrm=recur_rm.sh
```

**Comment by DNDEBUG** [comment]
aight enough

**Comment by DNDEBUG** [comment]
@leo-arch  make it to prevent t *
maybe it can cause confusion with "t del" then *

**Comment by DNDEBUG** [comment]
something like t * .

**Comment by leo-arch** [comment]
Hi @DNDEBUG. I'm not sure about what causes the confusion exactly.

`t *` will trash all files in the current directory
`t del` will remove from the trash can (permanent removal) all files passed as parameters (`t del FILES`, mostly used with TAB completion), and, if no parameter, it will open the trash screen to select files from there (including the possibility to remove all trashed files: `*`).

Could you please be more descriptive as to what causes the confusion?

Btw, `t del`, and then `*`, or just `t del *` is the same as `t clear`.

**Comment by DNDEBUG** [comment]
dunno
how do i change t to output the deleted files?

**Comment by leo-arch** [comment]
Just `t` or `t ls` or `t list` to list currently trashed files.

**Comment by DNDEBUG** [comment]
not like that
i mean to list files while deleting
like rm -v

**Comment by leo-arch** [comment]
I see. That's a feature request. Please open e new issue requesting exactly that, so that I can keep better track of things to do.
