### ISSUE TITLE
Outdated .po files

### ISSUE THREAD

**Issue by leo-arch** [leo-arch/CliFM#122]
Hi @comradekingu! Long time no see.

I recently updated the .po files, but I'm getting [merging errors](https://hosted.weblate.org/projects/clifm/clifm/#repository) in Hosted Weblate. Could you please take a look at it?
Thank you very much in advance.

**Comment by comradekingu** [comment]
Heia :)
I think pushing from the Weblate repo and then doing it works better.
Similarly uploading from Weblate or editing there is safer.
Now there is a two-way merge without any prevailing logic for conflicts.
Are the PO files updated because there are changes in the POT, or is this some manual editing?
Edit: Charset being "CHARSET" I don't know how happened, nor the missing temp(?) files?
What was the original intent and procedure here?

**Comment by leo-arch** [comment]
I just updated the main .pot file and .po files for each language (not being a priority, translation files remained outdated for the last releases). The procedure was the usual: update files, push.

I really fear the work done so far could be be lost. I hope this won't be the case.

So, two questions:

1. How can this be fixed?
2. What's the adequate/recommended procedure when updating translation files?

**Comment by comradekingu** [comment]
Saved all the translations from Weblate.
I think just rolling back the update in Git should do the trick.
https://github.com/WeblateOrg/weblate/issues/3683 might be the issue, and that sounds like a likely error if the charset isn't correct.

https://github.com/leo-arch/clifm/blob/master/translations/german/clifm.po
Other than there being no revision date and nothing in "language" it seems correct…

**Comment by leo-arch** [comment]
Thanks @comradekingu!

So, let me see if I get this right:
I should roll back (push again) translation files before the update (87bd538), isn't it?
Now, should I do something in Weblate?
How do I update .po files without messing things up again?

**Comment by opiyodonpaul** [comment]
HELLO,I AM TRYING TO INSTALL KALI LINUX ON VIRTUAL BOX AND GETTING AN ERROR,I HAVE EVEN TRIED REINSTALLING THE VIRTUAL BOX AND GETTING THE SAME ERROR EVEN AFTER ENABLING VIRTUALISATION IN THE BIOS SETTINGS AND UINSTALLING ALL SECONDARY ANTI VIRUS SOFTWARES,,,PLEASE HELP???
![VB ERROR 1](https://user-images.githubusercontent.com/97983487/165368876-945e68e3-6203-4135-96f4-b808d6d2c0f4.PNG)

**Comment by leo-arch** [comment]
Hi @opiyodonpaul. Sorry, but this is clearly not the place to ask for help regarding Kali. Try posting on https://www.reddit.com/r/Kalilinux/. I'm sure people here will be helpful. Good luck!
