### ISSUE TITLE
huh, long text problems again?

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#124]
https://user-images.githubusercontent.com/98880063/166258356-01e659cc-38f4-4124-88d2-d74167c8ed3c.mp4

**Comment by leo-arch** [comment]
Hi @DNDEBUG. I've not exactly reproduced your issue, but I do fixed a screen size thing that might be related. Please give it a try.

**Comment by DNDEBUG** [comment]
i have tested and the bug does not happen anymore
i'll close it
