### ISSUE TITLE
bookmarks with spaces and digits

### ISSUE THREAD

**Issue by deathtrip** [leo-arch/CliFM#125]
**Describe the bug**
Looks like the "space in bookmarks" behavior described in #114 also applies to bookmark shortcuts and names.
When you use spaces in shortcuts or names you get `No such bookmark` error, when trying to go to the directory.

When your bookmark name or shortcut is a number, then you type eg. `bm 4` you get a `ELN name:/No such bookmark` error, but only when the ELN exists, when it doesn't it works correctly.

**To Reproduce**
1. Add a bookmark with a shortcut with a space in it, or a name with space.
2. Then run `bm your shortcut` or `bm your name`
3. See `No such bookmark` error
4. Do the same with numbers.

**Expected behavior**
1. Spaces should be handled correctly.
2. After you type bm, clifm should only check bookmark shortcuts and names and not the ELN numbers, unless the command is to add or remove a bookmark from a ELN. Otherwise you only get an error, when your bookmark matches a ELN.

**Desktop:**
 - OS: Linux
 - Terminal: kitty
 - CliFM version: 1.5.1.r290.g2dbdd79f-1
- Installation source: AUR

**Additional context**
When i used numbers and spaces in both shortcut and name i would get a `tags/: No such bookmark` error, but couldn't reproduce it later. And i don't use any tags.

I also named a few shortcuts and full names  "1 1" and "1 2" to test things, and now my bookmark numbers start at 2.
Also when i go to the bookmark manager and type 1 nothing happens, it just asks me again to choose a bookmark, without error.

**Comment by leo-arch** [comment]
Thanks for reporting @deathtrip! I'll take a look at it.

**Comment by leo-arch** [comment]
Well, the spaces thing should be fixed now. Time to work on the numbers issue.

**Comment by leo-arch** [comment]
Give it a try now. Works for me at least.

**Comment by deathtrip** [comment]
All works fine now, except for one little thing. When a bookmark shortcut is for example `1 3`, then `bm "1 3"` works as it should.
But in the bookmark manager "1 3" gives a `"1: No such bookmark`

Also the wrong numbering of bookmarks mentioned above was caused by accidently uncommenting a line at the beginning of bookmarks.cfm. It also caused a segmentation fault when exiting clifm. After fixing the bookmark file, the segfault disappeared.

**Comment by leo-arch** [comment]
Great. I'll address the `No such bookmarks` issue.

As to the segfault, that shouldn't happen, of course, no matter how you modify the config file. Must be fixed.

**Comment by leo-arch** [comment]
> In the bookmark manager "1 3" gives a "1: No such bookmark

Fixed. Please try it a let me know.

EDIT: I've finally reproduced and fixed the segfault you mentioned. Thank you very much for reporting this! It was a very important bug.

**Comment by deathtrip** [comment]
Tested it, and everything works fine. So i'm gonna close this.
