### ISSUE TITLE
List files while deleting

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#126]
add an option to list the files while they are being deleted like "rm -v"

**Comment by leo-arch** [comment]
Hey @DNDEBUG! Removed/trashed files are now listed immediately after the corresponding operation. Please give it a try and let me know what you think.

**Comment by DNDEBUG** [comment]
do i need to enable something? it didn't work for me

**Comment by leo-arch** [comment]
It should work out of the box. I tried a fresh install on two boxes and it just works. Are you using the last version? Maybe an issue with an old config file or something.

**Comment by leo-arch** [comment]
Btw, this feature works for internal commands: `r` and `t, tr, trash`. It won't work for shell commands like `rm`.

EDIT: If you want `rm` to run `r` instead of **rm**(1), just write an alias:

```sh
alias rm='r'
```

**Comment by leo-arch** [comment]
Hi @DNDEBUG. Could we close this issue?
