### ISSUE TITLE
inconsistent prompt behavior: as set in colorscheme vs as set by prompt command

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#132]
I want to use the security-scanner prompt with the zenburn colorscheme. I edited the zenburn.cfm file and set:
```
PromptStyle=custom
Prompt="security-scanner"
Notifications=true
```
I also commented out the original Prompt, WarningPrompt, and WarningString settings.

This results in a prompt that looks like:
```
[1] -:-:-:1 21:11 ~/projects/clifm
```

But what I would expect is the prompt as set by the "Prompt security-scanner" command:
```
T479[1] -:-:-:1 21:13 ~/projects/clifm
```
Attempting to set the prompt in the colorscheme file results in the Notifications segment of the prompt not appearing.

Am I not understanding how this supposed to work?

**Comment by leo-arch** [comment]
Hi @knodalyte. `PromptStyle` set to `custom` disables notifications (letting you compose them yourself via escape codes): default notifications might mess up your custom made prompt. So, just set `PromptStyle` to `default` and notifications should be back.

**Comment by leo-arch** [comment]
I agree however that `PromptStyle` and `Notifications` are confusing and unclear options. Both do basically the same, the former for the color scheme file and the latter for the prompts file. More consistent naming convention needed: just one option name (and value) is enough: `Notifications`: true/false.

I'll fix that up.

**Comment by leo-arch** [comment]
Done! `Notifications=true/false` works now in the color scheme file. `PromptStyle` (now deprecated) is kept however to preserve backward compatibility.

```sh
Prompt="security-scanner"
Notifications=true
```
This should be now enough.

**Comment by leo-arch** [comment]
Have been working further on this thing: I think it is now more robust and consistent. Recompile, take a look at the [new format](https://github.com/leo-arch/clifm/wiki/Customization#the-prompt), and let me know what you think.

You might need to recreate the prompts file. Just delete it (`r ~/.config/clifm/prompts.cfm`): it will be recreated automatically the next time you start CliFM.

**Comment by knodalyte** [comment]
Solved! Thank you for accommodating user error/misunderstanding and simplifying clifm to make it better.
