### ISSUE TITLE
cd jumps to clifm subdirectory in wrong tree

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#134]
Today I wanted to pull and build the latest clifm, I jumped to my projects directory, and then used the cd command to attempt to move to the clifm subdirectory. Instead, I ended up in my config/clifm directory! 

Directory tree snippet:
\~ 
  - projects
    - clifm

The following commands took me from ~/projects to ~/.config/clifm:
- clifm
- 9 (the ELN of clifm subdirectory
- cd clifm
- cd 9 

The only way I could seem to move from projects/ to projects/clifm was to use 
- cd ./clifm

This was surprising and the first time I have seen such [mis]behavior!

clifm version 1.6

**Comment by leo-arch** [comment]
Hi @knodalyte. Thanks for reporting!

Ok, that's weird. I'm currently running a fresh install and couldn't reproduce this issue. My guess is that something (alias, bookmark?) is redirecting the word `clifm` to something else (more precisely `~/.config/clifm`). There should be some relevant setting causing this behavior.

Have you tried a fresh install (with fresh config files), o maybe running under a different profile?

**Comment by knodalyte** [comment]
I will try with a new profile. I am also finding that it is not just clifm. I also must ruleout that some zsh plugin is at play here.

**Comment by leo-arch** [comment]
Good to know, cause I cannot even find a way to do what you say entirely from within clifm. Neither aliases nor bookmarks can do that: file names in CWD always take precedence.

**Comment by leo-arch** [comment]
@knodalyte, should we close this issue?

**Comment by knodalyte** [comment]
I created a new profile, and tested using it. Same problem found. 

I also disabled the zsh autocd option, thinking that might be causing this behavior. No change.

**Comment by leo-arch** [comment]
Is it still happening outside clifm?

EDIT: Have you tried using another shell? For my part, I still cannot reproduce the issue, no matter what shell I use.

**Comment by knodalyte** [comment]
Sorry, I did not express myself clearly when I said it didn't happen only with clifm. I meant that there were other directories for which I saw this behavior besides the clifm directory.

It seems to happen when I have a subdirectory of ~/.config with the same name as a subdirectory of ~/projects. Silmilarly, if I am in ~/.local/share and I attempt to move to the nvim subdirectory, I end up in ~/.config/nvim.

The reverse does not seem to happen: for example, if my current directory is ~/.config and I move to the qtile subdirectory, I end up in the correct place, not in ~/projects/qtile.

**Comment by leo-arch** [comment]
Ok. I'll try to reproduce that.

**Comment by leo-arch** [comment]
I replicated the issue setting `CDPATH` environment variable to `~/.config`. If this is your case, then the behavior you describe is the expected behavior (at least in bash): the bash builtin `cd` command does exactly the same.

So, just try unsetting `CDPATH` and the "issue"  should be solved.

I you want to keep the value of `CDPATH`, set the current directory as the first value as follows:

```sh
export CDPATH=".:$CDPATH"
```

For more information take a look at [this article](https://www.theunixschool.com/2012/04/what-is-cdpath.html).

**Comment by knodalyte** [comment]
I am glad to learn that the "issue" was with my misunderstanding of my environment rather than a mysterious behavior in clifm.

I apologize for wasting your time.  Closing this as due to user error.

**Comment by leo-arch** [comment]
No need for apologizes! And no, you didn't waste my time: solving issues, no matter the cause, is what we maintainers do (and we also learn in the process). If ain't broken, brake it, I like this saying.
