### ISSUE TITLE
Bleach: wrong replacement for äöü

### ISSUE THREAD

**Issue by Baerbeisser** [leo-arch/CliFM#135]
**Describe the bug**
ä/ö/ü (umlauts) are replaced by a/o/u

**Expected behavior**
ä/ö/ü should be replaced by ae/oe/ue and the rare uppercase Ä/Ö/Ü by Ae/Oe/Ue

**Reason**
I'm native german speaking and that's what we use as replacement. Aepfel vs. Apfel, Oesterreich vs. Osterreich.

**Comment by leo-arch** [comment]
Hi @Baerbeisser. Thanks for reporting! I'll fix that and let you know.

**Comment by leo-arch** [comment]
It should work as intended now. Give it a try and let me know if it works for you too.

**Comment by leo-arch** [comment]
Hi @Baerbeisser. Could you please confirm the issue was solved?

**Comment by Baerbeisser** [comment]
Sorry, had a deadline and was just tired at evenings.

Yes, it works fine, thanks!
