### ISSUE TITLE
Back-and-forth for workspace switch shortcuts

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/clifm#138]
Feature request:

Support back-and-forth toggling between two workspaces by pressing the same shortcut key twice.

For example, I have workspace 1 and workspace 2, and I workspace 1 is currently active. I press Alt-2 to activate workspace 2, and then press Alt-2 again to move back to the prior workspace, in this example, workspace 1.

**Comment by leo-arch** [comment]
Amazing synchro! I've been thinking about this a few days ago, specially looking at how some window managers work, and yes, they do exactly this.

It should be quite trivial to implement. I'll let you know as soon as I have this thing working.

Thanks for thesuggestions @knodalyte!

**Comment by leo-arch** [comment]
Done. Please give it a try.

Btw, since I find this feature a bit confusing, I added an option to disable it: `-W, --no-toggle-workspaces`

**Comment by knodalyte** [comment]
Works exactly as imagined. And yes, this was inspired by the Toggle option within Qtile's workspace (group in Qtile lingo) switching config.

Thank you! Feel free to close.
