### ISSUE TITLE
workspace names not working

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#144]
I have a couple workspace names defined in my profile:
```WorkSpaceNames="1=src,2=dest"```

If I try to change workspaces using the names, I get an error:
```
ws dest
ws: dest: No such workspace
```
Also, when I list workspaces using the ```ws``` command, the names are not listed although the workspace numbers and paths are.

**Comment by leo-arch** [comment]
Great. These issues are not really issues: they're just not implemented features. I didn't even think about it. Shouldn't be hard to implement.

I'll let you know as soon as it's done.

**Comment by knodalyte** [comment]
Not implemented as in "implementation is not complete" or as in "this was never expected behavior"? Maybe the documentation is getting ahead of the code. 

Should I not write issues until planned features are in a release?

In any case, glad to see the torrent of new features appearing!

**Comment by leo-arch** [comment]
Strictly speaking, neither of them. Regarding workspace names I just thought it would be nice to have names in the prompt, that's all. Never thought about making them work on the command line too. And this is why users feedback is essential: it unveils things/features a developer wasn't even able to see. So, thanks for that.

> Should I not write issues until planned features are in a release?

On the contrary. Whenever we decide to release a new version, features should be as mature as possible. Open issues whenever you feel you should. No problem at all.

**Comment by leo-arch** [comment]
Well, I was wrong. Names do work in the command line exactly as you said they should.

I think you only have a misspelled option name. This is wrong:

```sh
WorkSpaceNames="1=src,2=dest"
```

It should be rather:

```sh
WorkspaceNames="1=src,2=dest"
```
no uppercase `s`.

**Comment by knodalyte** [comment]
Works as documented.
