### ISSUE TITLE
Building with -D_NO_ICONS causes error: 'struct props_t' has no member named 'attr'

### ISSUE THREAD

**Issue by FluffyJay1** [leo-arch/CliFM#145]
```
src/properties.c:748:28: error: 'struct props_t' has no member named 'attr'
  748 |                        prop_fields.attr == 1 ? attr_s : ""
      |                                   ^
```

Seems like a small oversight from [b131432ad375d31bc87c51cd12f3c3aca75f0163](https://github.com/leo-arch/clifm/commit/b131432ad375d31bc87c51cd12f3c3aca75f0163)

I'm assuming the line's supposed to look like this
https://github.com/leo-arch/clifm/blob/fce5d23e47b947e1d32f1ecddf7c2c0f93cb6f55/src/properties.c#L732
not
https://github.com/leo-arch/clifm/blob/fce5d23e47b947e1d32f1ecddf7c2c0f93cb6f55/src/properties.c#L748

also there seems to be some other inconsistencies in that area

**Comment by leo-arch** [comment]
Hi @FluffyJay1, thanks for pointing this out! Fixed.

EDIT:

> there seems to be some other inconsistencies in that area

I guess you refer to the fields values. Some of them should be `!= 0` and not `== 1`. If this is the case, these inconsistencies were solved too.

**Comment by FluffyJay1** [comment]
Works for me now, thanks
