### ISSUE TITLE
cfm filetype conflicts with vim's ColdFusion filetype

### ISSUE THREAD

**Issue by harriott** [leo-arch/CliFM#146]
# bug
Opening a `*.cfm` configuration file in `vim` gets it recognised as a `ColdFusion` configuration file, with subsequent incorrect syntax highlighting.

## where this happens
In [filetype.vim](https://github.com/vim/vim/blob/master/runtime/filetype.vim), `*.cfm` is identified as filetype `cf`, with syntax highlighting as per [cf.vim](https://github.com/vim/vim/blob/master/runtime/syntax/cf.vim) (for [ColdFusion Markup Language](http://en.wikipedia.org/wiki/ColdFusion_Markup_Language)).

# suggested fix
Convert all of your `*.cfm` configuration files to something unused elsewhere, such as `*.clifm`.

# reason
We can then write a filetype plugin for your configuration files - I've begun one - [vim-clifm](https://github.com/harriott/vim-clifm).

**Comment by leo-arch** [comment]
Hy @harriott, thanks for reporting! I have already noticed this conflict, but didn't thought it might cause this kind of issue. Changing this should take only a few minutes, no problem. The only drawback would be backwards compatibility. Let me think of a way to handle this appropriately (maybe a command line switch). I'll let you know.

Btw, thanks for vim-clifm, that's cool!

**Comment by leo-arch** [comment]
Hi @harriott. The transition to `.clifm` config files is ready. Please give it a try: it should be pretty smooth. Old config files will be automatically renamed (after asking the user) using the new file extension.

Now it only remains to fix whatever is broken because of this change. Hope it's not much.

**Comment by harriott** [comment]
Wow, that was quick. I switched to AUR's [clifm-git](https://aur.archlinux.org/packages/clifm-git), which got me `CliFM v1.6.1` with your change over to `*.clifm`. All working, and I've updated [vim-clifm](https://github.com/harriott/vim-clifm) accordingly.

**Comment by leo-arch** [comment]
Perfect. Closing then and thanks again @harriott!
