### ISSUE TITLE
Compile and use on termux 

### ISSUE THREAD

**Issue by mhdzli** [leo-arch/CliFM#148]
**Is it possible to compile clifm on termux?**
I tried many times but didn't have any progress compiling clifm on termux.

It's the most suitable file manager for termux IMO. Minimal, fast and good experience on smaller screens.

**Comment by leo-arch** [comment]
Hi @mhdzli. Possible it is, of course. But actually haven't been tested on termux. In principle, _clifm_ does work on ARM, so that shouldn't be any issue. However, we most likely need to do some porting work.

I'll give it a try and let you know.

**Comment by leo-arch** [comment]
Hey @mhdzli. Got it working!

Compiling on termux:

1. Install the following packages: `libcap`, `libacl`, `file`, and `clang`. Readline should be already installed. If not, install it.
```
pkg in libcap libacl file clang
```
2. Clone the clifm repo as usual:
```sh
git clone https://github.com/leo-arch/clifm
cd clifm
```
3. Compile as follows:
```sh
clang -D_NO_GETTEXT -o clifm src/*.c -Wall -Werror -lreadline -lcap -lacl -lmagic -landroid-glob
```

Please let me know if it works for you too.

**Comment by leo-arch** [comment]
Lira, the resource opener, isn't working as expected. Working on a fix.

EDIT: The problem was not _clifm_, but the `ed` editor. Lira founds **ed**(1) to open text files and executes it, but `ed` hangs. The solution is simply to specify a working application, say, **nano**(1):

1. Enter `mm edit nano`
2. Set `nano` as opening application for text files:

```sh
###########################
#  File names/extensions  #
###########################
X:N:(.*\.clifm$|clifmrc)=$EDITOR;$VISUAL;nano;kak;micro;nvim;vim;vi;mg;emacs;ed;mili;leafpad;mousepad;featherpad;gedit -s;kate -n;pluma --new-window
!X:N:(.*\.clifm$|clifmrc)=$EDITOR;$VISUAL;nano;kak;micro;nvim;vim;vi;mg;emacs;ed
...
# Text
X:(^text/.*|application/json|inode/x-empty)=$EDITOR;$VISUAL;nano;kak;micro;dte;nvim;vim;vi;mg;emacs;ed;mili;leafpad;mousepad;featherpad;nedit;kate;gedit;pluma;io.elementary.code;liri-text;xed;atom;nota;gobby;kwrite;xedit
!X:(^text/.*|application/json|inode/x-empty)=$EDITOR;$VISUAL;nano;kak;micro;dte;nvim;vim;vi;mg;emacs;ed
...
```
If you experience some input lag (most likely due to my SSH connection), try disabling suggestions:

```sh
./clifm --no-suggestions
```
EDIT: You can ignore this if installing via make. See comment below.

**Comment by leo-arch** [comment]
We have a Makefile now!

New install instructions:

```sh
git clone https://github.com/leo-arch/clifm
cd clifm
make -f misc/termux/Makefile install
```

**Comment by leo-arch** [comment]
[Documentation](https://github.com/leo-arch/clifm/wiki/Introduction#gear-compiling-and-installing-clifm) updated.

**Comment by mhdzli** [comment]
Wow that was fast. Thank you so much.
Great job.
It's awsome.
![20220805_083734](https://user-images.githubusercontent.com/50514359/182999977-48b22da0-5cb1-410f-8100-9ea02d25fe3e.jpg)

**Comment by mhdzli** [comment]
Yes that works for me too :)

**Comment by nakhla** [comment]
Any ready binary for arm architecture, i don't want to go thorough process of compiling.

**Comment by leo-arch** [comment]
Hi @nakhla. Yes, just run `pkg install clifm`.
