### ISSUE TITLE
Error compiling in termux according to instructions

### ISSUE THREAD

**Issue by jggamba** [leo-arch/CliFM#149]
**Describe the bug**
Error compiling the package as instructed:

**To Reproduce**
Installed the required packages for termux: libcap, libacl, readline, file, and I ran the [instructed commands](https://github.com/leo-arch/clifm/wiki/Introduction#small_blue_diamond-c-termux), got this error:

```clang-14: error: the clang compiler does not support '-march=native' make: *** [misc/termux/Makefile:29: clifm] Error 1```

**Expected behavior**
Package compiled and installed.

**Desktop:**
 - OS: Android 12, One UI 4.1, SM-S906E
 - Terminal: Termux
 - CliFM version: 1.6
- Installation source: Git

**Additional context**
Finally got it compiled and installed, as [hinted in reddit](https://www.reddit.com/r/termux/comments/whnk4p/comment/ij842og/?utm_source=share&utm_medium=web2x&context=3) editing the Makefile on line 23 the flag ```-march=armv8a```, with the following warnings:

```make -f misc/termux/Makefile install
cc -o clifm src/*.c -O3 -fstack-protector-strong -march=armv8a -Wall -Wextra -DCLIFM_DATADIR=/data/data/com.termux/files/usr/share -D_NO_GETTEXT -D__TERMUX__  -lreadline -lacl -lcap -lmagic -landroid-glob
src/properties.c:413:41: warning: format specifies type 'long long' but the argument has type 'long' [-Wformat]
        printf(_("\tBlocks: %s%lld%s"), cbold, attr.st_blocks, cend);
                              ~~~~             ^~~~~~~~~~~~~~
                              %ld
src/properties.c:421:42: warning: format specifies type 'long' but the argument has type 'int' [-Wformat]
        printf(_("\tIO Block: %s%ld%s"), cbold, attr.st_blksize, cend);
                                ~~~             ^~~~~~~~~~~~~~~
                                %d
src/properties.c:424:42: warning: format specifies type 'unsigned long long' but the argument has type 'ino_t' (aka 'unsigned long') [-Wformat]
        printf(_("\tInode: %s%llu%s\n"), cbold, attr.st_ino, cend);
                             ~~~~               ^~~~~~~~~~~
                             %lu
src/properties.c:431:39: warning: format specifies type 'long long' but the argument has type 'dev_t' (aka 'unsigned long') [-Wformat]
        printf(_("Device: %s%lld%s"), cbold, attr.st_dev, cend);
                            ~~~~             ^~~~~~~~~~~
                            %lu
4 warnings generated.
```

**Comment by leo-arch** [comment]
Thanks for reporting @jggamba!

Regarding the `-march=native` flags, it seems that clang does not support it on some ARM platforms (tested on `armv7l` without any warning). Removing this flag in the Makefile actually solves the issue, but still want a closer inspection on why the warning is generated.

As to the formatting warnings, again, not getting any of those on `armv7l`, so it seems to be again a platform-dependent issue. Not a big deal, but it isn't nice either.

Thanks for the logs, very useful. I'll let you know as soon as I make some advance on these issues.

**Comment by leo-arch** [comment]
Hey @jggamba, errors and warnings should be gone now. Please give a try and let me know.

**Comment by jggamba** [comment]
Yes, **@leo-arch** the warnings are gone now. Great work btw.

**Comment by leo-arch** [comment]
Glad to hear that! And thanks again @jggamba.

Please do no hesitate to report whatever issue you might find.

**Comment by laurentlbm** [comment]
[CliFM 1.7 has been added to the Termux package repository](https://github.com/termux/termux-packages/pull/11822). It’s available in the main repo and should be in the mirrors soon.

It also just showed up on [Repology](https://repology.org/project/clifm/versions).

**Comment by leo-arch** [comment]
Awesome! Thanks @laurentlbm.
