### ISSUE TITLE
warning: 'memchr' specified bound 4096 exceeds source size 8 (and similar)

### ISSUE THREAD

**Issue by jonathanspw** [leo-arch/CliFM#154]
**Describe the bug**
There are quite a few instances during compilation warning about memchr out of bounds.

```
/builddir/build/BUILD/clifm-1.6/src/strings.c:185:33: warning: 'memchr' specified bound 4096 exceeds source size 8 [-Wstringop-overrea
d]
  185 |         return (size_t)((char *)memchr(s, '\0', MAX_STR_LEN) - s);
      |                                 ^
/builddir/build/BUILD/clifm-1.6/src/config.c: In function 'read_config':
/builddir/build/BUILD/clifm-1.6/src/config.c:2069:30: note: source object allocated here
 2069 |                         char opt_str[SUG_STRATS + 1] = "";
      |                              ^
In function 'xstrnlen',
    inlined from 'get_last_path.isra' at /builddir/build/BUILD/clifm-1.6/src/init.c:2254:28:
/builddir/build/BUILD/clifm-1.6/src/strings.c:185:33: warning: 'memchr' specified bound 4096 exceeds source size 4094 [-Wstringop-over
read]
  185 |         return (size_t)((char *)memchr(s, '\0', MAX_STR_LEN) - s);
      |                                 ^
```

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/9805/90929805/build.log

**To Reproduce**
1. Compile code with full verbosity.

**Expected behavior**
No potential memory out of bounds scenarios.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora (all versions)
 - Terminal N/A
 - CliFM version 1.6
- Installation source GitHub source package

**Additional context**
N/A

**Comment by leo-arch** [comment]
Thanks @jonathanspw! I'll take a look at it.

EDIT: All warnings coming from a single function. Should be trivial to solve.

**Comment by leo-arch** [comment]
Warnings should be gone now.

**Comment by jonathanspw** [comment]
Awesome I'll test the patch.

Do you have any idea when 1.7 will be released?  I'm waiting to put it in Fedora as 1.6>1.7 will be a backwards-incompatible upgrade due to the config file change so starting with 1.7 will hopefully keep us able to update the OS packages for much longer versus if I add 1.6 now and then can't go to 1.7 on the stable Fedora branches.

**Comment by leo-arch** [comment]
Well, there a a few important changes I need to make sure they're stable. Maybe a week or two, but I can't promise anything. Anyway, I'll let you know as soon as 1.7 is ready.

Btw, having _clifm_ in Fedora repos will great for the project! Thanks.

**Comment by jonathanspw** [comment]
Sounds good, no rush!

It will also be in EPEL for RHEL, AlmaLinux, Rocky, etc.

**Comment by jonathanspw** [comment]
I'll be pushing a pre-release 1.7 tag of the latest commit tree ([bd9457f](https://github.com/leo-arch/clifm/commit/bd9457fb4aec0a797bf0b449fc7f33d3277af15d) as of this writing) so that we can get it out to all Fedora/EPEL versions without having to worry about the backwards-incompatible change.

Once you tag 1.7 for release we'll track the official releases.

The version tag will look like this: `clifm-1.7~^1.bd9457f-1` which looks like a mess but when 1.7 is tagged for release a "normal" `clifm-1.7-1` will supersede this and update everything accordingly.

**Comment by leo-arch** [comment]
Thanks @jonathanspw! I was just waiting for you to confirm the warnings are actually gone. I plan to release 1.7 in a few days (maybe less): code that's still unstable was removed, and will make it maybe in 1.8.

Currently working on a last fix. Once this is done, 1.7 will be out.

**Comment by jonathanspw** [comment]
Ohh I thought you were still a few weeks out.

The warnings appear fixed, yes.

**Comment by leo-arch** [comment]
Well, a few hours after I said "a few weeks" a new instability came out in the new code. This code makes suggestions more performant on unreliable, high latency connections, like SSH, but it has to wait while I keep working on it (maybe 1.8 if everything goes as expected). In the meanwhile, two months after 1.6, and with several improvements, 1.7 will be released.

**Comment by leo-arch** [comment]
[CliFM 1.7 is finally out!](https://github.com/leo-arch/clifm/releases/tag/v1.7)

**Comment by jonathanspw** [comment]
Awesome!  We'll push 1.7 out instead then :)

**Comment by jonathanspw** [comment]
@leo-arch https://bodhi.fedoraproject.org/updates/?packages=clifm

Builds are done.  They'll go to testing repos tonight, and stable in a week (unless the packages get thumbs up/upvotes then it can happen sooner).

**Comment by leo-arch** [comment]
That's amazing! Thanks so much @jonathanspw! This is a big step forward for _clifm_.

**Comment by leo-arch** [comment]
Hey @jonathanspw! Just a little observation: the package description in Fedora repos includes the footnotes (which only make sense in the `README.md`). Is it possible to remove them?

More specifically, this:
```
a command-line interface (CLI),1 also known as REPL.2
```

should be replaced by this:
```
a command-line interface (CLI), also known as REPL.
```

**Comment by jonathanspw** [comment]
Fixed in https://bodhi.fedoraproject.org/updates/?search=clifm-1.7-2

**Comment by leo-arch** [comment]
Thanks!

**Comment by leo-arch** [comment]
Hey @jonathanspw! Is there some problem with the Fedora packaging? Clifm is stuck at 1.10 (even Rawhide). If there's something I can help with just let me know.

**Comment by jonathanspw** [comment]
> Hey @jonathanspw! Is there some problem with the Fedora packaging? Clifm is stuck at 1.10 (even Rawhide). If there's something I can help with just let me know.

The system that emails me when you cut new releases wasn't working right, mostly because I forgot to link it up when I built the package :)

Fixed that now so I'll stay on top of updates.  Are there any breaking changes between 1.10 and 1.15?  If not I can push all releases up to 1.15.

**Comment by leo-arch** [comment]
> Fixed that now so I'll stay on top of updates.

Really good news.

> Are there any breaking changes between 1.10 and 1.15?

No. Updating to 1.15 should be pretty safe (users might want to update config files however, though nothing should break if not).

**Comment by jonathanspw** [comment]
Updates will push out to testing repos tonight, then production in a week unless people test/upvote the updates in which case they'll hit prod repos faster.

https://bodhi.fedoraproject.org/updates/?search=clifm-1.15

**Comment by leo-arch** [comment]
Thanks @jonathanspw!

**Comment by leo-arch** [comment]
Hi @jonathanspw! I don't want to bother you, but the **clifm** package hasn't been updated in the Fedora repos for a while. The Bug list says something about the package updates policy and licensing. Is there anything I can do to help with?

**Comment by carlwgeorge** [comment]
I'm also a Fedora packager, and I helped with the initial package review for clifm.  I just sent a pull request to update it to version 1.22.

https://src.fedoraproject.org/rpms/clifm/pull-request/2

**Comment by leo-arch** [comment]
Thanks @carlwgeorge!

**Comment by leo-arch** [comment]
Hi @jonathanspw, @carlwgeorge. Clifm 1.26 is out (last version in Fedora repos is 1.22).

**Comment by jonathanspw** [comment]
> Hi [@jonathanspw](https://github.com/jonathanspw), [@carlwgeorge](https://github.com/carlwgeorge). Clifm 1.26 is out (last version in Fedora repos is 1.22).

On it!

**Comment by leo-arch** [comment]
Hey @jonathanspw, @carlwgeorge, [clifm 1.26.3](https://github.com/leo-arch/clifm/releases/tag/v1.26.3) is out!

**Comment by jonathanspw** [comment]
1.26.3 update shipped for all active branches of Fedora/EPEL: https://bodhi.fedoraproject.org/updates/?search=clifm-1.26.3

Should hit stable in a week or so.

**Comment by leo-arch** [comment]
Awesome. Thanks @jonathanspw.

**Comment by leo-arch** [comment]
Hi @jonathanspw. [Clifm 1.27](https://github.com/leo-arch/clifm/releases/tag/v1.27) is out!

**Comment by leo-arch** [comment]
There was a little annoying bug. Latest released version is [1.27.1](https://github.com/leo-arch/clifm/releases/tag/v1.27.1).

**Comment by leo-arch** [comment]
Hey @jonathanspw, @carlwgeorge, [Clifm 1.28](https://github.com/leo-arch/clifm/releases/tag/v1.28) is out!

**Comment by jonathanspw** [comment]
Updates in the pipes for Fedora rawhide, 44, 43, EPEL 10 (10.3), EPEL 10.2, EPEL 9, and EPEL 8.

**Comment by leo-arch** [comment]
Hey guys (@jonathanspw, @carlwgeorge), [version 1.29](https://github.com/leo-arch/clifm/releases/tag/v1.29) is finally out!
