### ISSUE TITLE
Japanese, Chinese or Korean file names cause misaligned columns

### ISSUE THREAD

**Issue by queer-bird** [leo-arch/CliFM#155]
**Describe the bug**
Japanese, Chinese or Korean file names cause misaligned columns, making it hard to read and find the folder you are looking for.
Seems to be happen regardless of terminal emulator, but I only tried Alacritty and Foot.

**To Reproduce**
1. Run clifm
2. Enter directory with sub-directories in any of the above languages
3. See error

**Expected behavior**
Directories and files of any script should be aligned the same as Latin script

**Screenshots**

[Screenshot](https://ibb.co/8gSgjyM)

**Desktop:**
 - OS: Gentoo 
 - Terminal: Alacritty, Foot
 - CliFM version 1.7
- Installation source: Gentoo GURU overlay

**Comment by leo-arch** [comment]
Hi @queer-bird. Thanks for reporting.

Could you copy here the exact names of those directories, so I can more precisely reproduce the issue?

**Comment by queer-bird** [comment]
OK, just to have all of our bases covered, here is all the subdirectories in my Music folder that I showed in the example


1 800 PAIN
1st PLACE
5pb.Records
40mP
88rising
96猫
100 gecs
164
8485
A. G. Cook
Alice Gas
Alice Longyu Gao
ALIEN WIZARD
Ana Frango Elétrico
Antischism
Appendix
Ashnikko
ATOLS
AVTechNO!
Beastie Boys
Billy Talent
Black Dresses
black midi
Blood on the Dance Floor
Blur
Breathe Carolina
BROCKHAMPTON
CAKE POP
Charli XCX
Choking Victim
Circus-P
Citizen Fish
clipping_
CMTEN
Crack Rock Steady
Cro‐Mags
Crystal Castles
Daft Punk
Daniel Kahn & The Painted Bird
daniwellP
DAOKO
Dayglo Abortions
Dead Kennedys
dead prez
Dead Rejects
Death Grips
DECO_27
Descendents
DEVO
Die Antwoord
Djemynai
dmARTS
Doja Cat
Dorian Electra
Dot Dot Curve _)
Dystopia
Earl Sweatshirt
Earwax Jam x CDR
ElyOtto
Erich-Weinert-Ensemble
EXIT TUNES
EZFG
Fagatron
Flux of Pink Indians
food house
Frank Sinatra
fraxiom
Fucknrad
Full Tac_Lil Mariko_Rico Nasty
Future & Juice WRLD
Getter
Ghostemane
girl in red
Goonncity
Gorillaz
GRLwood
haruka.M
Immortal Technique
Imperial Triumphant
INDK
I Set My Friends on Fire
Jack Parow
Jack Stauber
John Linnell
Joji
Jpegmafia
JPEGMAFIA
Juice WRLD
Kero Kero Bonito
Kikuo Sound Works
Leftöver Crack
Lemon Demon
Lil Darkie
Lil Peep
Lil Uzi Vert
livetune
Loli in early 20s
MARETU
MASA Works DESIGN
Math the Band
Matmos
MC BUSHPIG
Men’s Recovery Project
MGMT
Mindless Self Indulgence
Mind Of Asian
Mono Puff
Mood Killer
Moranbong Band
Morning Glory
natsuP
Oliver Tree
OST
otetsu
PASSENGER OF SHIT
Patricia Taxxon
Perfume
Phil Ochs
pilotredsun
Pink Guy
PLANARIYA Recordings
Playlists
Pochonbo Electronic Ensemble
Polyphia
Poppy
Prince
Pussy Riot
Quelle Chris
Reagan Youth
REFLECTION
REOL
Rico Nasty
Rina Sawayama
S3RL
Scarlxrd
Seth MacFarlane
Sewerslvt
ShitWank
Ski Mask the Slump God
Slayyyter
Sleater Kinney
Snail’s House
SOPHIE
Soviet Sex
Soyuz
Star Fucking Hipsters
Stiff Little Fingers
Sublime
SUICIDAL RAP ORGY
Talking Heads
The Black Eyed Peas
The Casualties
The Comet Is Coming
The Coup
The Dead Milkmen
the heavenly yard
The Pillows
The Red Army Choir
The Redskins Complete_the redskins
THE STALIN
The Voidz
THE WIND CHIMES
They Might Be Giants
TOY'S FACTORY
Tyler, the Creator
U_M_A_A
Various Artists
Vocaloid Loud Project
Vulfpeck
Wavves
Whokilledxix
Wowaka
Xiu Xiu
Yamaha
おとぼけビ〜バ〜
かごめp
きくお
きゃりーぱみゅぱみゅ
じん
ギガp×おればなな
デッドボールp
ピノキオピー
事実上
光収容の倉庫
初音ミク
周平
岐阜県
春ねむり
松下
稲葉曇
鍾翔宇 Xiangyu
鬱p
김예림 [투개월] (lim Kim (togeworl))

**Comment by leo-arch** [comment]
Great, thanks!

**Comment by leo-arch** [comment]
Are you running with Unicode enabled, isn't it?

Just in case, use the `uc` command as follows:

```sh
uc on
```

**Comment by queer-bird** [comment]
Oh dang, you're right, that was the problem. Sorry for wasting your time, haha

**Comment by leo-arch** [comment]
Don't worry @queer-bird! Happy to help.

I'm starting to think that disabling Unicode should not even be an option.

**Comment by queer-bird** [comment]
Blame Gentoo (and me missing a step during installation) for this one, haha. In Gentoo you have to manually select your locale during installation.
