### ISSUE TITLE
view command renders list but not content - zsh error

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#159]
**Describe the bug**
When I invoke the new *view* command, I see the list of files in the current directory, but contents show as:
```zsh:1 bad pattern: ^[[tJ```

**To Reproduce**
see above

**Expected behavior**
As I move between files in the list, I would expect that for at least some file types, I would see the file contents in the viewing pane at the right.

**Screenshots**
![screen](https://user-images.githubusercontent.com/783768/198104022-55434e9d-38a6-4e66-ad24-226e7f301bdc.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Terminal: kitty
 - CliFM version: 1.8
- Installation source: git
- shell: zsh

**Comment by leo-arch** [comment]
Hi @knodalyte. It seems that zsh does not understand the ED escape sequence. This should be easily fixed.

I'll let you know as soon as I solve this issue. And thanks for reporting, as always!

**Comment by leo-arch** [comment]
Have you tried running on a different terminal and/or shell?

Trying to reproduce the issue.

**Comment by knodalyte** [comment]
Same issue under alacritty, also under bash.

**Comment by leo-arch** [comment]
Ok. I'll try removing the escape code altogether.

**Comment by leo-arch** [comment]
Give it a try now.

**Comment by leo-arch** [comment]
What's you version of fzf?

**Comment by knodalyte** [comment]
update fixed it

Thank you!

BTW, fzf is 0.34
