### ISSUE TITLE
short/long file display per workspace

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#160]
Please make the short or long file display dependent from the workspace. Currently it's not. I would like to use a workspace with short and another one with long display.

**Comment by leo-arch** [comment]
Done. The [autocommands](https://github.com/leo-arch/clifm/wiki/Specifics#autocommands) function allows you now to set/unset settings per workspaces, and not only per directory/path names.

For example, to make the second workspace to always list files in long view, no matter what the current directory is, just add this line to the configuration file:

```sh
autocmd @ws2 lv=1
```

**Comment by leo-arch** [comment]
Hi @muellerto. Should we close this issue?

**Comment by muellerto** [comment]
The problem is that the long/short file view setting is still global for all workspaces. When you have two workspaces open and both have currently short file view and you change now one to long file view the other one will also be affected, and if you have even more they all will be, too. They are not independent. This may have fatal consequences when you have directories with 200 files in it where you never would switch the long file view on.

I don't use workspaces for concrete purposes so that I could say this workspace has always short view and that one has always long view. I use Alt-l a lot, temporary.

**Comment by leo-arch** [comment]
Great. Thanks for reporting. I'll take a look at it.

Wait. Are you using the [new autocommands feature](https://github.com/leo-arch/clifm/issues/160#issuecomment-1304697650) to set settings per workspace?

EDIT: Ok. I see what you mean: you're asking for workspace independent settings (as it is in the case of profiles). Well, settings are currently global, as you said, and changing this means refactoring the whole way in which settings are handled, so this could take some time.

As a workaround, I suggest trying to use autocommands to always list files, for all workspaces, in short view. In this way, `Alt-l` would only be effective as much as you remain in the current workspace: if you switch to another workspace, and even if you go back to the previous one (no matter if it was listing files in long view), the short view will be applied. Not ideal, but pretty close to what you're asking for. To get this, add the following lines to your config file:

```sh
autocmd @ws1 lv=0
autocmd @ws2 lv=0
autocmd @ws3 lv=0
autocmd @ws4 lv=0
```
The long view is thus always local.

BTW, this should achieve the same result (in a single line, which is better/faster):

```
autocmd /** lv=0
```

**Comment by leo-arch** [comment]
@muellerto, what about the above workaround? Does it work for you?

**Comment by muellerto** [comment]
No, it doesn't. I checked both variants.

I see that a workspace gets then the same fix setting everytime when I switch to that workspace. But this is too static. This assumes that the user uses workspaces always for the same directories and tasks. I never do, I change directories and also long and short view all the time. That's why I suggested that a workspace just keeps the view setting it currently has, regardless of what it is, short or long. I can't predefine my workspaces, I open them on the fly.

Enter ws1, type Alt-l to switch to long view. Now change to ws2 (this will probably show short files there, OK, may be, doesn't matter) and then change back to ws1 -> short files now, damned.

BTW: there are also more settings which should in my opinion be workspace local, sorting for instance, perhaps also the show hidden files option, a file filter. Such settings depend just on the contents you want to see, it can make sense that you want to see hidden files on one place and surely not on another one. The user must have the opportunity to decide in such situations.

**Comment by leo-arch** [comment]
Thanks for your feedback, again. Added to my TODO list.

**Comment by leo-arch** [comment]
HI @muellerto. Added support for private/local workspace settings. Just add this new option to your config file:

```sh
PrivateWorkspaceSettings=true
```
NOTE: This is just for testing purposes, and it's not even documented yet. This option name might change in a future. Too long, and not that descriptive, isn't it? I'm sure there should be a more appropriate name out there; maybe some shell/file manager/window manager implementing something like this might provide a better name. Any suggestion?

Local setting changes (either via command line or keyboard shortcuts) will be remembered per workspace. For the time being, only the following options are supported (mostly those controlling the list of files are included):

| Option | Command/keybinding |
| --- | --- |
| `Color scheme` | `cs` |
| `Dirs first` | `Alt-g` |
| `Files counter` | `fc` |
| `Filter` | `ft` |
| `Hidden files` | `Alt-.` |
| `Long view` | `Alt-l` |
| `Light mode` | `Alt-y` |
| `Max files` | `mf` |
| `Only dirs` | `Alt-,` |
| `Pager` | `pg` |
| `Sort` | `st`, `Alt-z / Alt-x` |
| `Toggle max name length` | `Ctrl-Alt-l` |

Bear in mind:
1. Workspace options set via autocommands (using the `@N` notation) override any of the above
2. These settings are local and won't be kept across `clifm` runs. At startup, all workspaces are initialized using the values set in the configuration file, which are global.

**Comment by muellerto** [comment]
Yeah, bestest clifm ever!!! (until now)

And the list of included options is really impressive. Haven't thought that it could be so many but everyone makes sense. Thanks a lot for this comprehensive approach.

P.S.: My gcc (12.2.0, Linux and MinGW) shows a warning since yesterday. An sprintf() destination buffer is to short.

**Comment by leo-arch** [comment]
> P.S.: My gcc (12.2.0, Linux and MinGW) shows a warning since yesterday. An sprintf() destination buffer is to short.

I'll fix that.

EDIT: The warning should be gone now.

**Comment by leo-arch** [comment]
Closing then. Please reopen in case you observe anything unusual or unexpected.
