### ISSUE TITLE
clearing the selection complicated

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#163]
Clearing the selection is sometimes needed because it survives a lot of actions without clearing itself. So we have the `ds` command. But `ds` requires an operand or it asks interactively what to do. So you must either type `ds *` [Enter] or `ds` [Enter] and then `*` [Enter]. I find this complicated, `*` needs Shift on my keyboard.

**Possible alternatives for `ds *`**
- `ds` [Enter], then open the question and let the question accept [Enter] as a valid answer so the user could just type `ds` [Enter][Enter]
- `Ds`with no operand

The easiest idea I have is:
- `s` with no operand, this would be very easy to understand: "select nothing"

I would also welcome a command like `S` ... (I mean: uppercase `S`) meaning "_replace_ the current selection by ..." so that a preceding clearing of the selection is not needed at all.

**Comment by muellerto** [comment]
OK, I found `Alt-d` now, will use that in future ...

**Comment by leo-arch** [comment]
Besides `Alt-d`, `ds a` and `ds all` are available (instead of `ds *`).

**Comment by muellerto** [comment]
OK so far.
