### ISSUE TITLE
symbolic link points onto a directory, what's the right parent directory?

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#164]
**Describe the bug**
When clifm shows the contents of a symbolic link which points to a directory and you type `..` - which is the right parent directory? I'm not sure.

**To Reproduce**
We have the following situation:

    dir A1                 dir B1
      subdir A2     ->       symlink B2 (points to A2)

clifm shows the files of B2.

When I now type `..` I would expect that I get into B1 because B1 is the parent of B2 and probably I was in B1 before I came into B2. But clifm jumps into A1. I find this unexpected, A1 is in my case often completely elsewhere on another partition or even disk. And getting back is then sometimes no easy.

This happens at least with symbolic links, didn't try hard links until now, on Linux and Windows.

**Comment by leo-arch** [comment]
I get it, and you're right about this one. The parent directory of a symlink pointing to a directory should be the parent of the _symlink itself_, and not that of the _target directory_.

I'll start working on it. Thanks.

**Comment by leo-arch** [comment]
Ok, this thing proved to be harder than I thought: a few hundred lines of code had to be changed and refactored.

Please give it a try and let me know: newly implemented code is almost always buggy code.

**Comment by muellerto** [comment]
Yes, works fabulous! Thanks a lot for this. I also checked `....` and similar with such symbolic links, it prognosticates the right path and jumps indeed exactly there, fine.

BTW: I also notice improvements in the viewer. Indeed the new viewer began to work fine on my Windows compilation. I see file contents and also subsequent directory trees now. So the application made really a big step forward in the last week.
