### ISSUE TITLE
file names with spaces, start an application using the MIME type

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#166]
**Describe the bug**
When the user tries to start a MIME type dependent application on a file having spaces (or other crap) in it's name it will not be successful on Windows.

**To Reproduce**
Some people like spaces in their file names. When you have such file names and you press [Enter] or `o` or `ow` starting the application will probably not be successful because the command line parameter (the file name) is wrong coded.

Windows applications like Winword.exe expect that a command line parameter having inner spaces is written as

    winword.exe "my wonderful file name with spaces.doc"

If the filename itself contains " it must be doubled:

    winword.exe "my wonderful file name with spaces and ""hello"".doc"

clifm does instead encode the spaces like

    winword.exe my%20wonderful%20file%20name%20with%20spaces.doc

This leads to a file not found error in the very most applications.

**Expected behavior**
Do not encode spaces on Windows, put file names into "...".

**Comment by leo-arch** [comment]
Hey @muellerto!

I've been looking at this issue, and these are my first impressions:

1. When running on _Cygwin_ **clifm** always assumes there's no GUI available, and thereby definitions in the mime file are on their head: `!X` (used to specify opening applications when not running on a graphical environment) need to be used when running on a GUI (which is always the case on _Cygwin_). This is easily fixable, but might require from the user to invert some of they mime definitions: `!X:` -> `X:` (which is the right thing). I'll let you know as soon as this change is commited. Note that this is not an issue if you do not use `X` at all, for example: `N:.*\.pdf$=APP;APP1`, and so on.
2. **Clifm** _does not encode spaces_. Indeed, this issue does not apply to **notepad**, but to **WINWORD**. Notepad can open files whose names contain spaces without any problem (and this proves that there's no spaces encoding), but **WINWORD** can't (it seems to be encoding spaces itself). Maybe this is a **WINWORD** issue, but I'm not sure. Even if it is, we still need to find a workaround.

**Comment by leo-arch** [comment]
**UPDATE**

Here's something even stranger: **EXCEL** _can_ open files with spaces (just as **notepad**), whereas both **WINWORD** and **POWERPNT** _can't_! Whatever the issue is, the guys at the Office department are not very consistent.

I'm using Office 2010 for testing, if that matters.

**Comment by leo-arch** [comment]
**UPDATE 2**

Both `FILE_WITH_SPACES winword` and `winword FILE_WITH_SPACES` work as intended. This can be used as a workaround for now.

You might want to write a short alias:

```sh
alias ww='winword'
alias pw='powerpnt'
```

**Comment by leo-arch** [comment]
**UPDATE 3**

These are the exact commands produced by **clifm** (Lira):

CMD1:
```
winword
/path/to/file with spaces.docx
```
CMD2:
```
excel
/path/to/file with spaces.xlsx
```

Save the command names, there's no difference at all between these commands, both composed the exact same way. And still, CMD1 refuses to work.

You can even try it at the command line (either **clifm**'s or any other shell's):

```
# This fails
winword "/path/to/file with spaces.docx"

# This works
excel "/path/to/file with spaces.xlsx"
```

**Comment by leo-arch** [comment]
**UPDATE 4**

The thing seems to be that `winword`, just as `powerpnt`, doesn't like absolute paths _when the file name contains spaces_ (though they do work when there are no spaces). This works:

```
winword
file with spaces.docx
```
It's pretty trivial to modify the code to use only file names, without the full path, when running on Cygwin. However, it's generally a bad idea to implement this kind of hacky solutions when you don't fully understand the cause of the problem: soon or later it will fail. At least, that's my experience.

So, the question still holds: why is `winword` unable to correctly open files containing spaces passed as absolute paths while `excel` can do it seamlessly?

**Comment by leo-arch** [comment]
Both fixes commited:

1. Properly recognize Cygwin's/Windows' graphical environment: `!X` in the mime config file (if it was used) must be replaced by `X`.
2. Correctly open files containing spaces when the opening application is MS-Word or MS-Powerpoint (among other possible programs misbehaving the same way).

**Comment by muellerto** [comment]
Hey, great improvements. I had to change some lines in my MIME config file. It didn't even open on F6. But now it does again.

I also can open a Word document with spaces now. At least in the ways I tested. Perhaps there are still cases where it doesn't work, don't know.

This issue is hard, I know. This comes because Microsoft lets the developer alone with that. They just said our NTFS can have files with spaces and the rest is on the developer's side. So the developer of an application must himself parse this stuff and it's not fully predictable what he gets in `argv[]`. And indeed Microsoft apps do not agree themselves in every detail.

Thanks a lot for having a look at this. Can't believe how diligent you work on all that (while I sleep ...)

**Comment by leo-arch** [comment]
You're welcome!

As to the Word/Powerpoint thing, this would be a BIG/UNACCEPTABLE bug in the Unix world (as terminal-based). But, in the Windows world, where the terminal is not even a thing, nobody cares.

Btw, I was thinking about providing a Cygwin/Windows specific mimelist file with sane default applications. The Office part is not a problem. But, what about default applications for PDF, images, videos, music, archives, and so on? What applications Windows provides by default for these file types?

**Comment by muellerto** [comment]
I'm not typical, I'm a Linux guy from the early days (Slackware 1992). I use a lot of FOSS applications also on Windows. My standard office is LibreOffice.

PDF: The most people will still use old Acrobat stuff (Acrobat Reader), another well known blown up is Foxit Reader. I use SumatraPDF which is rather light weight. 

Images: Most will use Photoshop or Paintshop Pro. I use Gimp and still even Paint (from Windows). Yes, it's primitive but some things you can do easily, for instance write some text into a picture, draw some connecting lines or arrows, this is something where Gimp is not good. Also Inkscape.

Video: never made or cut one.

Music: Microsoft had something, not sure anymore, never used that. I use foobar2000, VLC (both Windows ports). Cutting and converting I do on my Linux machine (ocenaudio).

Archives: 7z with it's own Gui file manager (7zFM). Also a lot of ordinary file managers (Multi Commander, Double Commander) have very good plugins for archiving anything, so you don't need something else. I use zip and unzip, tar, bzip, xz on the command line.

Editors: Many people will use Notepad++, also Sublime and in many many cases Microsoft Visual Studio Code. It's indeed good when you want to have debugger integration and and integrated terminal (Javascript, Typescript, Markdown, JSON, XML, ...). I have always a vim open, also Emacs or even Micro.

Mail: Claws Mail, eM Client, still Thunderbird, and of course Outlook, but I don't know anybody who still uses Windows Mail (aka Outlook Express), I use also Gnus on Emacs a lot because I do still a lot of usenet

A good source of inspiration (also for Linux software) is the [AlternativeTo](https://alternativeto.net/software/clifm/about/) website. Oh, there's clifm ... only one like.

**Comment by leo-arch** [comment]
Thanks for such a detailed list! This is nice place to start building the mimelist file. However, it will take some time and further investigation. For the time being, I need to focus on the next release.

> I'm a Linux guy from the early days (Slackware 1992)

Never doubted about you being an old-school Linux guy. I can hardly imagine a Windows user using **clifm**, nor any terminal program for that matter.  My first computer was a Commodore 64, and then moved on to a DOS machine, way before popular GUI's were a thing. I guess it was, at least partly, this old-school style what led me to write this program, with this particular approach/design. And I think this is why **clifm** is a niche program (and probably will always be), aimed basically at old-school people (or sysadmins and stuff like that).

**Comment by leo-arch** [comment]
So, can we close this issue?

**Comment by muellerto** [comment]
Yes, let's close this.
