### ISSUE TITLE
p on a symbolic link gives a stack dump

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#169]
**Describe the bug**
When `p` is used to show properties of a symbolic link it crashes. Doesn't matter if the symbolic link means a file or a directory.

**To Reproduce**
1. have a symbolic link among your files and directories
2. type `p` with the number of the symbolic link

**Expected behavior**
Should at last not crash.

**Desktop:**
 - OS: Windows 11
 - Terminal ConEmu
 - CliFM version 1.8.4-beta
 - Installation source: self compiled using MinGW

**Additional context**
Couldn't check if this happens also on Linux until now.

**Comment by leo-arch** [comment]
Reproduced. This should be an easy fix. I'll let you know.

Btw, have you taken a look at https://github.com/leo-arch/clifm/issues/160?

**Comment by leo-arch** [comment]
Yeap, it was a double free corruption. Should be fixed now.

Fortunately, this code is not released, so that the bug does not exist in 1.8.

**Comment by muellerto** [comment]
Works fine now.
