### ISSUE TITLE
unexpected abbreviation of file name

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#171]
**Describe the bug**
I have a directory named mastodonpp (10 characters). The short file view shows it correctly. The long file view abbreviates it when no other file is longer.

**To Reproduce**
MaxFilenameLen=60
MinFilenameTrim=60

**Expected behavior**
Should not abbreviate at all. Other files with longer file names are not abbreviated.

**Screenshots**
(For any damned reason I can't upload pictures. Not on Windows and not on Linux.)

The short file view looks like this, mastodonpp has its full name and even the number of files in it:
```
1 apps/8        2 board/2       3 clifm/18      4 haskell/3     5 librewolf/1
6 mastodonpp/24 7 pdrx/1        8 snapd/1        
--------------------------------------------------------------------------------------------
T1[2] 16:20 muellerto:seth ~/work/dev
<0> $ 
```
The long file view looks like this, and that's interesting:

```
1 apps       d/rwx/rwx/r-x 1000:100 2021-11-13 11:13:44 4096
2 board      d/rwx/rwx/r-x 1000:100 2010-10-27 15:57:06 4096
3 clifm      d/rwx/r-x/r-x 1000:100 2022-11-14 16:09:53 4096
4 haskell    d/rwx/r-x/r-x 1000:100 2021-10-24 17:31:42 4096
5 librewolf  d/rwx/r-x/r-x 1000:100 2022-11-05 12:12:22 4096
6 mastodon~  d/rwx/r-x/r-x 1000:100 2022-11-07 16:49:18 4096
7 pdrx       d/rwx/rwx/r-x 1000:100 2022-11-11 17:01:48 4096
8 snapd      d/rwx/r-x/r-x 1000:100 2021-01-01 17:50:31 4096
--------------------------------------------------------------------------------------------
-> Long view mode enabled
T1[2] 16:20 muellerto:seth ~/work/dev
<0> $ 
```

Interesting is also that other files in the same view would not be abbreviated:

 ```
1 abcdefghijklmnopqrstuvwxyz  d/rwx/r-x/r-x 1000:100 2022-11-14 16:24:34 4096
 2 apps                        d/rwx/rwx/r-x 1000:100 2021-11-13 11:13:44 4096
 3 board                       d/rwx/rwx/r-x 1000:100 2010-10-27 15:57:06 4096
 4 clifm                       d/rwx/r-x/r-x 1000:100 2022-11-14 16:09:53 4096
 5 haskell                     d/rwx/r-x/r-x 1000:100 2021-10-24 17:31:42 4096
 6 librewolf                   d/rwx/r-x/r-x 1000:100 2022-11-05 12:12:22 4096
 7 mastodonpp                  d/rwx/r-x/r-x 1000:100 2022-11-07 16:49:18 4096
 8 pdrx                        d/rwx/rwx/r-x 1000:100 2022-11-11 17:01:48 4096
 9 snapd                       d/rwx/r-x/r-x 1000:100 2021-01-01 17:50:31 4096
--------------------------------------------------------------------------------------------
T1[2] 16:24 muellerto:seth ~/work/dev
<0> $ 
```

So what's wrong with my mastodonpp? Why is it abbreviated in the middle picture? All simple characters, no spaces, no interpunction, no digraphs.

**Desktop:**
- OS: Arch Linux
- Terminal: urxvt
- CliFM version: 1.8.5-beta
- Installation source: Git master

**Comment by leo-arch** [comment]
Reproduced the directory tree, exactly as yours, and still cannot reproduce the issue. I seems arbitrary, but clearly it's not: something, and more properly, some value, is triggering the name trimming mechanism.

Could you please run in stealth mode (`clifm -S`)? In this mode, no config file is read and only default values are used. We do this in order to dismiss a wrong value in the config file. If the issue disappears, then you can try with a fresh config file: just rename the current one and it will recreated at the next run using the one found in the data directory.

Does this happen when using the same directory name in another directory or just in this particular directory tree?

Have you tried renaming the directory to something else and then back to `mastodonpp`?

**Comment by muellerto** [comment]
Good ideas, will check this this afternoon.

**Comment by muellerto** [comment]
It remains mysterious. I found out the following:
- it happens exactly as I described above also with the -S parameter
- it happens also in a second directory when I set it up like this one
- not only a longer, also a new created shorter file in the list triggers the algorithm so that it ends correctly, notice my `abc` in the first line, when I remove that I have again the `mastodon~`
```
 1 abc         d/rwx/r-x/r-x 1000:100 2022-11-16 15:52:06 4096
 2 apps        d/rwx/rwx/r-x 1000:100 2021-11-13 11:13:44 4096
 3 board       d/rwx/rwx/r-x 1000:100 2010-10-27 15:57:06 4096
 4 clifm       d/rwx/r-x/r-x 1000:100 2022-11-15 17:43:55 4096
 5 haskell     d/rwx/r-x/r-x 1000:100 2021-10-24 17:31:42 4096
 6 librewolf   d/rwx/r-x/r-x 1000:100 2022-11-05 12:12:22 4096
 7 mastodonpp  d/rwx/r-x/r-x 1000:100 2022-11-07 16:49:18 4096
 8 pdrx        d/rwx/rwx/r-x 1000:100 2022-11-11 17:01:48 4096
 9 snapd       d/rwx/r-x/r-x 1000:100 2021-01-01 17:50:31 4096
10 test        d/rwx/rwx/r-x 1000:100 2020-05-28 17:41:45 4096
--------------------------------------------------------------------------------------------------------
T1[1] 15:52 muellerto:seth ~/work/dev
<0> $ 
```
- it shows also all files correctly when I create a new entry with exactly the same length, `mastodoNpp`
```
 1 apps        d/rwx/rwx/r-x 1000:100 2021-11-13 11:13:44 4096
 2 board       d/rwx/rwx/r-x 1000:100 2010-10-27 15:57:06 4096
 3 clifm       d/rwx/r-x/r-x 1000:100 2022-11-15 17:43:55 4096
 4 haskell     d/rwx/r-x/r-x 1000:100 2021-10-24 17:31:42 4096
 5 librewolf   d/rwx/r-x/r-x 1000:100 2022-11-05 12:12:22 4096
 6 mastodoNpp  d/rwx/r-x/r-x 1000:100 2022-11-16 16:01:44 4096
 7 mastodonpp  d/rwx/r-x/r-x 1000:100 2022-11-07 16:49:18 4096
 8 pdrx        d/rwx/rwx/r-x 1000:100 2022-11-11 17:01:48 4096
 9 snapd       d/rwx/r-x/r-x 1000:100 2021-01-01 17:50:31 4096
10 test        d/rwx/rwx/r-x 1000:100 2020-05-28 17:41:45 4096
--------------------------------------------------------------------------------------------------------
T1[1] 16:01 muellerto:seth ~/work/dev
<0> $ 
```
- the name itself is not the trigger, I can rename it to `mastoDonpp` and it's still abbreviated:
```
1 apps       d/rwx/rwx/r-x 1000:100 2021-11-13 11:13:44 4096
2 board      d/rwx/rwx/r-x 1000:100 2010-10-27 15:57:06 4096
3 clifm      d/rwx/r-x/r-x 1000:100 2022-11-15 17:43:55 4096
4 haskell    d/rwx/r-x/r-x 1000:100 2021-10-24 17:31:42 4096
5 librewolf  d/rwx/r-x/r-x 1000:100 2022-11-05 12:12:22 4096
6 mastoDon~  d/rwx/r-x/r-x 1000:100 2022-11-07 16:49:18 4096
7 pdrx       d/rwx/rwx/r-x 1000:100 2022-11-11 17:01:48 4096
8 snapd      d/rwx/r-x/r-x 1000:100 2021-01-01 17:50:31 4096
9 test       d/rwx/rwx/r-x 1000:100 2020-05-28 17:41:45 4096
--------------------------------------------------------------------------------------------------------
T1[1] 16:04 muellerto:seth ~/work/dev
<0> $ 
```

My latest guess: Perhaps the number of rows plays a role, because of the indentation of the ELN on the left, a 10th row affects all other rows. When a 10th row appears the calculation is right.

**Comment by leo-arch** [comment]
I think your guess is right. This seems to be one of those edge cases only triggered when very specific conditions are met. Be it as it may, I still need to reproduced the thing.

Given this scenario, and all the information you provided, I think I need one last piece of info: terminal size, both X and Y (the value of COLUMNS might also be included).

**Comment by muellerto** [comment]
It happens just always. In my **urxvt**, in **xterm** but also on the **plain console** (without X11).

In the terminals I can change the window size as I want. LINES is for instance 75, COLUMNS 273. But when I open a second window my tiling window manager halves the size of the other one, so COLUMNS is then 134. Whatever I do, when I then let clifm redraw its files I have it always in the same way. Until now I haven't seen a dependency to any outer condition.

Damned, I forgot to check if I can also produce this on Windows.

**Comment by leo-arch** [comment]
Thanks for this new info. I'll keep trying to reproduce the bug.

**Comment by leo-arch** [comment]
@muellerto, please give it a try now.

EDIT: FYI, the issue was triggered whenever there were 9 files in the directory, neither 8 nor 10. At least in my test cases.

**Comment by muellerto** [comment]
Seems to be a success! The following picture is from Windows where it also happened this morning without your fix (I made just some directories):
```
1 a          d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:37 0
2 b          d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:39 0
3 c          d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:41 0
4 d          d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:13 0
5 e          d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:21 0
6 librewolf  d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:07 0
7 mastodon~  d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:48 0
8 snap       d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:29 0
9 x          d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:35 0
---------------------------------------------------------------
[1] 06:20 tm:DES-TM-003 /e/test/x
<0> $
```
And this is after your fix:
```
1 a           d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:37 0
2 b           d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:39 0
3 c           d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:41 0
4 d           d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:13 0
5 e           d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:21 0
6 librewolf   d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:07 0
7 mastodonpp  d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:19:48 0
8 snap        d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:29 0
9 x           d/rwx/r-x/r-x 1050202:1049089 2022-11-17 06:20:35 0
---------------------------------------------------------------
[1] 06:22 tm:DES-TM-003 /e/test/x
<0> $
```
I saw that the bug became visible when I had 8 lines and then created the 9th.

We can close this.
