### ISSUE TITLE
terminal exits immediately after "$TERMINAL -e clifm"

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#173]
I use "lxterminal -e clifm" as a keyboard shortcut. After some update I am  not sure which, this command started to behave differently ( similar to running "lxterminal -e ls", where terminal exits immediately after completing the command). Running clifm in already open terminal works fine.

**Comment by leo-arch** [comment]
Hi @Docbroke. Reproduced. I'll fix it as soon as I can.

**Comment by leo-arch** [comment]
Done. Give it a try now.

**Comment by Docbroke** [comment]
Solved.
