### ISSUE TITLE
problem with German umlauts

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#178]
**Describe the bug**
Both views, short and long, have a problem to display file names having German umlauts correctly.

**To Reproduce**
German umlauts `ä ö ü Ä Ö Ü` and some other special characters like `ß é à è É À È ç ø` are an integral part of european languages. Words change their meaning because of an umlaut - in German "Bar" means "bar" (for drinking) but "Bär" means "bear" (the animal). So the people put umlauts into their file names a lot and trust on them.

clifm struggles about this. For example I have a directory containing the following file and sub directory names:

> 1 B**ü**ttenberg
> 2 Court
> 3 Gesigen
> 4 Graitery
> 5 Leimern
> 6 Leissigen
> 7 L**ä**ngholz
> 8 L**ü**tschine
> 9 Malleray
>10 Moutier
>11 Neufeld
>12 Pieterlen
>13 Raimeux
>14 Rugen
>15 R**ü**dtligen-Alchenfl**ü**h
>16 Simmenfluh
>17 Soliwald
>18 Sous-le-Mont
>19 Spiezwiler
>20 StadttangenteBern
>21 Wankdorf
>22 CleanUp.cmd
>23 CreateDatabaseExternals.cmd
>24 DeleteAllServers.cmd
>25 db_ext.txt
>26 ExportSprach**ü**bersetzungTable.cmd
>27 ImportSprach**ü**bersetzungTable.cmd
>28 RestoreAllServers.cmd
>29 ShowIIPVersions.cmd
>30 scr_ext.txt
>31 UpgradeDatabaseDirectory.cmd

clifm shows this as follows:
```
 1 B                              d/rwx/r-x/r-x 1050202:1049089 2022-03-03 06:35:51 2048
 2 Court                         d/rwx/r-x/r-x 1050202:1049089 2022-01-03 06:20:46 2048
 3 Gesigen                       d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:47:03 2048
 4 Graitery                      d/rwx/r-x/r-x 1050202:1049089 2021-12-01 08:30:09 2048
 5 Leimern                       d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:56:21 2048
 6 Leissigen                     d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:47:53 2048
 7 Leissigen                              d/rwx/r-x/r-x 1050202:1049089 2022-09-16 06:36:06 2048
 8 Leissigen                              d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:53:54 2048
 9 Malleray                      d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:53:01 2048
10 Moutier                       d/rwx/r-x/r-x 1050202:1049089 2021-12-01 08:30:10 2048
11 Neufeld                       d/rwx/r-x/r-x 1050202:1049089 2021-12-21 07:14:50 2048
12 Pieterlen                     d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:49:42 2048
13 Raimeux                       d/rwx/r-x/r-x 1050202:1049089 2021-12-01 08:30:16 2048
14 Rugen                         d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:55:51 2048
15 Rugen                              d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:50:39 2048
16 Simmenfluh                    d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:53:31 2048
17 Soliwald                      d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:57:46 2048
18 Sous-le-Mont                  d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:52:06 2048
19 Spiezwiler                    d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:56:49 2048
20 StadttangenteBern             d/rwx/r-x/r-x 1050202:1049089 2022-08-18 15:06:18 2048
21 Wankdorf                      d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:54:56 2048
22 CleanUp.cmd                   ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
23 CreateDatabaseExternals.cmd   ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
24 DeleteAllServers.cmd          ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
25 db_ext.txt                    ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
26 ExportSprachvers.cmd                              ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
27 ImportSprachvers.cmd                              ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
28 RestoreAllServers.cmd         ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
29 ShowIIPVersions.cmd           ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
30 scr_ext.txt                   ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
31 UpgradeDatabaseDirectory.cmd  ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
---------------------------------------------------------------------------------------------------------------
[1] 07:30 tm:DES-TM-003 /e/work/Project/Infra3_Server/Standorte
<0> $
```

Remarks
- 1 is cut completely on letter ü
- 6, 7 and 8 are displayed having the same name, also 14 and 15 because of 7, 8 and 15 have umlauts, the same name comes because letters from previous entry 6 are used
- 26 and 27 get wrong names on umlauts, letters from previous entry 24 are used
- when an umlaut occures in a file name the display of the additional informations is shifted right by a variing amount of characters, this happens also in the short view, the amount seems to be the length of the remaining (wrong) file name, 15 is shifted by 5 characters because the remaining file name has a length of 5

**Expected behavior**
Every umlaut should be shown as one single character as every other letter.

**Desktop (please complete the following information):**
- OS: Windows 10 Pro, 11 Pro, Windows Server 2022
- Terminal: ConEmu, DOS prompt
- CliFM version: all up to now
- Installation source: Git

**Additional context**
Don't be discouraged by this. This is a long term issue for sure - for the Christmas holidays :)) Solving this is probably not easy. I'm not even sure what coding is used on NTFS and Microsoft makes it (also in documentation) not easy for the developer.

Indeed also other programs have problems here, my MinGW implementation of **ls** shows the following which is probably correct but not nice at all:
```
$ ls -l
total 106
drwxr-xr-x 1 tm Domain Users    0 Mar  3  2022 'B'$'\303\274''ttenberg'
-rw-r--r-- 1 tm Domain Users  515 Nov 30  2021  CleanUp.cmd
drwxr-xr-x 1 tm Domain Users    0 Jan  3  2022  Court
-rw-r--r-- 1 tm Domain Users  940 Nov 30  2021  CreateDatabaseExternals.cmd
-rw-r--r-- 1 tm Domain Users  551 Nov 30  2021  DeleteAllServers.cmd
-rw-r--r-- 1 tm Domain Users  643 Nov 30  2021 'ExportSprach'$'\303\274''bersetztungTable.cmd'
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Gesigen
drwxr-xr-x 1 tm Domain Users    0 Dec  1  2021  Graitery
-rw-r--r-- 1 tm Domain Users 2130 Nov 30  2021 'ImportSprach'$'\303\274''bersetztungTable.cmd'
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Leimern
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Leissigen
drwxr-xr-x 1 tm Domain Users    0 Sep 16 06:36 'L'$'\303\244''ngholz'
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021 'L'$'\303\274''tschine'
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Malleray
drwxr-xr-x 1 tm Domain Users    0 Dec  1  2021  Moutier
drwxr-xr-x 1 tm Domain Users    0 Dec 21  2021  Neufeld
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Pieterlen
drwxr-xr-x 1 tm Domain Users    0 Dec  1  2021  Raimeux
-rw-r--r-- 1 tm Domain Users  553 Nov 30  2021  RestoreAllServers.cmd
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Rugen
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021 'R'$'\303\274''dtligen-Alchenfl'$'\303\274''h'
-rw-r--r-- 1 tm Domain Users  226 Nov 30  2021  ShowIIPVersions.cmd
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Simmenfluh
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Soliwald
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Sous-le-Mont
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Spiezwiler
drwxr-xr-x 1 tm Domain Users    0 Aug 18 15:06  StadttangenteBern
-rw-r--r-- 1 tm Domain Users  732 Nov 30  2021  UpgradeDatabaseDirectory.cmd
drwxr-xr-x 1 tm Domain Users    0 Nov 30  2021  Wankdorf
-rw-r--r-- 1 tm Domain Users  974 Nov 30  2021  db_ext.txt
-rw-r--r-- 1 tm Domain Users  292 Nov 30  2021  scr_ext.txt
```

Fact is that my terminal is able to show the characters correctly, the DOS **dir** command displays them all (note: same terminal, same font):
```
$ dir
 Datenträger in Laufwerk E: ist HDD
 Volumeseriennummer: 48B8-B689

 Verzeichnis von E:\work\Project\Infra3_Server\Standorte

02.08.2022  12.31    <DIR>          .
30.11.2021  14.34    <DIR>          ..
03.03.2022  06.35    <DIR>          Büttenberg
30.11.2021  14.46               515 CleanUp.cmd
03.01.2022  06.20    <DIR>          Court
30.11.2021  14.46               940 CreateDatabaseExternals.cmd
30.11.2021  14.46               974 db_ext.txt
30.11.2021  14.46               551 DeleteAllServers.cmd
30.11.2021  14.46               643 ExportSprachübersetztungTable.cmd
30.11.2021  14.47    <DIR>          Gesigen
01.12.2021  08.30    <DIR>          Graitery
30.11.2021  14.46             2’130 ImportSprachübersetztungTable.cmd
30.11.2021  14.56    <DIR>          Leimern
30.11.2021  14.47    <DIR>          Leissigen
16.09.2022  05.36    <DIR>          Längholz
30.11.2021  14.53    <DIR>          Lütschine
30.11.2021  14.53    <DIR>          Malleray
01.12.2021  08.30    <DIR>          Moutier
21.12.2021  07.14    <DIR>          Neufeld
30.11.2021  14.49    <DIR>          Pieterlen
01.12.2021  08.30    <DIR>          Raimeux
30.11.2021  14.46               553 RestoreAllServers.cmd
30.11.2021  14.55    <DIR>          Rugen
30.11.2021  14.50    <DIR>          Rüdtligen-Alchenflüh
30.11.2021  14.46               292 scr_ext.txt
30.11.2021  14.46               226 ShowIIPVersions.cmd
30.11.2021  14.53    <DIR>          Simmenfluh
30.11.2021  14.57    <DIR>          Soliwald
30.11.2021  14.52    <DIR>          Sous-le-Mont
30.11.2021  14.56    <DIR>          Spiezwiler
18.08.2022  14.06    <DIR>          StadttangenteBern
30.11.2021  14.46               732 UpgradeDatabaseDirectory.cmd
30.11.2021  14.54    <DIR>          Wankdorf
              10 Datei(en),          7’556 Bytes
              23 Verzeichnis(se), 654’579’851’264 Bytes frei
```

I guess getting such file names is even a problem when you don't have such characters on your keyboard. I could provide a ZIP file containing such a directory structure.

**Comment by leo-arch** [comment]
Hi @muellerto. I've already spotted an Unicode issue when it comes to suggestions on Windows: they just don't work when Unicode characters are involved. So, this is not unexpected at all. It seems that people at MS decided to use their own Unicode library, disregarding what works perfectly fine on most operating systems.

Just to be sure. This issue is Windows-only, isn't it?

Btw, I can generate Unicode file names without any issue. Indeed, I have several directories populated with such file names (including cyrillic, CJK, latin, german, arabic, and a few more) because I have thoroughly tested Unicode support on *nix.

**Comment by muellerto** [comment]
I never had that on Linux until now, but I also have much less umlauts in file names on Linux.

Made an experiment now. When I have a file named öö.öö and I make then a very short C program like
```
#include <stdio.h>
int main ()
{
        FILE* f = fopen("öö.öö", "r");
        if (f)
                fclose(f);
        return 0;
}
```

it does indeed find and open my test file correctly.

My guess is: today most none Unicode libraries will accept or provide UTF8 character strings.

On Windows it seems that the behavior can be switched on or off, they have API functions for that:
https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileapistooem

**Comment by leo-arch** [comment]
The problem pops up when you need to handle Unicode strings (say, comparing two strings, determining whether a given character is upper or lower case, and so on). For example, if you want to get the amount of characters in a string, **strlen**(3) is enough when it comes to ASCII strings (because here 1 byte == 1 char and `strlen` counts bytes). But, since Unicode characters are multi-byte characters, `strlen` will just not work: `Übermensch`, for example, has 10 chars, but `strlen` returns 11, because `Ü` takes 2 bytes. In this case, we need a Unicode specific function (**clifm** uses a built-in Unicode aware `strlen` (`wc_xstrlen`) built upon the standard Unicode encoding).

Briefly put, you need specific functions to handle Unicode, and what works for *nix is not working for Windows.

I will try to go around this issue, for sure, but currently I'm not entirely sure how to do it: several tests and some research are required.

**Comment by muellerto** [comment]
> Übermensch, for example, has 10 chars, but strlen returns 11, because Ü takes 2 bytes.

Of course, that's clear. It may even be up to 4 bytes per character. But there should be libraries for that, especially there's [GNU libunistring](http://www.gnu.org/software/libunistring/manual/libunistring.html) and [PCRE](http://www.pcre.org/). Very interesting is [this project here](https://github.com/sheredom/utf8.h) because it's small and very handy.

> and what works for *nix is not working for Windows.

It should since there's no special Windows UTF8.

**Comment by leo-arch** [comment]
What is clear is that what works without any hassle on *nix is not working on Windows. I need to identify the source of the issue and either write an alternative routine or rewrite the existing one to make it cross-platform. 

EDIT: [This project](https://github.com/sheredom/utf8.h) looks pretty cool. Thanks for pointing it out.

**Comment by leo-arch** [comment]
### First test: sheredom UTF8 library

#### *nix

```sh
utf8len "üaüa"
4
```

### Windows (both Cygwin and MinGW64)

```sh
utf8len.exe "üaüa"
6
```

This one fails on Windows too. There's something else going on.

**Comment by leo-arch** [comment]
Hey @muellerto, please give it a shot now.

**Comment by muellerto** [comment]
Look yourself:

```
 1 Büttenberg                         d/rwx/r-x/r-x 1050202:1049089 2022-03-03 06:35:51 2048
 2 Court                              d/rwx/r-x/r-x 1050202:1049089 2022-01-03 06:20:46 2048
 3 Gesigen                            d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:47:03 2048
 4 Graitery                           d/rwx/r-x/r-x 1050202:1049089 2021-12-01 08:30:09 2048
 5 Leimern                            d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:56:21 2048
 6 Leissigen                          d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:47:53 2048
 7 Längholz                           d/rwx/r-x/r-x 1050202:1049089 2022-09-16 06:36:06 2048
 8 Lütschine                          d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:53:54 2048
 9 Malleray                           d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:53:01 2048
10 Moutier                            d/rwx/r-x/r-x 1050202:1049089 2021-12-01 08:30:10 2048
11 Neufeld                            d/rwx/r-x/r-x 1050202:1049089 2021-12-21 07:14:50 2048
12 Pieterlen                          d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:49:42 2048
13 Raimeux                            d/rwx/r-x/r-x 1050202:1049089 2021-12-01 08:30:16 2048
14 Rugen                              d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:55:51 2048
15 Rüdtligen-Alchenflüh               d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:50:39 2048
16 Simmenfluh                         d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:53:31 2048
17 Soliwald                           d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:57:46 2048
18 Sous-le-Mont                       d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:52:06 2048
19 Spiezwiler                         d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:56:49 2048
20 StadttangenteBern                  d/rwx/r-x/r-x 1050202:1049089 2022-08-18 15:06:18 2048
21 Wankdorf                           d/rwx/r-x/r-x 1050202:1049089 2021-11-30 14:54:56 2048
22 CleanUp.cmd                        ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
23 CreateDatabaseExternals.cmd        ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
24 DeleteAllServers.cmd               ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
25 db_ext.txt                         ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
26 ExportSprachübersetztungTable.cmd  ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
27 ImportSprachübersetztungTable.cmd  ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
28 RestoreAllServers.cmd              ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
29 ShowIIPVersions.cmd                ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
30 scr_ext.txt                        ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34  512
31 UpgradeDatabaseDirectory.cmd       ./rw-/r--/r-- 1050202:1049089 2021-11-30 14:46:34 2048
-----------------------------------------------------------------------------------------------------------
[1] 06:26 tm:DES-TM-003 /e/work/Project/Infra3_Server/Standorte
<0> $
```

:))     <-- me

Hey, thanks for your exemplary support!

**Comment by leo-arch** [comment]
Thank you for your awesome feedback!

**Comment by leo-arch** [comment]
Hi @muellerto. I discovered that this issue was not really a **clifm** bug, but rather a locale issue. The thing is that by default the CYGWIN environment does not set an UTF-8 locale, generating thus encoding issues (and not only for **clifm**).

To avoid this problem I was forcefully setting an UTF-8 locale (more precisely `C.UTF-8`): but this was just a dirty workaround. Overriding the user environment is clearly not the best approach. The new, much more appropriate procedure is to warn the user whenever a non-UTF-8 locale is detected.

To avoid encoding issues you only need to set a proper UTF-8 locale. Example:

```sh
export LANG=de_DE.UTF-8
```
That's it. Now everything, including `ls(1)` output, should work as expected.

Btw, the problem is not Windows-only. If you run **clifm** as follows you'll get the same issues on Linux:

```sh
LANG=de_DE clifm
```

For more information you can take a look at the [**utf-8** manpage](https://man.archlinux.org/man/utf-8.7).

**Comment by muellerto** [comment]
On my Linux machine `LANG` is `de_DE.UTF-8`.

On Windows I'm rather sure I don't have a `LANG` environment variable since Windows has no `locale` file or `locale.gen` script. Yes, I could make one for the MinGW programs, this could indeed have an impact on `ls` and others. Good idea. I will check this tomorrow.

BTW: runs good now!

**Comment by muellerto** [comment]
Made this on Windows. This affects indeed MinGW programs. `ls` shows proper umlauts now. Good!
