### ISSUE TITLE
Alt+- doesn't work

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#179]
**Describe the bug**
`Alt+-` should start the viewer - as the doc says. But it leads into a question and does nothing.

**To Reproduce**
Start in a normal state:
```
[1] 06:48 tm:DES-TM-003 /e/work/Dev
<0> $
```

Press `Alt+-`. This leads (as I understand it) into a question:
```
[1] 06:50 tm:DES-TM-003 /e/work/Dev
(arg: -1)
```

What now? When I press Enter it just closes the question and does nothing.

If I press a valid number the question takes the number somehow as argument but remains open:
```
[1] 06:52 tm:DES-TM-003 /e/work/Dev
(arg: -123)
```

If I give him a letter the question ends immediately.

Note: the `view` command works fine now, also on my Windows machine. Should `Alt+-` do the same as the `view` command? Or is there a difference?

**Expected behavior**
Should open the viewer?

**Desktop:**
- OS: Windows 11
- Terminal: ConEmu, DOS prompt
- CliFM version: fresh 1.9
- Installation source: Git

**Comment by leo-arch** [comment]
I'm pretty sure the issue is that there's no such keybinding in your keybindings file (this is a new setting and you might be using an older config file). Try this:

```sh
kb edit (or F9)
```
and then add this line:

```sh
launch-view:\M--
```
Restart, and it should be working now.

**Comment by muellerto** [comment]
Ah! Thanks a lot.
