### ISSUE TITLE
recursive file search ignores symbolic links

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#180]
**Describe the bug**
When I am in a parent directory which contains symbolic links to other directories and I cause a deep recursive file search using `/ ... -x` the symbolic links are ignored.

**To Reproduce**
I have a directory containing all my subversion working copies of different branches. Some of them (1...5, 16...18) are indeed real physical directories but others (6...15) are physically on a SSD, so I made only symbolic links here:
```
 1 3rdParty        d/rwx/r-x/r-x 1050202:1049089 2022-03-02 14:24:12 2048         
 2 10_X            d/rwx/r-x/r-x 1050202:1049089 2021-12-01 07:39:23 2048         
 3 12_X            d/rwx/r-x/r-x 1050202:1049089 2022-01-12 15:49:18 2048         
 4 15_X            d/rwx/r-x/r-x 1050202:1049089 2022-12-13 09:22:52 2048         
 5 17_X            d/rwx/r-x/r-x 1050202:1049089 2022-12-01 08:10:38    0         
 6 18_4_X          l/rwx/rwx/rwx 1050202:1049089 2022-03-16 14:33:43    0         
 7 18_5_X          l/rwx/rwx/rwx 1050202:1049089 2022-03-16 14:34:03    0         
 8 18_X            l/rwx/rwx/rwx 1050202:1049089 2022-03-16 14:34:18    0         
 9 18_X_BLE        l/rwx/rwx/rwx 1050202:1049089 2022-10-20 10:57:13    0         
10 19_X            l/rwx/rwx/rwx 1050202:1049089 2022-08-11 10:46:39    0         
11 20_X            l/rwx/rwx/rwx 1050202:1049089 2022-03-29 09:25:47    0         
12 21_X            l/rwx/rwx/rwx 1050202:1049089 2022-08-03 08:18:56    0         
13 22_X            l/rwx/rwx/rwx 1050202:1049089 2022-11-10 15:18:31    0         
14 __Backup        l/rwx/rwx/rwx 1050202:1049089 2021-12-09 09:14:30    0         
15 __DATA          l/rwx/rwx/rwx 1050202:1049089 2021-12-09 09:14:45    0         
16 __test_configs  d/rwx/r-x/r-x 1050202:1049089 2022-12-13 13:30:28 4096         
17 Trunk           d/rwx/r-x/r-x 1050202:1049089 2022-01-13 11:54:33    0         
18 __              d/rwx/r-x/r-x 1050202:1049089 2022-11-09 11:49:51 2048         
19 UpdateAll.cmd   ./rw-/r--/r-- 1050202:1049089 2022-09-19 06:41:31  512         
----------------------------------------------------------------------------------
[1] 07:21 tm:DES-TM-003 /e/work/Dev                                               
<0> $                                                                             
```

When I start a recursive file search from here only the real directories are affected. The symbolic links are ignored completely.

**Expected behavior**
Would be good if symbolic links meaning physical directories could also be affected. When you iterate over the entries of the current directory you could ask if the entry is a symbolic link and then if it means a directory. Note: symbolic links can also happen deeper in the tree. So you must do the same checks everywhere.

**Desktop**
- OS: Windows 11
- Terminal: ConEmu, DOS prompt
- CliFM version: fresh 1.9
- Installation source: Git

**Comment by leo-arch** [comment]
Thanks for reporting @muellerto! I'll take a look at it.

**Comment by leo-arch** [comment]
Give it a try now.

**Comment by muellerto** [comment]
Yes, yes, yes!

I couldn't check if it also works in the deep because I haven't further symbolic links there but it works fine now in the start directory. Great!
