### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [leo-arch/CliFM#181]
Would you like to add more error handling for return values from functions like the following?
* [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [log_function](https://github.com/leo-arch/clifm/blob/8f728e778e239334cadc1cd0691815ac175c3b62/src/history.c#L164)
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [set_term_title](https://github.com/leo-arch/clifm/blob/25335bbde43c93c862ee038c41eb38de66b72e2c/src/misc.c#L420)

**Comment by leo-arch** [comment]
Hi @elfring. Are you saying we should add error handling for **fclose**(3) and **printf**(3) calls in `log_function` and `set_term_tittle` functions respectively? Is that what you mean?

**Comment by elfring** [comment]
Yes (for example).

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by sodface** [comment]
@leo-arch I think elfring is a bot. Here's an issue today from another project I follow:

https://github.com/tio/tio/issues/182

**Comment by leo-arch** [comment]
Hi @sodface. Yes, maybe you're right. But, just in case...

**Comment by leo-arch** [comment]
@elfring, thanks for your suggestion, but no. Checking the return value of these functions, specially in the case of **printf**(3), doesn't make much sense (and, in any case, it's not necessary in the context of the functions you pointed out).

**Comment by elfring** [comment]
>… is a bot. …

You can take additional information sources better into account, can't you?

:thought_balloon: Do you care for [advices according to more secure programming](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions")?

**Comment by leo-arch** [comment]
Are you really suggesting to clutter the source code checking the return value of each call to printf? Thanks, but again, no.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested in [aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by leo-arch** [comment]
Thanks for the information.
