### ISSUE TITLE
let p also display folder sizes

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#184]
**Is your feature request related to a problem? Please describe.**
I would find it a good idea to get a size information about a directory (or symlinked directory) before I start a copy or move operation with the contents of that directory.

**Describe the solution you'd like**
When I press `p` on a directory (or symlinked directory) please sum up all file sizes in the directory recursively and show the result in a new line below the other data. For a single file this is already the case but for a directory it would be even more interesting.

I often copy audio files, such a directory has then about 100MB. In this case it would be good to know if there's enough space on the destination side, especially when I move it because a move operation fails normally with some files here and some files there which is always annoying.

If you don't want to have this on `p` by default make an option so that the user can decide if he wants this. Or make a new `P` command.

**Describe alternatives you've considered**
I know there is the disk usage analyzer mode on ALT-Tab, but this shows the sizes for all directories and takes a long time in some cases. Getting the folder size of a specific folder would be much faster.

An interesting thing would also be a size check before the `c` or `m` commands are executed. (Yes, can still fail later ...)

**Comment by leo-arch** [comment]
Hi @muellerto, That's exactly what the [`pp` command](https://github.com/leo-arch/clifm/wiki/Introduction#p-pr-prop-elnfile-) does: it's just like `p`, but includes full directories size.

**Comment by muellerto** [comment]
Coool, some solutions are so easy. Probably I will use `pp` now generally.

I did read the doc. But the `pp` command is mentioned only in the text. It wasn't able to find the way into my mind.

**Comment by leo-arch** [comment]
In this case, an [alias](https://github.com/leo-arch/clifm/wiki/Customization#aliases) might be handy:

```sh
alias p="pp"
```
