### ISSUE TITLE
Doesn't build anymore on Windows

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#189]
**Describe the bug**
The latest Git sources do not build anymore on Windows.

**To Reproduce**
I always used `make -f misc/cygwin/Makefile`. Yesterday it did still work. Today it shows a lot of linker errors:

```
undefined reference to 'libintl_gettext'
more undefined references to 'libintl_gettext'
undefined reference to 'readline'
undefined reference to 'tilde_expand'
undefined reference to 'rl_activate_mark'
undefined reference to 'rl_redisplay'
undefined reference to 'rl_deactivate_mark'
undefined reference to 'rl_mark'
(... many more ...)
```

I didn't change anything in my installed libs or the compiler. (Compiler is gcc 11.3.0) Something must have changed in linking.

**Expected behavior**
Should build :)

**Desktop (please complete the following information):**
- OS: Windows 11 Pro
- Terminal: ConEmu, Windows DOS Box
- CliFM version: 1.10.1
- Installation source: Git from Feb 08 2023

**Comment by leo-arch** [comment]
Hi @muellerto. I'll take a look at it.

**Comment by leo-arch** [comment]
Builds fine for me on both `Cygwin` and `MINGW` (`ConEmu` 220807). At least we know the issue is not related to the source code: a linking warning indeed is just a problem regarding external libraries, in this case, `readline`.

I'll try updating `ConEmu` to version 221218.

EDIT: No, still compiling and linking fine. Try reinstalling `libreadline-devel` (and just in case `libreadline`) from the `msys` repo (current version for both is 8.1.002-2).

**Comment by leo-arch** [comment]
UPDATE: Upgraded my system (`pacman -Syu`), recompiled, and still no issue.

**Comment by muellerto** [comment]
Doesn't understand that. Now it builds. I didn't change anything, not a single file or environment stuff. The only thing I did was to stop sh (which is the bash from MinGW in my case) and restart it. And then I made a `make -f misc/cygwin/Makefile clean`. OK, I close this, sorry for the furor!

(Works still good! Use it everyday.)

**Comment by leo-arch** [comment]
Hi @muellerto. I've implemented gradient colors for date and size fields in long view mode.

### How to use this new feature
1. Recompile and reinstall.
2. Remove the old default color scheme (`~/.config/clifm/colors/default.clifm`). Or maybe you prefer to rename it (just in case).
3. Restart (a new `default.clifm` file will be created automatically).

**Note**: Works better with 256 colors.

Please let me know what you think.

**Comment by muellerto** [comment]
Good morning, Leo.

> Hi @muellerto. I've implemented gradient colors for date and size
> fields in long view mode.
> 
> Please let me know what you think.

I'm not sure what you want to achieve. Experiments on my Windows
machine do not show any real difference, see my attachment.

The window in the background shows a clifm which has been started
without having a default.clifm, the foreground clifm has this file.
Both instances don't have a ColorScheme line at all in the config, so I
think they should both try to use default colors.

Looks quite the same. The background window is generally a tiny bit
darker because it is not the active one, the foreground window is
active. So I'm not really sure if your changes became active in my test.

On Windows I don't have many options to change the color depth or so
(it's idiotic, you can't even change anymore the most simple things on
Windows 11).

I'll check if I see more on my Linux machine this afternoon.

T.M.

**Comment by muellerto** [comment]
Am Sun, 19 Feb 2023 20:53:13 -0800
schrieb leo-arch ***@***.***>:

> Hi @muellerto. I've implemented gradient colors for date and size
> fields in long view mode.
> 
> Please let me know what you think.

Ha, now I have it!!

The problem was: I had a local copy of the default.clifm, which was of
course active. I removed this now, this was for nothing.

And now I see indeed different colors, also on my Windows machine. What
I'm not really sure about is what the colors should mean.

Is it the age? Files from today are white, files from this year (or
so) are green, older files are cyan? Currently I see only three
different colors. - This could indeed be a useful instrument.

Optically I would prefer the same color just in different brightness
(the older the darker, just 5 steps) - so younger files would be an eye
catcher. But it's clear: the number of colors is probably always
limited.

You could even add two commands which allow the user to go in history
and come back. This could be used in a directory where all files have
the same color. The user could then control which date is handled as
"today" for this display and let the youngest files come out of the
darkness.

T.M.

**Comment by leo-arch** [comment]
Hey @muellerto. It seems to be a `ConEmu` color-support issue: in my tests, it doesn't really handle anything beyond 8 basic colors (plus attributes), at least not out of the box (despite the fact that it sets **TERM** to `xterm-256color`).

Just try this:

```sh
#!/bin/sh

for i in {0..255}; do
    echo -e "\x1b[0;38;5;${i}mCOLOR-${i}\x1b[0m"
done

exit 0
```
This simple snippet should print all the 256 colors, but it doesn't on `ConEmu`. Maybe 256-color support should be enabled or something (there seems to be something [here](https://conemu.github.io/en/AnsiEscapeCodes.html)).

BTW, the CygWin terminal works as intended.

**Comment by muellerto** [comment]
leo-arch ***@***.***> schrieb:

> Hey @muellerto. It seems to be a ConEmu color-support issue: in my
> tests, it doesn't really handle anything beyond 8 basic colors (plus
> attributes), at least not out of the box.

Ah, indeed, the black DOS terminal shows better shaded colors in the
timestamps and also different colors in the size column.

This is really an interesting feature. And it's an original, nowhere
seen before.

T.M.

**Comment by leo-arch** [comment]
Thanks! Interesting indeed (useful actually), but not original. I borrowed the idea from a few modern **ls**(1) implementations, like [`lsd`](https://github.com/Peltoche/lsd), [`lr`](https://github.com/leahneukirchen/lr), and a few others.

Btw, if you prefer going back to the old "flat" style, just replace the new `default.clifm` file by the old one.

**Comment by leo-arch** [comment]
Switched to a B&W 3-steps gradient for dates. My conclusion is that, at least in my eyes, more steps just make the thing confusing (besides, the cyan 4-step gradient was not working fine on Alacritty, which is a widely used terminal).

These three steps are:

1. One day or less
2. One year or less
3. Older

**Comment by muellerto** [comment]
leo-arch ***@***.***> schrieb:

> Switched to a B&W three-steps gradient for dates. My conclusion is
> that, at least in my eyes, more steps just make the thing confusing.
>
> These three steps are:
>
> 1 One day or less
> 2 One year or less
> 3 Older

I would let the number of steps open. My definition would be somehow
logarithmic (fine at the beginning, rough at the end):

1 One day or less (perhaps even 12h or less)
2 Two days or less
3 A week or less
4 A month or less
5 Older

If you watch yourself you will see you work many times with always the
same files. These are the files you are interested in. It probably
doesn't matter anymore if a file is 8 months old or 13 months, you don't
need to distiguish that. But it is often interesting if a file has
already been changed today or if it's still the one from last week.

I think the key is having not too much real colors. If you have all
steps based on the same color (just darkened differently) you can have
even more than 3 steps. But you can't oversee what you have, especially
you can't order the colors in your head, when you have different colors
to expess each step.

A special case is grey: grey is not a color. That's why you could have
the last step (the oldest files) always in a dark grey regardless of
with what color you started in the first step.

You could make it customizable. You could have a section in the config
file like this:

TimestampsAndColors
Step1<24        #B0B0B0
Step2<48        #A0A0A0
Step3<168       #808080
Step4<720       #606060
Step5           #404040

The numbers starting with 24 are hours, could also be days. If the user
wants 10 steps he can define 10. Important is that the last one has no <.

If you want to make it dependent on the one color defined in the color
scheme you could accept percents here instead of color values, starting
from 100% going down to 40% or so.

Just thinking aloud. You will surely find a good solution :)

T.M.

**Comment by leo-arch** [comment]
> If you watch yourself you will see you work many times with always the
same files. These are the files you are interested in. It probably
doesn't matter anymore if a file is 8 months old or 13 months, you don't
need to distiguish that. But it is often interesting if a file has
already been changed today or if it's still the one from last week.

Agreed. Good point.

I'll try implementing the 5-step gradient as described by you (it just makes sense) in black and white: given only 256 colors (assuming true colors is not quite portable) there are not much choices when it comes to monochromatic gradients. You have to carefully pick each grade (and most of the times you lost the desired monochromatic balance, or end up picking too similar colors). This is not the case with black and white: the 256 colors palette offers a nice series of tones to choose from (231-255). However, even using a B&W gradient, it is hard to choose 5 enough distinguishable grades.

As to customization, it's desirable indeed, but not a priority. Let's write good code first.

EDIT: Percentages and hex are ideal, for sure, but they work provided you terminal supports true colors, which is too much to ask when portability matters. Indeed, before implementing this feature, I have always written stuff having only 8 colors in mind (gradients in fact prefer 256 colors, but will fallback to 8 if no support is detected).

**Comment by leo-arch** [comment]
B&W 5-steps gradient implemented:

#### 256 colors (from white to dark gray)
| Age | Color |
| --- | --- |
| 1 hour or less | 231 |
| 1 day or less | 253 |
| 1 week or less | 250 |
| 1 month or less | 247 |
| older | 244 |

#### 8 colors
| Age | Color |
| --- | --- |
| 1 hour or less | bold cyan |
| 1 day or less | cyan |
| older | dimmed cyan |

**Comment by leo-arch** [comment]
Well, color gradients are now customizable via `DateShades` and `SizeShades` options in the [color scheme file](https://github.com/leo-arch/clifm/blob/master/misc/colors/default.clifm).

**Comment by muellerto** [comment]
Tried some color settings yesterday. But it was not that easy.

First it depends a lot on ConEmu's own color scheme which interprets colors of the running application on it's own way. Especially it seems that very fine color differences are bulldozed into no differences. In the result I always see less colors than expected.

So I tried also (just for the experiment) clifm in the default black DOS box from Windows 11. This shows at least all the colors I configured and doesn't interpret them itself.

In the end it remains hard to configure usable colors. The most success I had with 256 colors, I could see what I configured. But it's not easy with these 256 colors because every change in a number gives indeed another color. I would much more like to change the brightness of a color (I mean _the same_ color). The `-` sign with a number didn't show much effect.

I guess in a Linux terminal it looks much better. Will check this this afternoon.

**Comment by muellerto** [comment]
I did experiment with terminals and colors in the last days. It seems that the most problems with unexpected colors have indeed their reason in ConEmu and it's specific interpretation of colors an application uses. These ConEmu color schemes are always merged on top so that the application looks totally different. (I made a case for them now.)

Meanwhile I found that there are also other terminals for Windows around. I use [Tabby](https://tabby.sh/) now, which has tons of own color schemes, some are merged with the application colors, others are probably not so that I get very nice colors in the timestamp column:

![tabby](https://user-images.githubusercontent.com/5188366/222380458-14a90e4b-f261-4fd2-bb15-fce11071cfeb.png)

**Comment by leo-arch** [comment]
Hey @muellerto! Good to know. Yes that's how it is supposed to look like.

Btw, timestamps in the latest version are `ls`-like by default:

```
Jan  2  2022
Oct 16 01:59
Feb 17 17:17
```
But you can customize it the way you like via the [`TimeStyle` option](https://github.com/leo-arch/clifm/wiki/Common-Operations#time-styles) in the config file. For example, to get the previous timestamps format:

```
TimeStyle="%F %T"
```

**Comment by leo-arch** [comment]
Still warm from the oven: **relative** timestamps

```
TimeStyle=relative
```

**Comment by muellerto** [comment]
Saw this on my Linux laptop now, but this feature is rather not mine. I often have to compare timestamps of files (log files and such stuff) down to minutes and seconds, I always found such relative timestamps [1] more obstructive than helpful. I will probably avoid to use this.

[1] I have a subversion client which says indeed (if you allow this) a commit is from "yesterday", and the next day it says for the same commit "2 days ago" - unusable for anything.

**Comment by leo-arch** [comment]
Hey @muellerto, that's why relative time is optional (and not default): some people might find it useful, while others don't. The good thing is: we have choices.
