### ISSUE TITLE
no colors with wezterm

### ISSUE THREAD

**Issue by mimame** [leo-arch/CliFM#190]
**Describe the bug**
Wezterm with terminfo well installed clifm doesn't show the default colors
It works perfect with kitty terminal for example

**To Reproduce**
1. Run wezterm
2. Then run cli
3. See no colors with default configuration

**Expected behavior**
See clifm with the default colors

**Desktop (please complete the following information):**
 - OS: nixos
 - Terminal wezterm
 - CliFM version: 1.10
- Installation source: nixpkgs

**Comment by leo-arch** [comment]
Hi @mimame. Thanks for reporting, I'll investigate this issue.

As a workaround, you can try running **clifm** as follows:

```sh
CLIFM_FORCE_COLOR=1 clifm
```
For more info about env variables see https://github.com/leo-arch/clifm/wiki/Specifics#environment.

**Comment by mimame** [comment]
Unfortunately, same behavior, still no colors with wezterm
I can't find the root of the issue with strace command :disappointed: 
Maybe there is some kind of issue between wezterm terminfo and clifm

Thanks so much for this amazing tool and your fast support! :smile: 
Don't hesitate to ask more info if needed

**Comment by leo-arch** [comment]
Ok. We have two issues here:

1. **Clifm** cannot find `wezterm` in the terminfo database
2. **CLIFM_FORCE_COLOR** should force **clifm** to use colors, no matter what the terminfo db says (it's sometimes wrong or incomplete)

Both seem to be easily fixable issues. I'll let you know as soon as I have good news.

**Comment by leo-arch** [comment]
@mimame, should be fixed now (https://github.com/leo-arch/clifm/commit/81d0250dda5bbf0d844a1ac8b76e7bdd4ce1ca06). Please give it a try a let me know if it works for you too.

**Comment by mimame** [comment]
Hi @leo-arch,
I'm glad to confirm the issue is fixed!
Thanks so much @leo-arch :smile: 
As soon as you release a new version, I will update nixpkgs unstable and backport it to stable :tada:

**Comment by leo-arch** [comment]
Thanks @mimame! It's so nice to see people giving some love to this thing: devs alone are not enough to make free software work as intended.
