### ISSUE TITLE
icons are not visible in search results

### ISSUE THREAD

**Issue by deathtrip** [leo-arch/CliFM#195]
**Describe the bug**
When launching with icons enabled, they are not visible in search results. I'm using the default emoji-icons.

**To Reproduce**
1. Launch clifm with the `--icons` option
2. Search for something `/mysearch`
3. See the search results with no icons.

**Expected behavior**
Icons should be visible in the results

**Desktop:**
 - OS : Arch Linux
 - Terminal : kitty, foot
 - CliFM version : 1.10.r87.g5b55536c
- Installation source : AUR git package

**Comment by leo-arch** [comment]
Hi @deathtrip. Thanks for reporting.

Icons were just never added to the list of search results. I'll add this to my TODO list and let you know as soon as I have it working.

**Comment by leo-arch** [comment]
Hey @deathtrip, now we have icons (and right padded ELN's) in search results too!

EDIT: CWD only.

**Comment by deathtrip** [comment]
Icons are now there, however the fix introduced 2 empty lines: one after the search term before the results, and another one before the "matches found" summary. They don't match clifm's generally tighter spacing.

**Comment by leo-arch** [comment]
Great! Extra spacing removed.

**Comment by leo-arch** [comment]
Should we close this issue then?

**Comment by deathtrip** [comment]
Yeah, i think we can close it. Thanks for fixing it so quickly. 🥇

**Comment by leo-arch** [comment]
@deathtrip, thank you for reporting.
