### ISSUE TITLE
Feature Request: .Deb Packaging

### ISSUE THREAD

**Issue by saintphaenixos** [leo-arch/clifm#2]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
I'd like to request a .deb package of this for Debian Based systems. This would simplify trying out the software, though I'll honestly say I'm not sure if it would negatively impact functionality of the software by doing so. Perhaps using something like this: [Pkger](https://www.reddit.com/r/linux/comments/mz176u/pkger_020_released_rpm_deb_and_pkg_building_tool/)

**Describe alternatives you've considered**
I've installed it on a command line only Arch install, which was okay, but running in a virtual environment. I also attempted to install it on Ubuntu 21.04 but the extra steps of installing the needed build tools kept producing errors that were hard to track down. I eventually got it, but it wasn't the most straightforward thing.

------------------------------------------

That aside, this is a really cool project, I love how lightweight it is and have never quite seen a File Manager like this. Thank you for working on it, It is a cool thing to see, and I'd love to use it on more machines.

**Comment by leo-arch** [comment]
This is an absolute yes @saintphaenixos. A .deb package is a must for  any respectable software. Indeed, I was playing around a few weaks ago trying to build a Debian package, and I was successful. However, the ideal solution would be some kind of automated build process to generate different packages, and not only for Debian, for every new release. I know about the exsitence of Travis and CI, but still couldn't make them work.
I can build now a .deb package to temporarily help you (and I will), but, as said before, this is far from ideal.

**Comment by saintphaenixos** [comment]
I would love even the temporary package. I really do appreciate the idea of this software, I'm a huge fan of basic terminal file managers.

**Comment by leo-arch** [comment]
@saintphaenixos, the .deb package is ready (sorry for the delay). Built and tested on Debian 10. Let me know if it works for you too.

https://github.com/leo-arch/clifm/releases/download/v1.0/clifm-1.0-x86_64.deb

BTW, I built it from the testing branch, so the "latest and greatest" is there.

**Comment by saintphaenixos** [comment]
No worries, this was very fast to me.

I just gave it a test, did an install and uninstall and on Ubuntu 21.04 I got a clean install and uninstall, and it works beautifully!

I'll need to dig in for deeper tests, but I think you have it ready to go. :+1: 

Thank you for this! This package will be on all of my machines very quickly.

------------------------------------

I don't know if you'd like to leave the issue open until the .Deb's are part of the regular build process or close it now, as the issue has been brought to your attention.

If not, feel free to close it.

**Comment by leo-arch** [comment]
That's great! And yes, you're right: this issue will remain open until we find a way to automate the entire build process. O perhaps I could open a new one (asking more generally for automated build process for different distros and architectures) pointing to this one.

Thanks you so much. It's very nice and encouraging to know that people like your project and consider it useful. After all, that's why we're part of the Linux community, to share and learn.

**Comment by leo-arch** [comment]
And we finally have an automated build system! https://download.opensuse.org/repositories/home:/archcrack/

Great!
