### ISSUE TITLE
Add description to flags for tab-suggestion

### ISSUE THREAD

**Issue by theRoboxx** [leo-arch/CliFM#203]
Is it possible to add these short flag descriptions to clifm, like they are available in zsh?

clifm with TabCompletionMode=standard

![swappy-20230323_194605](https://user-images.githubusercontent.com/63428105/227318222-75a0e4c8-6e1f-4968-b127-23ee25c10efc.png)

clifm with TabCompletionMode=fzf

![swappy-20230323_194735](https://user-images.githubusercontent.com/63428105/227318301-b40dc916-df55-4853-af74-972536ab0d8e.png)

**Describe the solution you'd like**
![swappy-20230323_194527](https://user-images.githubusercontent.com/63428105/227318344-3bffd163-29d8-403e-be37-5643fc13dd55.png)

**Comment by leo-arch** [comment]
Hi @theRoboxx.

This is possible, and indeed done for some _internal_ commands (like the `cmd` command), but not for shell (or external) commands (not at least in the current state). To get the list of options for shell commands we parse the appropriate manpage; but our parser does not retrieve descriptions. `Zsh` does this, by contrast, using custom completion files provided by the application itself. So, no, we cannot do that at the moment.

What would be needed to get this done?

1. An algorithm to parse custom completion files (we have none at the moment).
2. Applications providing these files, which of course depends on external sources.
