### ISSUE TITLE
options in mimelist are ignored

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#209]
Hi, Leo

I have "mupdf %f 2>/dev/null &" in my mimelist for pdf files. But when I open pdf files from clifm, screen gets filled with error messages.
However if I use "ow" command and choose "mupdf %f 2>/dev/null &" to open pdf file there are no error messages on screen.

Are you able to reproduce this?

**Comment by leo-arch** [comment]
Hi @Docbroke! Quick test: not reproduced.

What kind of errors do you see? Does this happen only with PDF files, I mean, with `mupdf`? Can you use the exact same syntax with other applications?

**Comment by Docbroke** [comment]
Same happens with xournalpp. 
You will need a pdf file that produces errors with mupdf to reproduce, if you are using archlinux official mupdf-gl, mupdf will always give error about clipboard/unicode support, so that is not a problem. Zathura produces no error with same files.


![image](https://user-images.githubusercontent.com/16881701/229871310-03b44ecc-f6e3-4831-9b1f-73543f1f3eb3.jpg)

**Comment by leo-arch** [comment]
So, the errors are printed by `mupdf` itself, that's clear. The question is why these errors are printed only with the first procedure, not the second one, when they're supposed to be the same.

Let me take a look a it.

**Comment by leo-arch** [comment]
Replace your line by this one (according to the [new syntax](https://github.com/leo-arch/clifm/wiki/Specifics#stderr-and-stdout)):

```sh
mupdf %f !EO &
```
This will run `mupdf` in the background ignoring both STDERR and STDOUT.

**Comment by Docbroke** [comment]
This works. Thanks.

**Comment by leo-arch** [comment]
Hey @Docbroke! Just realized that the `ow` command does not honor the `![EO]` notation. The fix is almost done; just a few more tests.

I'll let you know as soon as it is ready.

**Comment by leo-arch** [comment]
Done!
