### ISSUE TITLE
Clear screen with `rf`

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#210]
Hi Leo,

From your FAQ example, `rf` actually refreshes file list, it doesn't clear the screen if there is `ClearScreen=false` in config file. Can you update the refresh command to do both, i.e., clear && refresh ? That shall be more useful to users with `ClearScreen=false`

**Comment by leo-arch** [comment]
@Docbroke, do you think the same should be the case for <kbd>Enter</kbd> (on empty line) and <kbd>Ctrl-l</kbd>?

**Comment by Docbroke** [comment]
Not with `Enter`, otherwise there will be no point of having `ClearScreen=false` setting.

**Comment by leo-arch** [comment]
Currently <kbd>Enter</kbd> refreshes the screen _only when the command line is empty_, not for every command (even if `ClearScreen` is set to false).

EDIT: I'll push the changes so that you can try it yourself.

**Comment by leo-arch** [comment]
Done. Give it a shot and let me know.

**Comment by Docbroke** [comment]
This is good. Checked.

**Comment by leo-arch** [comment]
Good. Closing.
