### ISSUE TITLE
3 symbols when file is selected?

### ISSUE THREAD

**Issue by muellerto** [leo-arch/clifm#213]
**Describe the bug**
When I select a file (or directory) I get now three symbols beside each other.

**To Reproduce**
Select a file. In the following picture I typed just `s 2`. The result is:
![1](https://user-images.githubusercontent.com/5188366/231066611-1467b96a-dfda-496a-972c-009b964285b5.png)
The line of file #2 gets three symbols on the left and will because of that be shifted to the right.

**Expected behavior**
Only one symbol.

**Desktop (please complete the following information):**
- OS: Windows 11 Pro
- Terminal: Windows Terminal (part of Windows 11)
- CliFM version: 1.11.7 from today
- Installation source: Git

**Additional context**
Not sure if this is a Windows problem. I didn't notice this yesterday on my Linux machine.

**Comment by leo-arch** [comment]
Looks like an easy fix. Let me take a look at it.

**Comment by muellerto** [comment]
Ah, this happens only in the long file view. The short view shows only the `*`.

**Comment by leo-arch** [comment]
Reproduced.

**Comment by leo-arch** [comment]
Solved. Easiest fix ever: literally a one-char fix (https://github.com/leo-arch/clifm/commit/062438b8d5fb75dff80ebb8f654273a0ade2c365).

**Comment by muellerto** [comment]
Great! A fix in a few minutes around the globe, I love this! :)

**Comment by leo-arch** [comment]
Like magic!

Btw, I implemented a new way of displaying symlinks: instead of a fixed color for all symlinks, the color of the target file is used and the symlink name is preceded by a `@`. Set `ColorLinksAsTarget` to `true` in the config file to try it. Still in testing stage, but it works pretty nice.

**Comment by muellerto** [comment]
Could be interesting this symlink feature.
