### ISSUE TITLE
wrong colors

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#218]
**Describe the bug**
When you edit clifmrc using `F10` and close it (you don't even have to change something, just close) the files are shown in wrong colors.

**To Reproduce**
1. press `F10`
2. just close the editor (`:q` in vi)
3. the file list appears again but has now some wrong colors

**Expected behavior**
The colors should always be according to the color scheme.

**Screenshots**
![2](https://user-images.githubusercontent.com/5188366/232412634-61d723c6-a640-4db5-99e3-919fc0257736.png)
This is immediately after closing clifmrc. The directories should be blue, instead they are dark cyan. Dark cyan is normally used by symbolic links, but symbolic links are now bright cyan.

**Desktop:**
- OS: Windows 11 Pro
- Terminal: mintty
- CliFM version: 1.11.9
- Installation source: Git from today

**Additional context**
These wrong colors are volatile. When you now press `Enter` or `rf` the display is refreshed in ordinary colors and remains then as expected.

**Comment by leo-arch** [comment]
Hey @muellerto! This one is weird: if nothing was changed in `clifmrc`, the screen should not even be refreshed after quitting the editor (have you tried running on a different terminal?).

Please try with a new profile (`clifm -P newprof`) and in stealth mode (`clifm -S`).

**Comment by muellerto** [comment]
Damned, this seems indeed to be an issue of mintty. When I use another terminal it doesn't happen but in mintty I still have it. Closing this case, probably not your business.
