### ISSUE TITLE
order changes unexpectedly

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#219]
**Describe the bug**
The order of directories changes after jumping into one and returning from there.

**To Reproduce**
The start situation is as follows:
![3](https://user-images.githubusercontent.com/5188366/232428275-2ae022d5-4523-47a9-99c8-64ecb9f0437e.png)
The directories are ordered, everything looks nice.

Then I step into 10_X using ELN `2`. I get there, all OK, and then I return from there using `..` I get again into the start directory but the file list looks now as follows:
![4](https://user-images.githubusercontent.com/5188366/232428857-e0436555-f463-4bb2-bbc5-11ae9556581e.png)
10_X is now at the bottom. Why? This changing order is especially annoying when you want to do an action in several directories and you must process them one by one.

**Expected behavior**
The order should not change as long as file names do not change.

**Desktop:**
- OS: Windows 11 Pro
- Terminal: mintty
- CliFM version: 1.11.9
- Installation source: Git from today

**Additional context**
This wrong order is volatile. When you press `Enter` or `rf` the order is again as expected.

**Comment by leo-arch** [comment]
Hi @muellerto. A few quick tests (I've recreated your dir structure) and no luck yet.

1. What sort order are you using? Run `st` to find it out. Run it both before and after changing the directory, to make sure it remains the same (if it changes, we a clearer notion of our problem).

2. Also, try running with a new profile (`clifm -P newprof`) to exclude a configuration issue (which nonetheless should also be investigated).
3. Run in stealth mode (`clifm -S`) as well, for the same reason.

**Comment by muellerto** [comment]
Sort order is: `none`. (note: `ListDirsFirst` is still `true` in .clifmrc)

But I can't reproduce this issue today. I have still the same binaries as yesterday, extra for a test. But it doesn't happen anymore. Strange. Yesterday I had it all the time.

I let the case open, will have a eye on it today.

**Comment by muellerto** [comment]
Never had this anymore. A self-solving problem, never good :(

**Comment by leo-arch** [comment]
I'll keep this in sight anyway.
