### ISSUE TITLE
Heredar funciones preexistentes

### ISSUE THREAD

**Issue by itsdeadguy** [leo-arch/clifm#22]
Hola, muy interesante este programa. 

Consulta: seria posible que clifm use funcionalidades que ya tengo configuradas en mi shell? en un principio el prompt, pero tambien tengo configurado colores y autocompletado con tab y seria medio engorroso tener que configurar todo 2 veces o bien aprenderme 2 maneras de hacer las cosas y tener que acordarme cual es cual.

Gracias

**Comment by leo-arch** [comment]
Hola @itsdeadguy. Gracias por tu consulta.

La verdad es que sería genial poder importar todas tus configuraciones directo desde la shell (especialmente el autocompletado via TAB), pero por el momento CliFM solamente importa aliases (tipo `alias x='y'`) y definciones XDG (para abrir archivos mediante la aplicación asociada).

De todas maneras, recordá que CliFM, si bien integrado a la shell, no es la shell, sino una aplicación distinta que corre encima de la shell.

Sin embargo, varias de las cosas que mencionás se configuran igual en la shell y en CliFM. El prompt de CliFM, por ejemplo, debería aceptar el prompt de tu shell (si usás Bash), sin mayores problemas (aunque depende por supuesto de lo complicado que sea tu prompt). CliFM reconoce todos los codigos de escape que se usan en el prompt de Bash. Lo mismo pasa con los colores: los codigos de colores son los mismos que usa la shell, a saber, aquellos determinados via **dircolors**(1) y la variable de entorno **LS_COLORS**.  CliFM usa los mismos códigos (por ejemplo di=34, para directorios), más algunos propios de CliFM. Así que, otra vez, no deberías tener problemas importando tus colores.

Espero haber sido de ayuda.

**Comment by leo-arch** [comment]
No te olvides de consultar la [wiki](https://github.com/leo-arch/clifm/wiki) en caso de necesidad. Por lo pronto, te recomiendo pegarle una ojeada a las secciones sobre el [prompt](https://github.com/leo-arch/clifm/wiki/Customization#the-prompt) y sobre los [colores](https://github.com/leo-arch/clifm/wiki/Customization#colors). Supongo que también te podría interesar la sección sobre [atajos de teclado](https://github.com/leo-arch/clifm/wiki/Customization#keybindings).

**Comment by itsdeadguy** [comment]
Ah, es con bash la cosa, con razon. Yo uso zsh. 

Gracias por la respuesta :+1:

**Comment by leo-arch** [comment]
De nada @itsdeadguy. Espero que puedas usar CliFM de todas maneras: la shell que uses no debería ser ningún impedimento. CliFM no depende de Bash ni de Zsh ni de Fish ni de ninguna otra shell.
