### ISSUE TITLE
show a summed up size of the selection

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#221]
**Is your feature request related to a problem? Please describe.**
When the user selects files and directories this is often because they should be copied or moved somewhere. When the destination place has limited size (for instance a 2GB-SD card) it would be good to know how much is currently selected. So the user could decide if a compression is needed, if another medium is needed and so on.

**Describe the solution you'd like**
When `PrintSelfiles` is true the selected files and directories are shown in a box below the files list. This box has normally a lot of unsused space on the right side where a sum of the sizes could be placed. To format this sum you could use the same file size settings as used for the file sizes in the long view.

There are also the `p` and `pp` commands which could help. Actually `pp sel` shows informations about each file in the selection but not the overall sum of the sizes.

**Additional context**
OK, such a sum of mega bytes will still be no guarantee for a successful copy or move operation because of block sizes on the destination side and so on. But it could be a good and useful hint for having a success or not. This is especially needed for move operations because in case of a full destination medium you have then a part of the files on one side and another part on the other side and must cleanup again.

**Comment by leo-arch** [comment]
Hi @muellerto. The total size of selected files is given in the Selection Box. Just run `sb` (or `Alt-s`).

However, I'll consider your suggestion: printing some info about selected files in the selected files section, when `PrintSelfiles` is enabled, could be a good idea.

**Comment by muellerto** [comment]
> Just run sb (or Alt-s).

Yeah, good to know. ;-) Since I have `PrintSelfiles` always on I've never used `sb` until now.
