### ISSUE TITLE
wrong directory used for startup of an executable

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#222]
**Describe the bug**
When you start an executable in the current directory using a command line like `./executable` and the current directory is not a directory itself but a symbolic link to a directory the executable will be started in the original directory the symbolic link points to.

**To Reproduce**
Imagine the following situation:

```
A (dir)                     B (dir)
    a (subdir)                b (symbolic link to a)
        executable               executable
                              other files and ...
                              ... directories under B
```

Now let clifm show the contents of `b` (these are indeed the contents of `a`).

When I now start an executable there in `b` using `./executable` the current working directory of the new process is `a`. This is unexpected.

**Expected behavior**
I would expect that the new process has a current working directory `b`. That can be important.

As a developer I have lots of binaries, also in different versions and with different options. Especially I must distinguish between debug and release binaries. But I want to run all of them in the same testing environment. So I often have symbolic links to several `Bin` directories under the same parent beside each other. On Windows it's usual that an executable finds other files based on it's own location. When other important files are now located somewhere under `B` they cannot be found when the process thinks it's working directory is based on `A`.

So I think it's not a big thing. You should not dereference a symbolic link before using it as current working directory for a new process, just use the path as is. When a new process gets a current working directory which contains a symbolic link it can dereference it on it's own if needed.

Found this on Windows. I'm not sure if this also happens also on Linux.

**Desktop (please complete the following information):**
- OS: Windows 11 Pro
- Terminal: mintty
- CliFM version 1.12.rc9
- Installation source: Git from today

**Additional context**
I know, starting an executable in the current directory seems rather strange on Linux. Maybe it doesn't even run there. But for development and testing purposes it's something I do a lot.

**Comment by leo-arch** [comment]
Hey @muellerto. Reproduced and working on it.

**Comment by leo-arch** [comment]
Should be solved now.

FYI: In the situation you described, the **real** current working directory is always `A/a` (as returned for example by **getcwd**(3)), because, from the perspective of the file system, there's no such thing as `B/b` (since `b` is not a real directory nor does it contain any file). It was rather the **PWD** environment variable what wasn't properly set (it was set indeed to the real current directory (`A/a`) instead of the apparent one, as seen by the user (`B/b`).

**Comment by muellerto** [comment]
Ahm ... `PWD`? This may contain the right value now but it's not a standard for anything and indeed I have it only because you set it. If I don't start clifm there's no `PWD` on my Windows machine. Do you mean a Linux program uses this on startup?

Not only on Windows a process gets a working directory assigned at startup. This is not an environment variable, it's a property of the process, like the environment, some file handles, some pipes, the threads, RAM and more. A call of `getcwd()` gets the value from the process, not from the environment. That's why a running process can also change it's working directory using `chdir()` which doesn't affect the environment at all.

Because of that the Windows-API function [`CreateProcess()`](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa) which is the base implementation for starting any new process on Windows has a separate parameter for this initial working directory. [`ShellExecute()`](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea) uses also a separate parameter. [`WinExec()`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-winexec) uses probably the executable's path.

The more convenient and more portable `spawn()` function does this somehow internally and that's not good at all, it's not even always documented, you find man pages of `spawn()` where the term "directory" is not even mentioned. I guess they inherit the initial working directory just from the parent process as many `fork()` man pages say. The best and most transparent practice seems to be a call sequence of `fork()` and then in the child process `chdir()` and `exec()` which starts then again a new (the 3rd) process but this one inherits the right initial working directory because it's parent (the 2nd) has already the right one.

Maybe you have an invisible shell between clifm and the executable, don't know. In this case it could be an idea to start this shell, let the shell change it's working directory using a simple `cd` and then start the executable which then inherits the shell's working directory. [see here](https://stackoverflow.com/questions/786376/how-do-i-run-a-program-with-a-different-working-directory-from-current-from-lin).

**Comment by leo-arch** [comment]
> Do you mean a Linux program uses this on startup?

I cannot make such a generalization, but `pwd` is a POSIX standard Unix utility and it does report **PWD** if set. Try running `pwd` on your `B/b` directory (whose real path is `A/a`) and you'll get `B/b`. Consult **pwd**(1p) for more info.

For testing purposes I wrote a little C program which outputs both **getcwd**(3) and the value of **PWD** environment variable and executed it, in the same directory (`B/b`), in several shells, including **clifm**. I got the same results:

```sh
getcwd: A/a
PWD: B/b
```
> Maybe you have an invisible shell between clifm and the executable

External programs are executed via **system**(3), which basically runs `sh -c CMD`, that is, it runs CMD through the system shell (namely, whatever `/bin/sh` points to).

**Comment by muellerto** [comment]
>For testing purposes I wrote a little C program which outputs both getcwd(3) and the value of PWD environment variable and executed it, in the same directory (B/b), in several shells, including clifm. I got the same results:
>
>getcwd: A/a
>PWD: B/b

Yes, that's what I also see on my Linux machine. Strange. The process knows already only the dereferenced link. I wouldn't have said this before. (I tried it on the plain `bash` command line.)

I'm rather sure this is different on a Windows machine. I check this tomorrow. I use this mechanism for years, I start an executable from inside a link and the executable knows this because the process gets this information for sure. I always thought this happens automatically on Windows but clifm has indeed found a way to do it different.

**Comment by leo-arch** [comment]
At least in Unix, executables wanting to know the current directory consult first **PWD** and then **getcwd**(3). Learned this the hard way: issuing `clifm .` if the current directory was a symlink to a directory, landed in the _target_ dir. I've cheked other file managers and shells and realized that my mistake was consulting **getcwd**(3) directly, bypassing **PWD**. Fixed it by simply adding a **PWD** check.

Please let me know whatever you find out about this issue, specially on Windows.

**Comment by leo-arch** [comment]
Made a few more tests: this behavior is not Linux-specific. I've run the same test on both FreeBSD and OpenBSD: same result.

**Comment by leo-arch** [comment]
UPDATE: The behavior of **getcwd**(3) seems to be implementation-defined. On Linux/BSD/Cygwin it returns the target directory of a symlink to a directory (i.e. the dereferenced symlink), but on MSYS/MinGW (ConEmu) it returns rather the symlink itself (which is what you expect).

**Comment by leo-arch** [comment]
Some further information:

On Linux, there are three functions informing the current working directory:

1. **getcwd**(3): Standard, portable
2. **getwd**(3): DEPRECATED
3. **get_current_dir_name**(3): Not portable (it's a GNU extension)

Both `1` and `2` behave the same. But `3`, just like **getcwd**(3) on MSYS, does return the symlink itself (instead of dereferencing it).

**Comment by muellerto** [comment]
Yes, I mentioned only `getcwd()`, this is also available in Microsoft's runtime library (but has another header there). There are even some more implementations on Windows belonging to several frameworks. All these functions and also `getcwd()` itself are based on the fundamental API function [`GetCurrentDirectory()`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcurrentdirectory). Not good is that all these API functions are not documented very well when symbolic links are involved, symbolic links are a stepchild on Windows, so I can't reference a rule.

When an executable has been started out of a link on Windows I found that a call of `getcwd()` or `GetCurrentDirectory()` in the first line of `main()` gets reliably the link itself, as I initially expected. This is the case
- on the plain command line with `cmd.exe`
- when I use a "higher" starting application like the Explorer or a shortcut in the start menu
- when I use a 3rd party software like Multi Commander or any other file manager I have.

But it's not that easy. When I use another 3rd party software, I mean a command line running MinGW's `sh` (which is `bash` in my case) then I get always the dereferenced link. This is the proof of that the parent process is responsible for the directory the child process uses. `sh` does it this way and it's probably legal.

I checked this with MinGW (gcc) and especially with Microsoft compiled binaries (Microsoft Visual Studio, in my case 2022, this is what 90% of the Windows applications are made with, even when they are Visual Basic or .NET or whatever). The MinGW environment would still allow a clang build but I don't have clang installed.

Pfff, difficult. Thinking aloud:
- Yes, in case of my own application I could check if there's a `PWD` variable in the environment. But this would be a check if my application (which is my company's application) has been started from clifm what nowhere happens except on my developer machine. So it would rather be code for my own machine.
- All the other applications cannot do this because they don't know anything about a `PWD` variable and they don't have any code for it. The `PWD` variable seems to be a feature of `sh` - when `sh` is not running there's also no `PWD`.
- On the other side it's a rather rare case that a Windows application is started out of a link. This is a development use case, in production it's always a real Bin directory. And Windows itself is a rather exotic platform from clifm's point of view.
- Knowing all this now I would say: take this to the known issues. Sure you could try a special Windows workaround for a concrete `sh` behavior (as I said: `fork()`, `chdir()`, `exec()`) but there is probably no rule or specification for that and it could also lead to side effects we don't know at the moment and strange behavior of other applications which rely on that.

**Comment by leo-arch** [comment]
This is a confusing issue for sure. Just thinking aloud:

1. The current directory of the current process is set via **chdir**(3) (no other way as far as I know).
2. This current dir is inherited by the child process.
3. Since some implementations of **getcwd**(3) properly get the current dir (even if it's a symlink), this means that the parent process (in this case **clifm**) is properly communicating the current dir to the child. Otherwise, **getcwd**(3) on the child won't be able to get the proper directory: it would be lost, but it isn't.
4. Given the above, specially (3), I'd say that this problem cannot be addressed from the parent side, but from the child's, that is, the process running within **clifm**, but not **clifm** itself. As far as I can see, **clifm** is properly communicating the current directory to the child (which, again, is why some **getcwd**(3) implementations get the no-dereferenced symlink).

EDIT: Since external programs are executed in **clifm** via the system shell, maybe the whole thing relies on how this shell handles the current directory in case of symbolic links (and thereby how it communicates it to child processes).

So, you might be asking, why not to get rid of the system shell and execute external programs directly from **clifm** via **fork**(3)? Because by doing this we also get rid of all of the shell goodies: pipes, stream redirection, conditional execution, etc.

**Comment by muellerto** [comment]
There's one well documented rule on all platforms: the parent process inherits it's current working directory to the child process, if no other working directory is specified. This is the case on Unix as well as on Windows.

So, if the parent process has the right working directory also the child process gets it automatically.

When the parent process with working directory X wants to start an executable with working directory Y a forked intermediate process between the parent and the executable can be used. The intermediate process can then access a path variable (containing path Y) the parent process made before and so it can do an own `chdir()` with that path. After this the intermediate process has working directory Y and can then start any other executable so that this executable gets also the initial working directory Y by inheritance. The intermediate process can then end, it's task is done. Understand that initial case: not the started executable changes it's initial working directory, it get's always it's initial working directory from it's direct parent. That's why it's important that the parent has a correct working directory. (Of course it can change it's directory later, also based on `PWD` or whatever, but in the initial case it gets a directory from the parent. And an application which doesn't change on it's own will never get another directory than that from the parent.)

But in case of a shell between clifm and the executable it gets an additional layer which can have effects. That's not really predictable and must be checked. A shell seems to dereference the link. I guess this will also happen when you start the shell out of a link.

Perhaps I find a solution using a small shell script which uses `PWD`. OK, this shell script must then be specified on the clifm command line but this wouldn't matter. `start my_executable` could glue `PWD` and `my_executable` into one absolute path.

**Comment by leo-arch** [comment]
> Perhaps I find a solution using a small shell script which uses PWD

This _could_ be a nice workaround. Not sure. Let me know if it works for you.

**Comment by muellerto** [comment]
I hammered now an ultra sophisticated little C++ program for that problem called `rfl` (run from link).

First I tried a shell script but it's not that easy (or I'm not clever enough), the shell has always it's own ideas to handle paths and you never know what you get.

I was also not successful using the MinGW-gcc and "simple" Unix-functions like `getcwd()`, `chdir()`, `fork()` and `exec()`. Sure you can set a symbolic link as current working directory using `chdir()` but when you then check what you have using `getcwd()` you get it dereferenced and also the needed inheritance doesn't work as expected because of that. Learned a lot here.

I had to take MSVC and fundamental API functions because they work indeed very well with symbolic links and do not interpret too much. My result looks as follows:
![1](https://github.com/leo-arch/clifm/assets/5188366/396f5817-1bc0-4d80-9143-1127ebeb255a)
The main things are
- take the path from `PWD` if we have any
- set our own working directory to that path
- run the specified external which gets then the path by inheritance
 
I can now run any executable (also `pwd` or something) as

`rfl  executable  param1 param2 param3`

and it gets indeed started with the "right" initial working directory based on a symbolic link. I close this case, no change is needed in clifm.

**Comment by leo-arch** [comment]
That's great! Nice coding also.

> Learned a lot here.

Me too. That's the whole point of free software, isn't it?
