### ISSUE TITLE
Which tool is used for previewing gifs?

### ISSUE THREAD

**Issue by siduck** [leo-arch/clifm#23]
Hi there! nice cli file manager :D . which tool is used for previewing gifs in clifm? ueberzug? all gif  cli viewers  I have seen convert the gif to ascii or some format . I have seen the demo video and clifm plays the gif in its original form , How did you do that.

**Comment by leo-arch** [comment]
Hi @siduck76. No, gifs are not reproduced in their original form, that is, as gifs, but rather as a sequence of frames (jpg's) via ueberzug, one per 0.1 secs. Here's the code:

```sh
filename="$(printf "%s" "$entry" | tr ' ' '_')"
if [ ! -d "$PREVIEWDIR/$filename" ]; then
	mkdir -p "$PREVIEWDIR/$filename" && \
	convert -coalesce -resize "$WIDTH"x"$HEIGHT"\> "$entry" \
	"$PREVIEWDIR/$filename/${filename%.*}.jpg"
fi
while true; do
	for frame in $(find "$PREVIEWDIR/$filename"/*.jpg 2>/dev/null \
	| sort -V); do
		"$IMG_VIEWER" "$frame"
		sleep 0.1
	done
done
```

**Comment by siduck** [comment]
@leo-arch would this script work standalone? like :

script file.gif

**Comment by leo-arch** [comment]
No. It's part of two bigger scripts. But you can nonetheless modify the code to work in a simple shell script.

**Comment by leo-arch** [comment]
Feel free to inspect the scripts in question and modify them to fit you needs: [fzfnav](https://github.com/leo-arch/clifm/blob/master/plugins/fzfnav.sh) and [BFG](https://github.com/leo-arch/clifm/blob/master/plugins/BFG.sh). The code you need is mostly in `BGF.sh`. Pay special attention to both the `*.gif` case in the `handle_mime` function and to the `uz_image` function. It shouldn't be too hard to extract what you need and reduce it to a few lines long script.

**Comment by siduck** [comment]
thanks for the info! Btw where did you learn bash scripting? @leo-arch

**Comment by leo-arch** [comment]
Trying and failing, a lot of times. The web is your friend.
Btw, these scripts are not exactly bash, but POSIX sh. Very similar, but not bash.

**Comment by siduck** [comment]
@leo-arch does clifm load gif instantly? or takes some time to convert it into multiple images then loads it?

I get this error :(

![image](https://user-images.githubusercontent.com/59060246/120203097-f6da5300-c244-11eb-82c5-c36a05f61346.png)

**Comment by leo-arch** [comment]
Gif frames need to be loaded, but only the first time. Afterwards, since frames are stored in cache, the thing is more or less instantaneous.
Are common images displayed correctly? Does this happen only with gifs?

**Comment by leo-arch** [comment]
I've managed to reproduce the issue: Ubuntu 18.04, fresh install. I'll fix it soon.

**Comment by leo-arch** [comment]
The issue should be solved now. Just download the latest version of the [plugins](https://github.com/leo-arch/clifm/tree/master/plugins) (at least `fzfnav.sh` and `BFG.sh`), copy them to `$HOME/.config/clifm/plugins`, and give it a try.

**Comment by leo-arch** [comment]
Gifs previewing still doesn't work on the Ubuntu box, but images are now previewed fine. Working on it.

**Comment by siduck** [comment]
@leo-arch no worries , it works now :) . thx!
