### ISSUE TITLE
p shows link info, pp does not

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#230]
**Describe the bug**
`p` shows the source path of a symbolic link, `pp` handles a symbolic link as the file or directory itself and doesn't show the source path of the symbolic link.

**To Reproduce**
Assume you have a symbolic link onto a directory.
1. run `p` on it
2. run `pp` on it
3. compare

The output of `p` contains the information that the item is a symbolic link and that the link points onto somewhere.

The output of `pp` mentions the item as ordinary directory, even in the access bits (there's a `d`, not an `l`) and the Name attribute doesn't contain the source path. The value of the Name attribute has also the color of a directory, not of a symbolic link.

The same happens when the symbolic link points onto an ordinary file.

**Expected behavior**
I would expect that all the informations shown by `pp` (except the summed up size of the contained files) are equal to the `p` output. If the item is a symbolic link it should be visible.

**Screenshots**
In my picture BinD is such a symbolic link onto a directory:
![1](https://github.com/leo-arch/clifm/assets/5188366/3d12ea2c-112f-480e-92c3-33b7a857e592)

**Desktop**
- OS: Windows 11 Pro
- Terminal:: mintty
- CliFM version: 1.12.8
- Installation source: Git from yesterday

**Comment by leo-arch** [comment]
Hi @muellerto. Yes, and this is the intended behavior: `p` do not dereference symlinks (unless it is a symlink to a directory and the passed file name ends with a slash), while `pp` always does. In this way we provide a mechanism to get full information about both the link and the target file.

However, I do agree with you that the fact that a file is a symbolic link is somehow lost in `pp`. I'm thinking about a little modification to the `Name` field (only for symbolic links):

`p`:

```sh
Name: link -> target
... (link info)
``` 

`pp`:

```sh
Name: target <- link
... (target info)
```
EDIT: Done.

**Comment by muellerto** [comment]
I saw you did something, thanks a lot. But in my case it makes a stackdump now:
![2](https://github.com/leo-arch/clifm/assets/5188366/eb706324-da68-4f65-a7a8-bed6953d36eb)
Something doesn't work getting the real path of the directory. The designated path after Name is empty.

`p` is still good, `pp` not.

**Comment by leo-arch** [comment]
Ok. I'll take a look at it.

EDIT: Does this happen with all links or just with this specific one?

**Comment by leo-arch** [comment]
Reproduced and solved!

**Comment by muellerto** [comment]
Yeah!
