### ISSUE TITLE
Config option to run shell in interactive mode

### ISSUE THREAD

**Issue by dluciv** [leo-arch/CliFM#232]
**Is your feature request related to a problem? Please describe.**

My shell has lots of aliases defined (to make clear, I use Zsh with OMZ), and none of them are available via CliFM command line.

**Describe the solution you'd like**

I guess having config option to run shell commands in interactive mode will be nice. False by default, because interactive shells are much heavier.

**Describe alternatives you've considered**

Sure. `$ omz version` fails, but `zsh -ic 'omz version'` works great. But not sexy at all.

**Additional context**

Nope.

**Comment by leo-arch** [comment]
Hi @dluciv. As to aliases, see the [aliases section](https://github.com/leo-arch/clifm/wiki/Customization#3-importing-aliases).

Regarding interactive shells, you can always launch them from the command line (as usual, typing the corresponding command name), or entering `:` to launch the default shell (as defined by the **SHELL** environment variable). Exit the shell and you'll be back in **clifm**.

**Comment by dluciv** [comment]
Thank you!
