### ISSUE TITLE
Cyrillic input in command line

### ISSUE THREAD

**Issue by dluciv** [leo-arch/CliFM#233]
**Describe the bug**

When I try to type cyrillic characters to command line, CliFM does nothing. It can have non-ASCII filenames in command, pasted by typing file №, but not typed from keyboard.

For some purposes, e.g. when I want to rename a file, it does not allow me to do this. E.g. I have no chance to do `$ m hello.txt привет.txt`.

**To Reproduce**

Get any (I guess any) terminal for Linux or OS X.

Type a command `$ echo 00001й2ц3у4к5е6н70000`. It gets  `$ echo 000012345670000` typed, skipping all non-ASCII characters.

**Expected behavior**
I expect every character, which one types on a terminal, to be also available in CliFM command line.

**Screenshots**
Nope.

**Desktop (please complete the following information):**
 - OS: Linux, OS X
 - Terminal: KiTTY, WezTerm, but I guess any other also matches
 - CliFM version: 1.12
- Installation source: AUR

**Additional context**

Copy-paste above string with cyrillics to terminal (any one I tested with). Everything is typed nicely! Okay... this difference confuses completely. It is also strange, that in my case Greek characters are typed nicely. And a lot of exotic characters with compose key are also typed without problems.

**Comment by leo-arch** [comment]
Thanks for reporting @dluciv! I'll take a look at this one and let you know.

EDIT: Confirmed. Greek and other scripts work fine, but for some reason **clifm** does not play well with cyrillic.

**Comment by leo-arch** [comment]
Should be fixed now @dluciv! Please give a try and let me know if it works for you too.

**Comment by dluciv** [comment]
Thank you very much! Built from `master`, goes ok!
