### ISSUE TITLE
MinFilenameTrim is not applied in long view mode

### ISSUE THREAD

**Issue by deathtrip** [leo-arch/CliFM#236]
**Describe the bug**
Filenames are trimmed to the same length in long view mode as in normal mode, ignoring MinFilenameTrim setting.

**To Reproduce**
1. Set MinFilenameTrim higher then MaxFilenameLen
2. enter long view mode
3. filenames are still trimmed to the MaxFilenameLen value

**Expected behavior**
MinFilenameTrim should override MaxFilenameLen in long view mode as per documentation.

**Desktop:**
 - OS: Arch Linux
 - Terminal [kitty, alacritty]
- Installation source:, AUR-git package

**Comment by leo-arch** [comment]
Thanks for pointing this out @deathtrip. Should be solved now.

**Comment by leo-arch** [comment]
Hey @deathtrip, did you give it a try? Is it working as expected?

**Comment by deathtrip** [comment]
Yes! Working as expected. Gonna close this one.
