### ISSUE TITLE
Add an `.editorconfig`?

### ISSUE THREAD

**Issue by spenserblack** [leo-arch/CliFM#239]
**Is your feature request related to a problem? Please describe.**
Before contributing to a repo (https://github.com/leo-arch/clifm/issues/238#issuecomment-1644385662) I feel a bit safer if there's an [`.editorconfig`][editorconfig] file so that I don't mess things up with incorrect line endings, missing final newlines, etc.

**Describe the solution you'd like**
[An `.editorconfig` file][editorconfig] sets up a compatible editor with some basic behavior:
- tab or space indentation
- indentation size
- automatically add a final newline
- set line endings
- charset

For example, since the linked issue comment talks about Fish:
```editorconfig
root = true

[*]
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true

[*.fish]
indent_style = space
indent_size = 4
```

**Describe alternatives you've considered**
Just going for it.

**Additional context**
Let me know if you have any questions.

[editorconfig]: https://editorconfig.org/

**Comment by leo-arch** [comment]
Didnt't know anything about EditorConfig. I'll definitely take a look at it.

**Comment by leo-arch** [comment]
Hey @spenserblack, hope [this](https://github.com/leo-arch/clifm/blob/master/.editorconfig) will be enough. Let me know if something comes up.

**Comment by spenserblack** [comment]
Yeah, that looks like it would be enough. It really just depends on your preferred style / editor behavior.

Just quickly skimming through your files, I found that you probably want to add this, though.

```editorconfig
[*.{yaml,yml}]
indent_style = space
tab_width = 2
```

Edit: `CMakeList.txt` probably needs 2-space indentation, too.

Edit 2: Nevermind, `CMakeList.txt` has mixed indentation it seems.
