### ISSUE TITLE
Long view mode doesn't respect "max name length unset"

### ISSUE THREAD

**Issue by tkossak** [leo-arch/CliFM#245]
**Describe the bug**
When max name length is unset, file names should be fully visible. It was working properly few versions back (I think in clifm v1.12 - lately I upgraded to v1.13 and it stopped working).

**To Reproduce**
1. Create files:
`n a01234567890`
`n a0123456789012345678901234567890`

2. If you have max name length set to 20, unset it. I have shortcut for it: `toggle-max-name-len:\C-\M-l`
3. Enter long view mode (again my shortcut is `toggle-long:\M-l`)
4. Observe how file names are truncated in long view mode (see screenshot below)

**Expected behavior**
Files names should not be truncated, just as in normal (non long view) mode

**Screenshots**
![image](https://github.com/leo-arch/clifm/assets/3728245/986afa53-51ad-4d44-bf83-a4a110535300)

**Desktop:**
 - OS: Linux Manjaro
 - Terminal: Konsole
 - CliFM version: 1.13.8
- Installation source: git

**Comment by leo-arch** [comment]
Reproduced. Thanks @tkossak!

**Comment by leo-arch** [comment]
Fixed!

**Comment by tkossak** [comment]
Works, thank you!
