### ISSUE TITLE
unexpected timestamp format in p and pp?

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#248]
**Describe the bug**
For a while now I have native file timestamps in the output of `p` and `pp`. These timestamps have suddenly another format than the timestamps in the files list.

**To Reproduce**
1. just press `p` or `pp` for a file or directory

A file in the files list has a timestamp like `2023-01-16 13:15:35`.

`p` and `pp` show the same timestamp as `Mo Jan 16 13:15:35.622705300 2023 +0100` which
- is language dependent
- contains the day of week
- has the month as an abbreviation
- has nanoseconds
- and contains a time zone information (which also includes DST)

Interesting is that the abbreviated day of week is German, the access and the birth timestamps show this, but the date format ("Jan 16") is English (German would be "16.Jan").

Is this really intended?

I guess this comes from any runtime library function (`strftime()` or so) which is used here but not or not in the same manner in the files list. But this is what I get on Windows with the runtime library of gcc on a machine where the locale is `de_DE` (German). I didn't check this on my Linux machine until now.

**Expected behavior**
I would expect that all timestamps have just the same format and are directly comparable.

**Screenshots**
![1](https://github.com/leo-arch/clifm/assets/5188366/22d64525-d47f-46ed-856b-97e969e6931d)

**Desktop (please complete the following information):**
- OS: Windows 11 Pro
- Terminal: mintty
- CliFM version: 1.14 rc4
- Installation source: Git from today

**Additional context**
This "problem" is there since 1.12 or so, can't remember anymore. I don't press `p` every day.

**Comment by leo-arch** [comment]
Hi @muellerto. Yes, it's intended.

Timestamps in the files list are customizable via the `TimeStyle` option in the configuration file. As far as I can see, you're using the legacy style (`%F %T`), which is not locale sensitive. Change it to whatever you like using the format modifiers provided by [**strftime**(3)](https://www.man7.org/linux/man-pages/man3/strftime.3.html). The [config file](https://github.com/leo-arch/clifm/blob/master/misc/clifmrc) provides a few examples.

As to the `p` and `pp` commands, the time style is hardcoded to `%a %b %d %T.%n %Y %z` (the only way I've found to add nano-second precision - `%n` is not provided by `strftime`, but inserted by **clifm**). These modifiers are locale sensitive.

> Interesting is that the abbreviated day of week is German, the access and the birth timestamps show this, but the date format ("Jan 16") is English (German would be "16.Jan").

`Jan 16` isn't English, it's the abbreviated month name according to the current locale (`%b`) plus the day of the month as decimal number (`%d`). As far as I know, there's no modifier in `strftime` to print something like `16.Jan` (i.e. day and month name together).

EDIT: Yes, I could use `%c`, namely, the preferred date and time representation for the current locale. But in this case I wouldn't be able to insert the nano-second precision field, because I cannot know in advance how the resulting string will look like, and thereby I cannot manipulate it programmatically.

**Comment by leo-arch** [comment]
> I would expect that all timestamps have just the same format and are directly comparable.

In that case, you can set the time format for the files list to the same used by the `p`/`pp` command by setting `TimeStyle` in the config file to something like `%a %b %d %T %Y` (nano-second precision is not available and the time zone (`%z`) might be a bit too much).

**Comment by muellerto** [comment]
> Hi @muellerto. Yes, it's intended.

Ah!

> Timestamps in the files list are customizable via the TimeStyle option [...]

Yes, of course, but they are good this way. I would never change it.

> As to the p and pp commands, the time style is hardcoded to %a %b %d %T.%n %z

Somewhere is a `%Y` missing. That year is not good there and this was indeed the motivation for my post. The year belongs truely to the date part but it appears unexpected after the nanoseconds. I know, `%c` does it similar but that's also not good at all, I always asked myself who needs this like this. And then comes still the time zone which belongs again to the time part. There's no order in it.

Just wanted to ask.

**Comment by leo-arch** [comment]
Yes, I just forgot to add the year (`%Y`). Do you have some advice about what would be the most convenient order/format for these fields?

EDIT: Maybe I should follow **stat**(1) neutral style: YYYY-MM-DD HH:MM:SS.n TZ.

**Comment by leo-arch** [comment]
Done. Switched to stat(1) neutral time format.

**Comment by muellerto** [comment]
> Yes, I just forgot to add the year (`%Y`). Do you have some advice about what would be the most convenient order/format for these fields?

I would prefer the year just after the day, so you get at least a complete date like `Mo Aug 16 2023`. And the entire rest is just the time part.

> EDIT: Maybe I should follow **stat**(1) neutral style: YYYY-MM-DD HH:MM:SS.n TZ.

I would prefer that because it's similar to what I have in the files list. But I understand that other people could have other timestamps in the files list. So it would really be a good idea to keep both timestamps as similar as possible.

When I understand this right your main interest is to add nanoseconds and TZ. So you just need to search for the seconds in the TimeStyle, I mean `%S`. If you don't find the seconds you can't add anything (or you do then an even more sophisticated search for minutes and add also seconds). If you find a `%S` you have the position for the nanoseconds. It gets not much more complicated when the user used `%r` or `%X`, the seconds are always at the end. Complicated is only `%c` because you don't know what you get, but in that case I would just assume that the seconds are at the end, this will probably also be the case in RTL environments, so you can just add the nanoseconds after that.

**Comment by leo-arch** [comment]
I'll keep thinking about this (maybe adding the possibility to customize timestamps for the `p` command). But for the time being this is what we have:

1. Timestamps in the files list default to the same format used by `ls -l` (namely `%b %e %H:%M` for recent files (< 6 months) and `%b %e  %Y` for older files). This field is customizable though.
2. Timestamps for the `p` command are hardcoded to the stat(1)-style: `%F %T.%n %z`.

`1` is pretty fine: people is just used to that format and is customizable.
`2` is fine too: people is used to this format as well (and we don't need to mess with locales). However, making it customizable would be nice (but we'll probably lose nano-second precision).

**Comment by leo-arch** [comment]
Hey @muellerto, you can now use `PTimeStyle` in the config file to customize file times displayed in the `p/pp` command (relative times are not supported, just as nano-second precision is not available for user-defined styles).

**Comment by muellerto** [comment]
I have the following now:

```
TimeStyle="%Y-%m-%d %H:%M:%S"
PTimeStyle="%Y-%m-%d %H:%M:%S %z"
```

Works immediately :) I think this is the best solution. Thanks a lot.

**Comment by leo-arch** [comment]
Hey @muellerto, nano-second precision is now available for `PTimeStyle` via the `%N` modifier. Example:

```
PTimeStyle="%Y-%m-%d %H:%M:%S.%N %z"
```
This is the default value.
