### ISSUE TITLE
Readline vi-mode remapping compatibility

### ISSUE THREAD

**Issue by vanya-robertson** [leo-arch/CliFM#259]
I am a non-QWERTY user who cannot make vi-mode remaps in readline.cfg. Behaviour seems the same, no matter what I try.

I would welcome any solution.

Thank you,
Vanya

**Comment by leo-arch** [comment]
Hi Vanya, thanks for reporting. What are you trying to accomplish exactly? A concrete example would be really useful to carry out a few tests. Btw, do you mean `readline.clifm`, isn't it?

EDIT: Is the **INPUTRC** environment variable defined in your system? If yes, this is why `readline.clifm` isn't read at all (try removing this variable from your environment, or run in [secure-environment mode](https://github.com/leo-arch/clifm/wiki/Specifics#a-secure-environment) via `--secure-env`).

**Comment by vanya-robertson** [comment]
Hi, Leo.

INPUTRC is not defined.

In readline.clifm, i have these lines:

```
$if mode=vi                                      
    set keymap vi-move                                 
    "i": backward-char
$endif 
```

Esc does enter me into vi-mode, as the qwerty keybindings work. I would like to remap i to backward-char, but there is no change in behaviour.

**Comment by leo-arch** [comment]
Have you been able to do this in Bash (via `~/.inputrc`)? I've tried and failed. The point is: is this issue clifm-specific?

**Comment by vanya-robertson** [comment]
When set in .inputrc, it works in bash, python and tasksh, all readline programs; it does seem to be clifm-specific.

I can unbind the hjkl keys in readline.clifm:
```
$if mode=vi                                      
    set keymap vi-move
    "h":
    "j":
    "k":
    "l":
    "i": backward-char
$endif 
```

**Comment by leo-arch** [comment]
I'll keep investigating.

**Comment by vanya-robertson** [comment]
Thanks, man

**Comment by leo-arch** [comment]
Hey @vanya-robertson, made a little modification. Could you give it a try now?

**Comment by vanya-robertson** [comment]
Works perfectly, you absolute legend.
