### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by comradekingu** [leo-arch/clifm#26]
It is possible to add libre projects via https://hosted.weblate.org/hosting/
https://docs.weblate.org/en/latest/ has info on setting things up.
If you add https://hosted.weblate.org/user/kingu/ as a user there, I can help.

**Comment by leo-arch** [comment]
Ok. You're in.

Thanks!

**Comment by leo-arch** [comment]
Hey @comradekingu, thanks for your work on Hosted Weblate: they finally granted us the free account!
Maybe I'll start the Spanish translation myself, if I get some time.

**Comment by comradekingu** [comment]
@leo-arch 
If you do, add "Norwegian Bokmål (nb_NO)" as a secondary language on your account and possibly add context for the strings missing translations.
