### ISSUE TITLE
constant CPU utilization on linux

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#261]
**Describe the bug**
Even when idle, even after just starting clifm, CPU usage is constant at about 3.4% on linux

**To Reproduce**
Start clifm
observe CPU usage in bpytop or similar utility

**Expected behavior**
Since clifm is idle, I would expect CPU usage to be 0.0%

**Desktop (please complete the following information):**
 - OS: linux 6.5.10 (Sparkylinux, a Debian derivative)
 - Terminal: kitty
 - CliFM version 1.15
- Installation source: Opensuse .deb

**Comment by leo-arch** [comment]
Hi @knodalyte, thanks for reporting.

After a few quick tests on my machines, I'm not getting any unusual or unexpected CPU usage. Was this happening before 1.15?

Try running in [stealth mode](https://github.com/leo-arch/clifm/wiki/Specifics#stealth-mode) (`-S`) to discard config issues.

**Comment by knodalyte** [comment]
I didn't notice it before 1.15.
Running in stealth mode did not make a difference.

**Comment by leo-arch** [comment]
Could you confirm it wasn't there in 1.14?

Also, try running the git version, on a different terminal and a different shell.

**Comment by knodalyte** [comment]
I built and installed 1.14 from git. I did not show excessive CPU time. I ran 1.15 again and it did not show excessive CPU time, either. I am baffled, but I will close this issue.
