### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by vladtarko** [leo-arch/CliFM#267]
**Describe the bug**
The following dependencies are missing: `/sys/capability.h`, `magic.h`, and `/sys/acl.h`. 

To fix, the following need to be installed before running the `make install`:

    sudo apt install libcap-dev libmagic-dev libacl1-dev

**To Reproduce**
1. Run `sudo make install`
2. See error

**Expected behavior**
The install instructions should mention the need to pre-install the dependencies.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64, I assume Ubuntu would be the same.
 - Terminal: kitty
 - CliFM version: 1.16.7
- Installation source: Git

**Comment by leo-arch** [comment]
Hi @vladtarko. The [install instructions](https://github.com/leo-arch/clifm/wiki/Introduction#compilinginstalling-from-source) already mention deps as its first step. As to the main README (or front page) a link is included as a note pointing to this very page.

If there's something we can do to improve the documentation, do not hesitate to mention it.

Btw, we also provide [a .deb package](https://software.opensuse.org//download.html?project=home%3Aarchcrack&package=clifm) (via the OpenSUSE Build System) which should take care of automatically install the required dependencies.

**Comment by vladtarko** [comment]
Thanks, looks like I missed that table earlier!

**Comment by leo-arch** [comment]
Thank you for trying **clifm**.
