### ISSUE TITLE
Build failure with -D_NO_ICONS

### ISSUE THREAD

**Issue by FluffyJay1** [leo-arch/CliFM#269]
**Describe the bug**
Build fails if the -D_NO_ICONS flag is set.

**To Reproduce**
1. Run make with the -D_NO_ICONS cflag
2. Observe the build fails

**Expected behavior**
The build succeeds

**Screenshots**
```
src/colors.c: In function ‘get_ext_color’:
src/colors.c:773:39: warning: implicit declaration of function ‘hashme’ [-Wimplicit-function-declaration]
  773 |                 return check_ext_hash(hashme(ext, 0), val_len);
      |                                       ^~~~~~
...
colors.c:(.text+0x1d09): undefined reference to `hashme'
...
colors.c:(.text+0x2100): undefined reference to `hashme'
...
collect2: error: ld returned 1 exit status
make: *** [Makefile:39: clifm] Error 1
```

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Terminal: foot
 - CliFM version: 1.17, also commit 62e9f684a8ad74fa51f0fcabde1a7ca1189b2cb2
- Installation source: git

**Additional context**
N/A

**Comment by leo-arch** [comment]
Thanks  @FluffyJay1. It should be fixed now. Give it a try and let me know if it works for you too,

**Comment by FluffyJay1** [comment]
awesome, works for me now
