### ISSUE TITLE
linker erros during the build process on on msys2

### ISSUE THREAD

**Issue by LinArcX** [leo-arch/CliFM#276]
**Describe the bug**
I can't build the clifm on msys2. I get linker errors:
https://gist.github.com/LinArcX/38c011f06c438c7ea8e184ef0c67fb50

**To Reproduce**
1. I installed: `libreadline-devel`, `gettext-devel`, `mingw-w64-x86_64-readline`, `mingw-w64-clang-x86_64-readline` 
2. Then run: `make install`

**Expected behavior**
It should compile and link without error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Terminal [e.g. xterm, alacritty]: I tried with wezterm and ConEmu. none of them working.(Shell: bash)
 - CliFM version [e.g. 1.4]: clone from git
- Installation source [e.g. OBS, AUR, Git]: git

**Comment by LinArcX** [comment]
`make -f misc/cygwin/Makefile` fixed the issue.

But i'm wondering.. since i'm not using cygwin. but just msys2. is it ok to use cygwin's Makefile?

**Comment by leo-arch** [comment]
Hi @LinArcX. Thanks for reporting.

Your dependencies are fine. Try to build as follows:

```sh
make -f misc/cygwin/Makefile
```

This is a Makefile specific to Windows systems (Cygwin/MSYS). You can also take a look at the [Cygwin install instructions](https://github.com/leo-arch/clifm/wiki/Introduction#small_blue_diamond-d-cygwin), which are supposed to be valid for MSYS too.

If everything goes fine, add the `install` subcommand:

```sh
make -f misc/cygwin/Makefile install
```

**Comment by leo-arch** [comment]
> But i'm wondering.. since i'm not using cygwin. but just msys2. is it ok to use cygwin's Makefile?

Good question. As far as I know, MSYS is just Cygwin under the hood, that's why it works.
