### ISSUE TITLE
ow doesn't work on symlinks

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#296]
**Describe the bug**
`ow` on a symlink doesn't bring a list of applications usable for this file type. The list remains empty.

**To Reproduce**
1. have a symlink on a file so that the symlink looks exactly like the file itself (same extension)
2. execute `ow` on that symlink

**Expected behavior**
I would expect that clifm acts on a symlink like on any other file.

**Screenshots**
![1](https://github.com/leo-arch/clifm/assets/5188366/9b6942c8-f8a0-4f18-a981-7ae846ef3d4a)

`ow` on number 11 brings nothing. `ow` on number 12 which is just a copy of the file behind number 11 works as expected. clifm makes a difference which is not needed.

**Desktop (please complete the following information):**
- OS: Windows 11 Pro
- Terminal: Hyper 3.4.1
- CliFM version: 1.19.3
- Installation source: Git from today

**Comment by leo-arch** [comment]
Hi @muellerto, and thanks for reporting. It should be solved now.

**Comment by muellerto** [comment]
Not sure. On Linux it seemed somehow to work. On Windows it looks like that:
![1](https://github.com/leo-arch/clifm/assets/5188366/49381a7c-4238-4f9d-aefb-0b28d8374782)

Interesting are here several things:
- sure I have MIME bindings for text files, for a .toml file like number 7 I should get seven text editors listed
- number 10 is an ordinary .js file, not a symlink, but does also list nothing
- but suddenly number 8 which is a symlink lists text editors

I don't see any system behind. Why don't all the links work like number 8?

**Comment by leo-arch** [comment]
Could you run `mm info` on those files refusing to work with `ow`? Does it inform some opening app? And, what is the informed MIME type?

Testing on my Windows box; cannot reproduce the issue yet.

**Comment by muellerto** [comment]
It's as follows:
![1](https://github.com/leo-arch/clifm/assets/5188366/129dfee7-e360-4759-b215-562a45681e2f)

- the files 7, 9 and 10 show a mime type but no associated application
- the files 8, 11 and 12 have different mime types but are all associated with vim

This explains the difference between number 8 (ow lists applications) and number 10 (ow lists nothing).

A question is why .js files seem to have no associations at all. The according rule is:
```
#-----------------------------
# Text
#-----------------------------

X:^text/rtf$=libreoffice;soffice;ooffice
X:(^text/.*|application/json|inode/x-empty)=$EDITOR;$VISUAL;kak;dte;vim;vi;nvim;gvim;micro;mg;emacs;notepad;ed;nano;mili;leafpad;mousepad;featherpad;nedit;kate;gedit;pluma;io.elementary.code;liri-text;xed;atom;nota;gobby;kwrite;xedit
!X:(^text/.*|application/json|inode/x-empty)=$EDITOR;$VISUAL;kak;dte;vim;vi;nvim;micro;mg;emacs;notepad;ed;nano
```

Ahhh, I read elsewhere that `application/javascript` is an own mime type, so .js files are not matched by `text/.*`. OK, I can add this in these lines. With that change it looks as it should:

![2](https://github.com/leo-arch/clifm/assets/5188366/34592bf6-d060-41b4-98d0-690065271b0a)

Thanks a lot for reading :)

**Comment by leo-arch** [comment]
Great!

I guess I'll modify the default `mimelist.clifm` file to include `application/javascript` as plain text:

```
X:(^text/.*|application/(json|javascript)|inode/x-empty)=...
!X:(^text/.*|application/(json|javascript)|inode/x-empty)=...
```
