### ISSUE TITLE
command 'x' doesn't open new window/clifmrc doesn't respect environment variables: 'clifm: $TERM: Command not found'

### ISSUE THREAD

**Issue by vorboyvo** [leo-arch/CliFM#317]
**Describe the bug**
I have `TerminalCmd="$TERM -e"` set in `clifmrc` but it doesn't seem to respect that. Especially as Lira/`mimelist.clifm`

**To Reproduce**
1. Set the above option in `clifmrc`
2. Try to use 'x'

**Expected behavior**
A new terminal window to open, respecting $TERM as set in my profile

**Output**
```
1 ⬇  meetings.md   ./rw-.r--.r-- alice users 7,19K jui  8 14:44
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
T2[1] 15:58 alice:randolph ~/Documents/notes
<0> $ clifm: $TERM: Command not found
```

**Desktop (please complete the following information):**
 - OS: NixOS (nix (Lix, like Nix) 2.91.0) with nixpkgs-unstable
 - Terminal: alacritty
 - CliFM version 1.22.rc1
- Installation source: Git, via nixpkgs overlay

**Comment by leo-arch** [comment]
Give it a try now.

**Comment by vorboyvo** [comment]
Forgot to reply - it works now!
