### ISSUE TITLE
Trimming names in long mode when MaxFilenameLen < MinFilenameTrim even when the former is -1

### ISSUE THREAD

**Issue by vorboyvo** [leo-arch/CliFM#318]
**Describe the bug**
The behaviour given is that in long mode, if MaxFilenameLen is less than MinFilenameTrim, then the MinFilenameTrim limit applies to determine when file names should be trimmed. This makes sense, for, e.g. MaxFilenameLen=2 or something. But for MaxFilenameLen=-1 (unlimited), it should be as if this value is arbitrarily large, not less than MinFilenameTrim, and so it shouldn't trigger this behaviour.

**To Reproduce**
Set TrimNames=true, MinFilenameTrim=20 (default), and MaxFilenameLen=-1.

**Expected behavior**
In long mode, as long as the window width permits, the file name should not be trimmed.

**Desktop (please complete the following information):**
 - OS: NixOS 25.05 (nixpkgs-unstable)
 - Terminal: alacritty
 - CliFM version 1.22.2
- Installation source Git

**Comment by leo-arch** [comment]
Should be fixed now.

**Comment by leo-arch** [comment]
@vorboyvo, is it ok now?

**Comment by vorboyvo** [comment]
Been busy and haven't had time to check it out, will do and update you when I get the chance

**Comment by vorboyvo** [comment]
Yes, it's good!

**Comment by leo-arch** [comment]
Great! Closing then.
