### ISSUE TITLE
add configuration option to default confirmation dialog to yes (or no)

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#319]
**Is your feature request related to a problem? Please describe.**
When I want to delete a file, clifm asks me to confirm. I must type y (or n) and <enter> .

**Describe the solution you'd like**
What I would prefer would have an option to have y or n selected by default so that I can just type <enter>. This would be controlled by an option in the clifmrc file and would support y, n, or unset as a default. It may be that it would make sense to make this more granular, so that the default could be set for each command like delete, trash, copy, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by leo-arch** [comment]
Hi  @knodalyte.

These lines are currently in the [main config file](https://github.com/leo-arch/clifm/blob/master/misc/clifmrc):

```sh
# If set to true, do not ask for confirmation before trashing files.
;TrashForce=false

# If set to true, do not ask for confirmation before removing files
# with the 'r' command.
# Note: If set to false, you can still use the '-f' parameter to turn
# confirmation off for a single command. E.g.: 'r -f FILE'.
;rmForce=false

# Set the default copy command. Available options are:
# 0 = 'cp -iRp', 1 = 'cp -Rp', 2 = 'advcp -giRp', 3 = 'advcp -gRp',
# 4 = 'wcp', and 5 = 'rsync -avP'
# 2-5 include a progress bar.
# Only 0 and 2 will prompt before overwrite.
;cpCmd=0
```

**Comment by knodalyte** [comment]
Hi @leo-arch,

Sorry, I had missed that. 

BTW, I had been away from clifm for a while (in yazi-land), coming back I have been very impressed with all the improvements, congratulations to you and the other contributors.

**Comment by leo-arch** [comment]
Thanks @knodalyte! If trying an app is a good thing, going back to it is much better (and staying, even better!).

**Comment by knodalyte** [comment]
But what I am looking for is not zero confirmation, but being able to just hit <Enter> most of the time instead of y<Enter>.
No confirmation sounds scary...

**Comment by leo-arch** [comment]
> No confirmation sounds scary...

Totally agreed.

Could you provide a concrete example? I'm not sure to correctly understand what you mean.

EDIT: This is what I understood. A confirmation prompt should have a default answer, something like this: `Remove this file? [y/N]`, where the uppercase character is the default answer. Just pressing Enter amounts to entering the default answer, in this case `N`. Is this right?

Now, which confirmation prompts should behave this way? Removals, trash? We have several of these prompts, not just for removal and trash. Should we do this for **all** of them? It seems too much.

As to how to implement this, an option in the configuration file is what I have in mind. But, should we use a single option to rule them all, or different options for different commands? Maybe a single one ruling removals and trash only? Or two, one for removals and another one for trash?

**Comment by knodalyte** [comment]
> EDIT: This is what I understood. A confirmation prompt should have a default answer, something like this: Remove this file? [y/N], where the uppercase character is the default answer. Just pressing Enter amounts to entering the default answer, in this case N. Is this right?_

Yes, that is what I had in mind.

As for how granular the configuration should be? If it is not difficult, perhaps each command that has a confirmation prompt could support a configuration option, but on an optional basis. For example:

`CommandConfirmations=r:N,t:Y,m:Y,bm:Y`

would default remove to N, trash to Y, move to Y, and bookmark to Y. Perhaps too cryptic, but most people could ignore it. Other commands would have their confirmation behavior unchanged, i.e. user would have to type y or n.

**Comment by leo-arch** [comment]
Here's the thing:

1. A default answer for confirmation prompts makes sense for widely used prompts (you want to be as quick as possible).
2. We have confirmation prompts for things used very sparingly, for instance, when you create a symbolic to a non-existent file, or a bookmark pointing to an already bookmarked path. In these cases a default answer doesn't seem to be required (and would unnecessarily clutter the config file).
3. We do have confirmation prompts for remove and trash, but not for copy and move: the confirmation prompt -overwrite only- comes in these cases from the shell commands themselves, i.e., **cp**(1) and **mv**(1), so that we cannot modify their behavior.

In this scenario, we can add a single option (say, `DefaultAnswer`) specifying answers for remove and trash (only these for the time being). The code to support default answers is already working, we only need the user interface (the config option).

**Comment by knodalyte** [comment]
I agree with your points, and _mildly_ look forward to eventual implementation of the option configuration in a future release.

**Comment by leo-arch** [comment]
@knodalyte, I agree with the general point: default answers are, after all, a more or less standard behavior for command line apps. What is not standardized at all, however, is the criteria to implement them (I've seen quite standard commands, say **mv**(1), having different default answers in BSD and Linux, for example).

Summarizing, I think default answers are a good idea. We only need a criteria and a good interface to implement them.

For the time being, a single config option (for a few cases we can handle, i.e. remove and trash) sounds like the best approach:

1. A single option is better than many (to avoid cluttering the config file, mostly).
2. This single option can be extended in the future to support more cases (without the need to implement new ones, which is annoying).
3. The current behavior (no default answer) will still be the default (to avoid confusing users).

**Comment by knodalyte** [comment]
Sounds good!

**Comment by leo-arch** [comment]
[Done](https://github.com/leo-arch/clifm/commit/e440deedd27b9f32fd62af50597c4251f1f12f4c). Add

```
DefaultAnswer=r:n,t:y
```
to the config file.

Explanation:

| Value |  Description |
| --- | --- |
| `r:n`  | Confirmation prompt defaults to `n` for the `r` command |
| `t:y` | Confirmation prompt defaults to `y` for the `t/trash` command |

By default, both prompts default to no default answer.

**Comment by knodalyte** [comment]
Thank you!

**Comment by leo-arch** [comment]
Hey @knodalyte, added the ability to set a _default default answer_. Here's how it works:

```
# A command separated line of fields defining default answers for
# confirmation prompts. Each field has two values separated by a colon (':').
# The left value indicates the command (for the time being only the following
# left values are supported):
#  'r': remove ('r' command)
#  't': trash ('t' command)
#  'R': bulk rename ('br' command)
#  'd': All confirmation prompts (excluding, if defined, the above ones)
#  'D': All confirmation prompts (including the above ones, no matter their value)
# The right value holds the default answer for the corresponding command:
#  'y' or 'n'.
# If unset (or set to any other value), no default answer will be used.
# For example, to set 'n' as the default answer for the 'r' command and
# trash, and 'y' for everything else: "r:n,t:n,d:y".
;DefaultAnswer=""
```

**Comment by knodalyte** [comment]
It gets better and better!
TY

**Comment by leo-arch** [comment]
Added a new option to `DefaultAnswer`: `o` (it stands for `overwrite files`), mostly for the `c` and `m` commands (which have now a builtin confirmation prompt, just like the `r` command).

For example, use `r:n,o:n,d:y` to set `r` command and `overwrite files` to `n` and everything else to `y`.

EDIT: These are the new default values: `d:y,o:n,r:n,R:n,t:y`, which reads: `no` for overwrite, remove, and bulk rename, `yes` for everything else, including trash. Do you think these are good sane defaults?

EDIT 2: Added a new right value,  `u`, to leave a prompt unset (no default answer, wait for explicit input). For example, to set remove to `n`, trash to unset, and everything else to `y`: `r:n,t:u,d:y`.

Take a look at the [current description in the config file](https://github.com/leo-arch/clifm/blob/d404fea6b45f39e69c00b7d7320a78dc7eee11a9/misc/clifmrc#L373).
