### ISSUE TITLE
MacOS port

### ISSUE THREAD

**Issue by juanandresgs** [leo-arch/clifm#32]
Any chance of getting this working on MacOS?

**Comment by leo-arch** [comment]
Hi @juanandresgs. There are chances, yes, but it is has been not tested on MacOS yet. It might work, but probably needs a few adjustments.
Have you tried compiling it from source?

**Comment by juanandresgs** [comment]
A couple of basic attempts at 'make build' (using GNU make 4.3 instead of the outdated OS version) turn up type errors for basic type definitions:

>gmake build                                                                                                                                                     master  ✭
cd src && gmake build
gmake[1]: Entering directory '/Users/user/CodeRepos/clifm/src'
cc -c -I/usr/local/include -O3 -fstack-protector-strong -march=native -Wall actions.c
In file included from actions.c:25:
./helpers.h:458:2: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t first_visit;
        ^~~~~~
        size_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
typedef __darwin_size_t        size_t;
                               ^
In file included from actions.c:25:
./helpers.h:459:2: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t last_visit;
        ^~~~~~
        size_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
typedef __darwin_size_t        size_t;
                               ^
In file included from actions.c:25:
./helpers.h:487:2: error: unknown type name 'mode_t'
        mode_t type; /* Store d_type value */
        ^
./helpers.h:488:2: error: unknown type name 'mode_t'
        mode_t mode; /* Store st_mode (for long view mode) */
        ^
./helpers.h:489:2: error: unknown type name 'ino_t'
        ino_t inode;
        ^
./helpers.h:490:2: error: unknown type name 'off_t'
        off_t size;
        ^
./helpers.h:492:2: error: unknown type name 'gid_t'
        gid_t gid;
        ^
./helpers.h:493:2: error: unknown type name 'nlink_t'
        nlink_t linkn;
        ^
./helpers.h:494:2: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t time;
        ^~~~~~
        size_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
typedef __darwin_size_t        size_t;
                               ^
In file included from actions.c:25:
./helpers.h:495:2: error: unknown type name 'time_t'; did you mean 'size_t'?
        time_t ltime; /* For long view mode */
        ^~~~~~
        size_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_size_t.h:31:32: note: 'size_t' declared here
typedef __darwin_size_t        size_t;
                               ^
In file included from actions.c:25:
./helpers.h:686:8: error: unknown type name 'off_t'
extern off_t total_sel_size;
       ^
11 errors generated.
gmake[1]: *** [Makefile:15: actions.o] Error 1
gmake[1]: Leaving directory '/Users/user/CodeRepos/clifm/src'
gmake: *** [Makefile:17: build] Error 2

**Comment by leo-arch** [comment]
It might need some extra library with definitions for *_t types. Let me take a look at it. The bad thing is: I cannot test it anywhere.

**Comment by juanandresgs** [comment]
Thanks! Happy to keep testing on my end if that helps.

**Comment by leo-arch** [comment]
I'll let you know. Just give me some time. Now working on the automated build system (trying Opensuse OBS).

**Comment by danfe** [comment]
Based on my FreeBSD porting experience, CliFM contains at least two Linuxisms which should be rewritten when porting to another (more or less) POSIX operating system: `realpath("/proc/self/exe", ...)` should be replaced as discussed [here](https://stackoverflow.com/questions/799679/programmatically-retrieving-the-absolute-path-of-an-os-x-command-line-app), and `fopen("/proc/mounts", ...)` as discussed... well, somewhere else. :-)

**Comment by leo-arch** [comment]
Hey, @danfe, thanks for the suggestions! I already replaced those references to `/proc`. Thanks.

**Comment by leo-arch** [comment]
Hi @juanandresgs. Thanks to @l2dy we finally have a macOS port!
