### ISSUE TITLE
When using vi-mode in readline, prompt line filled with a single Ctrl-A after using fzf

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#320]
**Describe the bug**
After escaping from viewing directory contents in fzf, the next prompt includes a Ctrl-A at the end of  the prompt itself. In words, the prompt line starts with 
`<0> $ ^-A`

**To Reproduce**
1. edit clifmrc, set `RlEditMode=0`
2. reload clifm
3. use fzf to view or select files `Alt-_`
5. exit from fzf using `Escape`
6. see that prompt starts with `^-A`

**Expected behavior**
Same as when `RlEditMode=1`

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal : happens in kitty and alacritty
 - CliFM version 1.22
- Installation source : debian

**Comment by leo-arch** [comment]
Thanks for reporting @knodalyte. I'll take a look at this as soon as I can.

**Comment by leo-arch** [comment]
@knodalyte, what do you mean by `Installation source : debian`?

**Comment by knodalyte** [comment]
Sorry, I see it in my package manager, but it's a debian package from download.opensuse.org.

I see that clifm is in the [debian----requested-packages](https://www.debian.org/devel/wnpp/requested)  list, and has been for 666 days...

**Comment by knodalyte** [comment]
P.S. Thank you for putting it up on opensuse, it's a help.

**Comment by leo-arch** [comment]
> and has been for 666 days...

And that's a big, demonic number. I've been trying to reach Debian repos for a while, yes; no luck.

**Comment by knodalyte** [comment]
The problem was due to a configuration error on my side. At one point in the past I had put all the .clifm configuration files in my ~/.config/clifm tree. I realized very recently that the current released versions of all these files are available in /usr/share/clifm. I removed any files that I had not modified and integrated my modifications into copies of the newer released versions (copied to my config directory).

Now this issue and a few other anomalies have disappeared.  Might be something for the troubleshooting doc or a FAQ.

Sorry for the false alarm.

**Comment by knodalyte** [comment]
Well, my .clifm files update may have improved some things but this issue is still unresolved.  Sorry for the confusion on my end, juggling too many changes.

**Comment by leo-arch** [comment]
Reproduced in `foot` (Wayland). On X, I don't see this specific issue, but others (and worse):

1. Pressing <kbd>TAB</kbd> doesn't trigger `fzf`, but the standard completion.
2. After pressing a keybinding (say <kbd>Alt+-</kbd>), and exiting the corresponding function, the keyboard remains somewhat unresponsive until you press <kbd>Enter</kbd>.
3. Keybindings sometimes need to be pressed twice to actually work (the first time it seems to be invoking the wrong function, like emulating the UP arrow key).

**Comment by knodalyte** [comment]
Maybe this should be a separate issue, but when I trigger fzf using `TAB`, image and pdf files are displayed in the bottom quarter of the preview pane.

When I use `ALT-TAB` or the `view` command, previews are OK.

FYI, I am using X, not Wayland.

**Comment by leo-arch** [comment]
> Maybe this should be a separate issue

Yes please.

**Comment by knodalyte** [comment]
#321

**Comment by leo-arch** [comment]
> Reproduced in foot (Wayland). On X, I don't see this specific issue

I've reproduced the issue in all my boxes: had a different config in one of them, causing the behavior difference.

**Comment by leo-arch** [comment]
Hi @knodalyte. The issue should be solved now. Please give it a try.

**Comment by knodalyte** [comment]
Fixed, thank you!
