### ISSUE TITLE
 When I trigger fzf using TAB, image and pdf files are displayed in the bottom quarter of the preview pane. 

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#321]
**Describe the bug**
When I trigger fzf using TAB, image and pdf files are displayed in the bottom quarter of the preview pane. 

**To Reproduce**
start clifm
when in a directory with some files, press `TAB` to preview the file contents
observe that the previews for non-text files (images, pdfs) are displayed in the bottom 25% of the preview pane

**Expected behavior**
Previews should display centered in the preview pane.

**Screenshots**
Note that the PDF being displayed in the attached screenshot is narrow (for a leaflet), but other PDFs fill the width of the preview panel, but not the full height.

![2024-12-15_13-41](https://github.com/user-attachments/assets/832be5ca-8ec3-4a89-b5bc-cadac73d5089)

**Desktop (please complete the following information):**
 - OS: Linux debian
 - Terminal alacritty
 - CliFM version 1.22
- Installation source .deb from Suse builds

**Additional context**

**Comment by leo-arch** [comment]
Let's check a few things:

1. Since this is an `alacritty` terminal (which supports neither sixel nor the kitty protocol), I guess the previewing method here is `ueberzug`. Can you please confirm by inspecting the value of **$CLIFM_IMG_SUPPORT**? 
2. If it is it, report `ueberzug`'s version by running `ueberzug version` (the latest version is 18.3.1).
3. How are you invoking `clifmimg`? Run `view edit` to find it out (you should read something along this line: `^image/.*=~/.config/clifm/clifmimg image;`). Make sure [the up to date version of `clifmimg`](https://github.com/leo-arch/clifm/blob/master/misc/tools/imgprev/clifmimg) can be found in `~/.config/clifm`.
4. Finally, make sure you're running **clifm** via [the latest version of `clifmrun`](https://github.com/leo-arch/clifm/blob/master/misc/tools/imgprev/clifmrun).

**Comment by knodalyte** [comment]
My config:
1. yes, ueberzug
2. 18.2.3
3. no, I did not have the latest version, but I copied the version from that the clifm deb installed into ~/.config/clifmimg
4. same situation with clifmrun

I updated my version of ueberzug to 18.3.1 

Then I downloaded and replaced clifmimg and clifmrun  in ~/.config/clifm

The issue persists.

p.s. I changed the image method to kitty; images and pdfs were centered properly in the preview but unreadable, running in alacritty. Running in kitty, images and pdfs were not previewed at all. Back to ueberzug...

p.s. What is the difference between the `TAB` invocation of previews versus using the `view` command? The first has problems, the second works correctly.

**Comment by leo-arch** [comment]
> The issue persists.

Too bad.

> I changed the image method to kitty; images and pdfs were centered properly in the preview but unreadable, running in alacritty

Yes, `alacritty` doesn't support the kitty protocol (nor sixel images). `Ueberzug` is our only hope in `Alacritty`.

> Running in kitty, images and pdfs were not previewed at all

Are you running **clifm** via `clifmrun`? Try with plain `clifm` (`clifmrun` is only required for `ueberzug`).
Btw, does `view` work on Kitty?

> What is the difference between the TAB invocation of previews versus using the view command?

Almost nothing, except that image dimensions and placement is quite straightforward in the case of `view` (full screen is easier), but needs more computation when it comes to TAB completion (everything here is dynamic).

Can you try running on a terminal with [sixel support](https://www.arewesixelyet.com/) (say `xterm` or `mlterm`)? Run just `clifm`: it should work out of the box.

**Comment by knodalyte** [comment]
By default, I run using clifmrun.

View does not work on kitty.

Starting clifm from xterm produces unreadable images, like running using kitty protocol with alacritty.

**Comment by leo-arch** [comment]
1. Let's discard config issues. Run with a fresh config dir (and thereby config files) as follows:

```sh
clifm -D ~/.config/clifm-test
```
2. What's the output of `which -a clifm`?

3. > Starting clifm from xterm produces unreadable images

By `unreadable` you mean like ANSI-art? ANSI-art is the fallback method when no other image preview method is available (or **clifm** _thinks_ there's nothing else available).

4. Try running `clifm --preview IMAGE_FILE`. This what **clifm** internally runs to generate image previews. Maybe we can start debugging from here. Do this from `alacritty` (via `clifmrun`) to test `ueberzug`, from `xterm` to test `sixel`, and from `kitty` to test the `kitty protocol`. Just in case, try with `clifm --preview IMAGE_FILE -D ~/.config/clifm-test` as well (in case we have a config issue).

**Comment by leo-arch** [comment]
I think I've reproduced the original issue (`ueberzug`). If I'm not wrong, you have `--height` set, from either **$FZF_DEFAULT_OPTS** or `FzfTabOptions` in the color scheme file (check via `cs edit`), possibly to a negative value, a number prefixed with `~`, or a percentage.

Removing this option should solve the issue, at least for `ueberzug`. In the meantime, I'll try to work around it.

**Comment by knodalyte** [comment]
FZF_DEFAULT_OPTS is set to 90% by the fish fzf plugin.

I assume that by setting the height option appropriately in my colorscheme (default-256), I can resolve this issue. 

What should be the correct value? I experimented a bit but did not see an improvement.

**Comment by leo-arch** [comment]
For the time being, setting `--height` will confuse **clifm** (it will not properly calculate the height of the fzf window). Try just removing this value:

```sh
FZF_DEFAULT_OPTS="" clifmrun
```
You can keep options other than `--height` though.
I'm working on a fix.

**Comment by knodalyte** [comment]
Or, I could just start clifm with

`set FZF_DEFAULT_OPTS '' && clifmrun`

That works, and I start clifm with an alias anyway, I could simply amend it.

**Comment by leo-arch** [comment]
Good to know! The fix to support fixed values for `--height` is almost done. I'll let you know as soon as it is ready.

**Comment by leo-arch** [comment]
@knodalyte. With the [latest commit](https://github.com/leo-arch/clifm/commit/4a2c84ed6b9e7d99718e698a4b5d5bdbb7f83427) fixed values for `--height` (except for `~NUM`) are supported.

To try this, make sure your `clifmrun` script ([line 88](https://github.com/leo-arch/clifm/blob/4a2c84ed6b9e7d99718e698a4b5d5bdbb7f83427/misc/tools/imgprev/clifmrun#L88)) properly points to the latest binary.
