### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by danfe** [leo-arch/clifm#33]
I've added CliFM to the FreeBSD Ports Collection, and while porting had to provide alternative code paths which do not use `/proc` files specific to GNU/Linux.  Please consider merging [the patch](https://cgit.freebsd.org/ports/tree/misc/clifm/files/patch-src_misc.c) (and feel free to change according to your taste).

**Comment by leo-arch** [comment]
That's great news! Thanks @danfe! As to the patch, consider it done. Just give me a few days.

**Comment by danfe** [comment]
> As to the patch, consider it done. Just give me a few days.

Take your time, there's no rush.  You'd most likely want to adjust the patch, as I've only tested in on FreeBSD and wanted to have minimal diff, e.g. the `int j` variable would be unused in Linux case, and you'd probably want to insert a blank line before `if (!self || sysctl(mib, 4, self, &len, NULL, 0) == -1) {` and adjust the comment `Update filesystem counter ...` -> `Update mountpoint counter ...`.

**Comment by leo-arch** [comment]
Are you sure you don't want to submit this patch yourself via a PR so that you appear as a contributor to the project? I think that would be fair.

Btw, the patch works ok.

Have you had some issue with the makefile? I modified a few things and now it complains about `libintl.h` not being found.

**UPDATE**: The problem was `CFLAGS`. It seems that FreeBSD has some predefined value for this variable (`-O2 -pipe`), so that setting it in the makefile using `?=` won't work. Should I use `+=` in this case instead?

**Comment by danfe** [comment]
> Are you sure you don't want to submit this patch yourself via a PR so that you appear as a contributor to the project?

I'm not very comfortable with pull requests, and I'm usually not hunting for extra attribution either, just for better code, but I reckon `git commit` has this `--author` switch which should DTRT, no?

> Should I use += in this case instead?

In the FreeBSD port, I patch the `src/Makefile` to _amend_ the `CFLAGS` with `+=` rather than set it, not just because our framework provides default value for it which ports should respect, but also because it's a common build environment variable which better not be overwritten unless there's a strong reason to do so; e.g. `-march=native` is typically what should IMHO be left to user's discretion.

**Comment by danfe** [comment]
Ah, forgot to comment about headers not being found.  In FreeBSD, third-party software bits are installed under `/usr/local` prefix, so that's why we have this `USES+=localbase` thing which adds `-isystem /usr/local/include` to `CFLAGS` (and `-L/usr/local/lib` to `LDFLAGS`).  Another reason to respect, i.e. not trying to override them. ;-)

**Comment by leo-arch** [comment]
Great. I'll try the --author option then. Good to know about how FreeBSD handles these make flags. Thanks.

**Comment by leo-arch** [comment]
Patch applied and submitted. Though I couldn't use the `--author` function, I'll mention you in the changelog. Thanks again @danfe!

**Comment by danfe** [comment]
> Though I couldn't use the `--author` function

I've never used it on GitHub myself as well, but you might want to find [this guide](https://github.blog/2018-01-29-commit-together-with-co-authors/) and this one [with more elaborate animation](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) helpful.
