### ISSUE TITLE
make this available for void also !!!!!

### ISSUE THREAD

**Issue by ghost** [leo-arch/clifm#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leo-arch** [comment]
Hi @deepaknegilachu. It not us who decide what is made available to a given repository and what not, but the repository maintainers. Maybe you could open a new issue requesting CliFM to be added to Void repos: https://github.com/void-linux/void-packages/issues.

**Comment by ghost** [comment]
ok leo-arch thanks

**Comment by ghost** [comment]
btw great software . does it has tab completion ?

**Comment by leo-arch** [comment]
Thanks. Yes it does.
