### ISSUE TITLE
override this file prompt issue

### ISSUE THREAD

**Issue by danrobi11** [leo-arch/clifm#38]
**Describe the bug**

Hello @leo-arch 

I tried to copy a file where that file already exist.
The `override this file` prompt shows up but I cant type anything.
Therefore, im stuck there. 
Perharps, y/n is not what we should be typing ?

**Expected behavior**

Typing y/n  

**To Reproduce**

Im running kitty 0.13.3 terminal. Not sure if that can be part of the issue.

clifm_1.1-1_amd64.deb
OS: MX 19.4 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.96
Kernel: 5.10.0-5mx-amd64

**Comment by leo-arch** [comment]
Hi @danrobi11. Let me take a look at it. I'll let you know.
Thanks for the report.

**Comment by leo-arch** [comment]
How are you exactly trying to copy the file? Are you using the keybind (Ctrl-Alt-v) or just a command (and in this latter case, which command)?

**Comment by danrobi11** [comment]
> How are you exactly trying to copy the file

`s 17` and `C-M v`

Tested with the xfce4-terminal and same result.

**Comment by leo-arch** [comment]
Great. This bug was fixed a few days after 1.1 was released (https://github.com/leo-arch/clifm/commit/96c680c5f06e6df057f22f70a989102a1f69995d). You have two options here: you either wait for 1.2 release (a couple of weeks at most), or you compile from source and install the latest (development) version. It's not that hard really:

First, uninstall the current version:
```sh
sudo apt remove clifm
```
And then:
```sh
mkdir build && cd build
git clone https://github.com/leo-arch/clifm
cd clifm
sudo make PREFIX=/usr install
```
That's it.

If you prefer to wait, you can meanwhile just use the command instead of the keyboard shortcut:

`s17` and  `c sel`

**Comment by danrobi11** [comment]
> If you prefer to wait, you can meanwhile just use the command instead of the keyboard shortcut: `s17` and `c sel`

Ya I'll do that because I have an error while compiling.

```
install: cannot stat 'misc/{mimelist.cfm,keybindings.cfm,clifmrc,actions.cfm}': No such file or directory
make: *** [Makefile:51: install] Error 1
```

@leo-arch Thanks again for the support. Closing.

**Comment by danrobi11** [comment]
Well, reguardless the compile issue. Seems like the binary compiled in /usr/bin

Its working as intended here now. Weird.

**Comment by leo-arch** [comment]
> Its working as intended here now. Weird.

Yes, regardless the failure, the source files were compiled and the binary copied to `/usr/bin`. Some files nonetheless were not copied (plugins thus won't work). You were right indeed: the Makefile was failing.

Fixed now. You can repeat the process (delete the clifm directory first), and everything should work fine.

**Comment by danrobi11** [comment]
@leo-arch Compiled ok, working perfectly :)
