### ISSUE TITLE
plugins/ihelp.sh: manpage path is hardcoded

### ISSUE THREAD

**Issue by danfe** [leo-arch/clifm#41]
Right now, `manpage` path is hardcoded to `/usr/share/man/man1/clifm.1.gz` which probably works on GNU/Linux systems, as they usually (ab)use `/usr` prefix for third-party software, but won't work on e.g. FreeBSD, which uses `/usr/local`, or NetBSD, which uses `/usr/pkg` prefixes for that purpose.  I reckon it's better not to assume any particular prefix, but obtain one from the plugin script itself, something like this:
```patch
-manpage="/usr/share/man/man1/clifm.1.gz"
+sharedir=`readlink -f "$(dirname "$0")/../.."`
+manpage="$sharedir/man/man1/clifm.1.gz"
```

**Comment by leo-arch** [comment]
Hi @danfe. Totally true. I've been struggling with DATADIR in different systems for the last few days and I just missed this one. Indeed, last night I fixed this very issue on fzfnav plugin (https://github.com/leo-arch/clifm/commit/323733673a0d6167a697efc8db96323b1120bd8a).

Thanks! I'll try to fix this and let you know.

**Comment by leo-arch** [comment]
What about this: (https://github.com/leo-arch/clifm/commit/4e8400f7518aa34fa34ffc9fa96fd244675d563f)? It's a quick fix and needs some testing, but it should be fine.

**Comment by danfe** [comment]
Can't test right now but looks like it should work (not that I'm particularly big fan of hardcoded paths, but I guess the real world warrants all those checks).

**Comment by leo-arch** [comment]
I'll look for some way to remove harcoded paths. But in the meanwhile, it should work.

**Comment by leo-arch** [comment]
@danfe, I finally found the way. Take a look at https://github.com/leo-arch/clifm/commit/c78cf02c93ab6859365fcab1bea8fe8c42f7a0f1.
