### ISSUE TITLE
fails to make on OpenBSD 6.9 AMD64

### ISSUE THREAD

**Issue by BSDNix** [leo-arch/clifm#44]
**Describe the bug**
#include <ereadline/readline/readline.h> file not found

added the /devel/readline from openbsd ports.

#EDIT after looking myself: 

Changed the line "-lereadline" in the makefile and changed the the link to the readline.h file in src/keybinds.c to
"readline/readline.h"

a make install now gives me this: 

`
HP-MH# make install
Detected operating system: OpenBSD
cc -o clifm src/*.c -O2 -pipe   -I/usr/local/include -L/usr/local/lib -lreadline -lintl
src/keybinds.c:158:3: warning: implicit declaration of function 'rl_bind_keyseq' is invalid in C99 [-Wimplicit-function-declaration]
                rl_bind_keyseq(find_key("show-manpage"), rl_manpage);
                
src/keybinds.c:252:3: warning: implicit declaration of function 'rl_bind_keyseq' is invalid in C99 [-Wimplicit-function-declaration]
                rl_bind_keyseq("\\eOP", rl_manpage);
                
2 warnings generated.
ld: error: undefined symbol: rl_bind_keyseq
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced by keybinds.c
>>>               /tmp/keybinds-1a5042.o:(readline_kbinds)
>>> referenced 124 more times
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in /home/gnunix/clifm (Makefile:33 'build')
`

**Environment**
 - OS: OpenBSD 6.9 -STABLE
 - Shell KSH
 - Terminal ST

**Comment by leo-arch** [comment]
Hi @BSDNix. Why did yo close this issue? Is it solved?

**Comment by BSDNix** [comment]
> Hi @BSDNix. Why did yo close this issue? Is it solved?

Yes. I probably need to stop tinkering around myself :)
