### ISSUE TITLE
Output corruption with long japanese folder name

### ISSUE THREAD

**Issue by Chiheisen** [leo-arch/clifm#48]
**Describe the bug**
Any directory above a certain length corrupts the output in an increasing manner. This _only_ happens in paths with japanese characters (I haven't tried any other non latin script) from what I can tell. Leaving the directory restores the expected behavior if it's not completely broken.

**To Reproduce**
1. `mkdir 'あああああああああああああああああああああああああああああ'`, and cd into it with clifm. Here you'll start noticing the corruption. The space after $ is missing.
2. `mkdir 'あああああああああああああああああああああああああああああああ'`, $ is gone.
3. `mkdir 'ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ'`, output completely corrupted, at this point nothing really works except holding ctrl+c and q'ing out.

Note: 1. even repros the bug when you create the folder on `/`, so it's not the total length, but the length of the folder you're currently in. Creating a folder with repeating `a`'s until the fs complains does not repro the behaviour, even if `pwd | wc -c`
 reports a higher bytecount.
(E.g.: 3 is 198 bytes, a path I made with just aaaa's is 241 and does not trigger it)

**Expected behavior**
No terminal output corruption. 

**Environment (please complete the following information):**
 - OS: Arch
 - Program version: master, built with bc8fc15f8087310389560494cb67f9a572cf3537
 - Shell: bash and zsh
 - Terminal: tried kitty, alacritty, foot

(Sidenote, ELNs really make working with annoying to type paths such as japanese extremely easy.)

**Comment by leo-arch** [comment]
Hi @Chiheisen. Thanks for reporting this bug. I'm glad a new bug has come out of its hiding. I'll take a look at it right now.

**Comment by leo-arch** [comment]
This bug should be solved now; try it an let me know. Still a minor issue nonetheless when suggesting these long japanese dir names (when they take up to the next line): working on it.

**Comment by leo-arch** [comment]
The suggestions issue seems to be solved too.

**Comment by Chiheisen** [comment]
Works perfectly now, thanks! Suggestions from what I can see work as I'd expect too.

**Comment by leo-arch** [comment]
Thank you for pointing out this bug!
