### ISSUE TITLE
ihelp does not open correct line when MANPAGER is set.

### ISSUE THREAD

**Issue by ohle** [leo-arch/clifm#52]
**Describe the bug**
When opening the manpage with either `ih` or `F1-F3`, if `clifm` was started with the `MANPAGER` environment variable set, the man page does not open to the desired line.

**To Reproduce**
1. Run `export MANPAGER=less; clifm`
2. Select a topic from the `ihelp` plugin
3. manpage opens at the top

**Comment by leo-arch** [comment]
Thanks @ohle! Nothing serious. It should be fixed in a few hours. I'll let you know.

**Comment by leo-arch** [comment]
@ohle, the issue should be fixed now, both for the `ihelp` plugin and CliFM itself. Let me know if it works for you too so that I can close this issue.

**Comment by ohle** [comment]
Works perfectly, thanks!
