### ISSUE TITLE
[Feature request]: Use a build system

### ISSUE THREAD

**Issue by lgbaldoni** [leo-arch/clifm#53]
How about building clifm with cmake or meson? I think they are both well supported on every intended target.

**Comment by leo-arch** [comment]
Not very well versed on any of them, but will give them a try. Thanks for pointing it out @lgbaldoni .

**Comment by leo-arch** [comment]
Hi @lgbaldoni. I've been playing around with `cmake`. I've even got CliFM compiling using a `CMakeLists.txt` file. However, I'm not sure about the advantages over a simple `Makefile`. Our entire continue deployment system  (based on OpenSuse build system) is now working fine with `make`. Why do you think we should move to `cmake`? Does it really worth the effort?

**Comment by lgbaldoni** [comment]
Hi,

the main reason is checking for the availability of libraries and not having to bother finding out the correct

linking/include/installation paths for each target.

Also cmake can produce fast ninja build scripts and not just makefiles.

 

As openSUSE packager myself, I've noticed its usefulness. Of course if you don't plan on growing the application

much, then it's perhaps unnecessary, especially if you need to support strange platforms.

 

Regards

 

Sent: Friday, September 17, 2021 at 9:25 PM

**Comment by leo-arch** [comment]
Thanks @lgbaldoni! I'll bear this in mind.
