### ISSUE TITLE
Support more formats when importing aliases

### ISSUE THREAD

**Issue by JohannesGaessler** [leo-arch/clifm#54]
**Is your feature request related to a problem? Please describe.**
I have a file containing alias definitions.
I wanted to import this file to CliFM.
However, because I used double quotes instead of single quotes this did not work.

**Describe the solution you'd like**
I want CliFM to import aliases regardless of whether they were defined with single quotes or double quotes.
Feedback that an alias couldn't be imported due to formatting would also be useful.

**Describe alternatives you've considered**
Just editing them to fit the required format.
In my case it's not that much work.

**Comment by leo-arch** [comment]
This is easy to implement. I'll let you know when that happens.

**Comment by leo-arch** [comment]
Hi @JohannesGaessler. The job is done: the import aliases functions now supports both single and double quotes. Try it and let me know if it works fine, so I can close this issue.

**Comment by JohannesGaessler** [comment]
Importing of aliases with double quotes works with the `clifm-git` AUR package.

However, upon inspection of the clifmrc file I now noticed that the aliases appear multiple times if you source the same alias multiple times from a file.
This might be an issue if a user were to edit or delete one of the aliases in the clifmrc file, unaware of the fact that that alias will be redefined a few lines down.

**Comment by leo-arch** [comment]
Since I refactored the whole aliases thing, I guess I missed to check for existing aliases while importing. Working on it.

**Comment by leo-arch** [comment]
Well, not exactly what you asked, but should be fine. This is how it works now:

1. Imported aliases are now correctly compared against the current list of aliases: if the new alias name is already there, skip it
2. When loading aliases from the config file (at startup), duplicated names are skipped. Only the first one will be kept.

This approach won't prevent dup names in the config file, but it does ensure that only one (the first one) will be actually loaded.
After all, the procedure is always the same (for all programs dealing with config files): it is up to the user what she/he writes into the config file, but it is up to the program to correctly parse the file and load only valid values.
