### ISSUE TITLE
Use CliFM as the primary shell

### ISSUE THREAD

**Issue by JohannesGaessler** [leo-arch/clifm#55]
**Is your feature request related to a problem? Please describe.**
I want to use CliFM for some time as my primary shell to figure out whether I like it better than Zsh.
Ideally I would just type `chsh -s /usr/bin/clifm` and start with a CliFM shell on login.
However, CliFM is not registered as a shell.
Manually editing `/etc/shells` leads to a broken shell :( .

**Describe the solution you'd like**
Register CliFM as a usable shell and fix it.

**Describe alternatives you've considered**
Just adding `clifm $PWD` to the end of my `.zshrc` file essentially does what I want but it's not ideal.

**Comment by leo-arch** [comment]
I'll try to reproduce the issue and fix it. However, I'm not totally sure about using CliFM as a shell, since it is not a shell. I'm not trying to replace ZSH or Bash, but to run on top of them.

**Comment by JohannesGaessler** [comment]
Honestly that is how I would be using it though.
I rarely need to perform many file operations at a time, but rather only a few operations at a time.
If I need to start CliFM manually beforehand using the built-in commands like mv, cp, or rm would be faster in my case.

**Comment by leo-arch** [comment]
No problem. I guess it could be done. I'll let you know.

**Comment by leo-arch** [comment]
Hi @JohannesGaessler. This issue was hard to track, but I finally got it working. Try it and let me know.
You still need to manually register CliFM as a valid shell.

**Comment by JohannesGaessler** [comment]
As far as I can tell it works. Thanks!

**Comment by leo-arch** [comment]
Great! Please recall that CliFM isn't intended to be used as a shell. It's a nice experiment however. Please let me know how it turns out.
