### ISSUE TITLE
Man page does not mention that icons need icons-in-terminal everywhere

### ISSUE THREAD

**Issue by JohannesGaessler** [leo-arch/clifm#56]
The part of the man page that describes the command `icons [on, off]` does not mention that you need to have icons-in-terminal installed.
It's mentioned everywhere else but if this is the part where you read it first you'll wonder why the icons are broken.

**Comment by leo-arch** [comment]
Cool. I'll add this info to the manpage.

**Comment by leo-arch** [comment]
Done and closing.
