### ISSUE TITLE
clifmrc file has no option for icons

### ISSUE THREAD

**Issue by JohannesGaessler** [leo-arch/CliFM#59]
As the title says, the `clifmrc` file is missing an option to automatically enable icons.
I'm assuming this is a simple oversight.

**Comment by leo-arch** [comment]
Well, that's only half-true: this option is certainly not in the config file, but only available as a command line option. I just didn't want to overload the config file, so a few things were left out. However, if you feel this as a lack, I guess I should simply add it.

**Comment by leo-arch** [comment]
Done.

**Comment by JohannesGaessler** [comment]
Works for me. Thanks!
