### ISSUE TITLE
Musl support

### ISSUE THREAD

**Issue by Archetypic** [leo-arch/CliFM#60]
Hello, I get this [error](https://pastebin.com/GWE2nWXW) when executing `make`. I will be happy to troubleshoot and resolve it as I am currently learning C, but am still a novice.

**Comment by Archetypic** [comment]
My computer uses `musl` as the libc, which is most likely the issue.

**Comment by leo-arch** [comment]
Hi @Archetypic. Yeah, that's should be. Try passing `CC=gcc` (or clang) to the make command (`make CC="gcc" install`). 
What system are you using? I need to fix the Makefile to prevent this kind of errors without an appropriate warning message.

**Comment by Archetypic** [comment]
My computer is `x86_64-pc-linux-musl`.

Command: make -d -e cc=GCC -> [output](https://pastebin.com/gakjwpmx)

The same results occur with `clang`.

**Comment by leo-arch** [comment]
Two stupid questions, but just in case:
1. Do you have `gcc`/`clang` installed?
2. Are you running the `make` command from within `src/` directory?

**Comment by Archetypic** [comment]
**1.**
gcc -V
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/x86_64-pc-linux-musl/libexec/gcc/x86_64-pc-linux-musl/10.3.0/lto-wrapper
Target: x86_64-pc-linux-musl
Configured with: /var/tmp/paludis/build/sys-devel-gcc-10.3.0/work/gcc-10.3.0/configure --build=x86_64-pc-linux-musl --host=x86_64-pc-linux-musl --target=x86_64-pc-linux-musl --prefix=/usr/x86_64-pc-linux-musl --datarootdir=/usr/share --localstatedir=/var --sysconfdir=/etc --disable-dependency-tracking --enable-fast-install --enable-serial-configure --disable-bootstrap --disable-decimal-float --disable-install-libiberty --disable-libada --disable-libatomic --disable-libcilkrts --disable-libffi --disable-libgfortran --disable-libgo --disable-libgomp --disable-libitm --disable-libobjc --disable-liboffloadmic --disable-libquadmath --disable-libsanitizer --disable-libssp --disable-libstdcxx --disable-libstdc++-v3 --disable-libvtv --disable-vtable-verify --disable-multilib --disable-nls --disable-shared --enable-lto --enable-plugin --enable-plugins --enable-threads --enable-languages=c,c++,fortran,objc,obj-c++ --with-sysroot= --with-gxx-include-dir=/usr/x86_64-pc-linux-musl/include/c++/10.3.0 --without-isl --with-lib-path=/usr/x86_64-pc-linux-musl/lib --with-as=/usr/x86_64-pc-linux-musl/x86_64-pc-linux-musl/bin/as.binutils --with-ld=/usr/x86_64-pc-linux-musl/bin/x86_64-pc-linux-musl-ld --with-system-zlib --with-glibc-version=2.11 --enable-linker-build-id --with-multilib-list= --disable-libhsail-rt --enable-default-pie --disable-libphobos --enable-analyzer --with-zstd --program-transform='s,$,-10,' --enable-cet
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (GCC)
```

clang -v 
```

clang version 12.0.1
Target: x86_64-pc-linux-musl
Thread model: posix
InstalledDir: /usr/host/bin
Found candidate GCC installation: /usr/host/bin/../lib/gcc/x86_64-pc-linux-musl/10.3.0
Found candidate GCC installation: /usr/host/bin/../lib64/gcc/x86_64-pc-linux-musl/10.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-musl/10.3.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-musl/10.3.0
Selected GCC installation: /usr/host/bin/../lib64/gcc/x86_64-pc-linux-musl/10.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**2.**

No, I am using make and allowing the Makefile to execute `build:`. I am in the parent directory of `src/`

**Comment by leo-arch** [comment]
As far as I can see, the output you shared means that `make` isn't able to find the Makefile, so that it starts looking for an implicit recipe.

**Comment by leo-arch** [comment]
Btw, the value passed to `make` should be `CC=gcc`, and not `cc=GCC`. So, the list of commands should be:

```sh
mkdir build && cd build
git clone https://github.com/leo-arch/clifm
cd clifm
make CC=gcc install
```

**Comment by Archetypic** [comment]
`GLOB_BRACE` is not implemented in musl. Found in `src/strings.c` and `src/search.c`.

Link: https://www.openwall.com/lists/musl/2013/09/16/1

I will have an opportunity to put my C-Coding practice to use.

I can also create a merge request to add this function to this project as the writer states; though that is probably unnecessary.

**Comment by leo-arch** [comment]
I would be nice to make it work with `musl`. But for the time being, it should be working fine with either `gcc` or `clang`. Have you tried the commands I listed above?

**Comment by Archetypic** [comment]
`musl` is a C standard library that is compiled against. It is not something I can quickly replace since all of the programs on this computer are compiled against it. Most linux use `glibc` but some offer a `musl` variant such as void linux.

References: https://www.etalabs.net/compare_libcs.html  

https://voidlinux.org/download/

**Comment by leo-arch** [comment]
Good to know. In order to support Void (and musl systems in general), thereby, there seems to be two options (none of them available right now):
1. A binary statically linked against whatever required from glibc
2. Musl support

I have been working last night on 2, but unfortunately, I had no success yet (some progress was made though). Readline is the biggest obstacle: it seems that the only way out is to provide the whole readline library as part of the source code itself.

**Comment by Archetypic** [comment]
Thank your for your assistance.

👍

**Comment by leo-arch** [comment]
Thanks for yours! :wink:
