### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by hectormonacci** [leo-arch/CliFM#74]
_If working with the command-line, your workflow is not affected at all, but just enriched with file management functionalities: automatic **fles** listing, files selection,_ 

That comes from the first lines of README.md. I think you mean **file** listing.

Wonderful approach to terminal productivity! I just twitted about (see https://twitter.com/hectormonacci/status/1456198940563582979)

**Comment by leo-arch** [comment]
Hi @hectormonacci! Can't believe I missed that one: I've read those lines hundreds of times. But, you know, shit happens.

Thanks for pointing it out! And for the tweet!
