### ISSUE TITLE
bm bookmarkName : no such bookmark

### ISSUE THREAD

**Issue by chimay** [leo-arch/CliFM#76]
When I try to access a bookmark by its name, its fails with the message:

```
Bookmarks: /book/mark/dir: No such bookmark
```

It works fine when I use the shortcut however. Any idea to solve this ?

**Comment by leo-arch** [comment]
Hi @chimay. This issue is most likely due to having `ExpandBookmarks` option set to `true` in the config file. Setting it to `false` should solve the issue.

However, `bm` should be able to understand bookmark paths as well. I'll fix it as soon as I can.

Thanks for the report.

**Comment by leo-arch** [comment]
Solved with the last commit. Now `bm bm_name` should work disregarding the value of `ExpandBookmarks`. Let me know if it works for your so I can close this issue.

**Comment by chimay** [comment]
it works, thank you !

**Comment by leo-arch** [comment]
You're welcome!
