### ISSUE TITLE
recursive search with /pattern -x . not working

### ISSUE THREAD

**Issue by chimay** [leo-arch/CliFM#77]
recursive search in subdirectories doesn't print any match, am I missing something in the syntax ? I tried:

```
/pattern -x dir
```

and:

```
/pattern dir -x

**Comment by leo-arch** [comment]
Fixed with last commit.

**Comment by chimay** [comment]
ok, I will try to build it. Nice work, btw !

**Comment by leo-arch** [comment]
Thanks! As to the build process, just issue these commands:

```sh
mkdir build && cd build
git clone https://github.com/leo-arch/clifm
cd clifm
sudo make install
```

**Comment by chimay** [comment]
it works fine !

**Comment by leo-arch** [comment]
Happy to help!
