### ISSUE TITLE
We need a cool, nice-looking demo video

### ISSUE THREAD

**Issue by leo-arch** [leo-arch/CliFM#78]
I'm just a dev; I know nothing about video editing and stuff like that. But, a demo video is no doubt a good way of letting the world know what CliFM is. So, it would be really nice to have one.

The idea is to quickly show/describe the interface, some basic file operations (including files selection, workspaces, bookmarks, completion, suggestions), and a bit of eye-candy: showing how icons, files preview, color schemes, prompt customization, the FZF mode for TAB completion, and a few more things, work. The [ugly monster](https://mega.nz/embed/J8hEkCZZ#fGp0JtcDvFIWKmTc4cOp0iMrWRlbqs99THg8F7EmQWI) I created could be used as a starting point.

Any help will be highly appreciated! Thanks in advance,

Archcrack

**Comment by chimay** [comment]
if you are looking about a full length video, I don't know much about it, but if you just need a small screencast, `byzanz` can help you to generate a gif or a ogg/theora.

Their page:

```
 https://gitlab.gnome.org/Archive/byzanz
```

There is an arch package.

See here for an example of result:

```
https://github.com/chimay/wheel/blob/master/screenshots.md
```

**Comment by leo-arch** [comment]
I'll take a look at `byzanz`, thanks. But the thing is not so much about good screen recorders, but rather about how to record a good video, conceptually I mean: the video I recorded, for example, was focused on speed, but things happen indeed so fast that it is hard to get a clear idea of what CliFM is and what it can do. This is why this video falls short of the aim: to introduce CliFM to those who don't know it. A good video should be thus not only a quality video, but also able to simply and clearly introduce the tool. What I have in mind is some simple video for Youtube or something like that.

**Comment by leo-arch** [comment]
And we finally have [video](https://www.youtube.com/watch?v=CJmcisw9F90), an amazing one indeed. Thanks so much for this @BrodieRobertson!

EDIT: Going directly into our [frontpage](https://github.com/leo-arch/clifm#clapper-introduction-video)!

**Comment by BrodieRobertson** [comment]
Glad to help out, keep up the great work
