### ISSUE TITLE
Why does clifm only display in a single column, regardless of enable/disable multi-columns.

### ISSUE THREAD

**Issue by anoduck** [leo-arch/CliFM#79]
Regardless of multi-columns being enabled or disabled, or which terminal emulator is used, clifm always displays the contents of a directory in a single column. I cannot stress how difficult this makes navigating through the file system and use the file manager. Is there anything that can be done to change this problematic behavior? Is there a terminal setting that needs altering? 

Running current release of clifm, and attempted clifm both on mlterm and kitty.

**Comment by leo-arch** [comment]
Hi @anoduck. I just installed CliFM (git) with a fresh config file on both `mlterm` and `kitty` and cannot reproduce the issue: everything looks and works as expected. Same with stable version (1.2.2 from the AUR).

I guess by multi-columns you refer to the `--no-columns` command line flag, isn't it? Have you tried with a fresh config file (run `edit reset` from within CliFM and restart it).

I need to reproduce the issue. How have you installed CliFM exactly? On what OS?

**Comment by Docbroke** [comment]
If there are very long filenames, `clifm` uses single column.

**Comment by anoduck** [comment]
> Hi @anoduck. I just installed CliFM (git) with a fresh config file on both `mlterm` and `kitty` and cannot reproduce the issue: everything looks and works as expected. Same with stable version (1.2.2 from the AUR).
> 
> I guess by multi-columns you refer to the `--no-columns` command line flag, isn't it? Have you tried with a fresh config file (run `edit reset` from within CliFM and restart it).
> 
> I need to reproduce the issue. How have you installed CliFM exactly? On what OS?

@leo-arch You really did a terrific job with documentation. I salute you and your teachers for this. 

I am running OpenBSD, and resetting the configuration file did not resolve the issue. Now attempting to pull the most recent changes to the source code, and rebuild/reinstall clifm. Ensuring that I follow the installation exactly to the letter. 

Received an error on make `'libintl.h' file not found`. File is located in `/usr/local/include/libintl.h`. Currently, consulting documentation on compilation, and will report back. 

@Docbroke There are reasonably long names throughout the file system, and admittedly I was of the understanding that these "long filenames" would be abbreviated just as they are in every other command, such as ls or du. Regardless, I do not recall an instance where there were ever more than one column.

**Comment by leo-arch** [comment]
True. To prevent this behavior you can set `MaxFilenameLen` to any value you want (say, 20), to trim file names longer than this value (this setting is global), or same thing on a per directory basis using [autocommands](https://github.com/leo-arch/clifm/wiki/Specifics#autocommands).

**Comment by leo-arch** [comment]
Thanks @anoduck! Please keep us informed about this issue. It is really important to have some real feedback from OpenBSD (it's not that usual, as you can imagine).

**Comment by leo-arch** [comment]
This is CliFM (latest git version, fresh config file) running on OpenBSD (lxterminal):

![clifm_openbsd](https://user-images.githubusercontent.com/21303106/142745029-bac13fac-90d9-4445-9136-c2457f1760e9.png)

Installed as follows:

```sh
git clone https://github.com/leo-arch/clifm
cd clifm
doas make install
```
Everything seems to work fine. At least columns are displayed as expected.

**Comment by leo-arch** [comment]
Upgraded now to OpenBSD 7.0 and running on Kitty (same installation procedure):

![clifm_openbsd70](https://user-images.githubusercontent.com/21303106/142745663-bef63b40-ce4b-4006-a51f-13b173834759.png)

**Comment by anoduck** [comment]
> It is really important to have some real feedback from OpenBSD (it's not that usual, as you can imagine).

-- Well, we all have those problems we try to overcome in life. For some, criminal behavior, addictions, broken home life, etc... For me, it is OpenBSD.

----

AH-HA, that explains the build errors received earlier. You performed a simple `make install`, while (just by pure coincidence) I went through the procedure mentioned in the wiki.

https://github.com/leo-arch/clifm/wiki/Introduction#b2-other-linux-distributions-freebsd-netbsd-and-openbsd-cmake

Oh, my word. That compilation was beautiful, absolutely beautiful.  
AND  
Sweet Baby Jeezus! Setting `MaxFilenameLen=20` did the trick. I am rocking.

Absolutely awesome! Grand Slam! 💯 🥇

**Comment by leo-arch** [comment]
Glad the issue was solved. The cmake compilation procedure is quite new, and it might be producing some issues: I'll keep an eye on it.

Please report anything unusual or unexpected. That's the only way to make this thing better.
