### ISSUE TITLE
ac/ad overrides 'lira' config

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#80]
I have configured `lira` to open cbr/cbz files with zathura, and xopp with xournalpp, but as these files are basically archive clifm opens them using `ac`.
I think if there is association defined in `mimelist.cfm` it should be preferred.

**Comment by leo-arch** [comment]
Thanks for reporting this. I'll take a look at it.

**Comment by Docbroke** [comment]
I think instead of hardcoding opening of archives with `ad`, it shall be set in `mimelist.cfm`, so that it can be modified by user.
```
X:E:^(cbr|cbz)$=zathura
X:E:^(xopp|xoj)$=xournalpp
X:^application/(*zip*|x-?ar|x-?z*|x-compressed*|vnd.rar|x-msi|x-*-image)$=ad;als;aunpack -D;lsar;unar
```

**Comment by leo-arch** [comment]
Done.

* `Lira` honors now user's choice in `mimelist.cfm`
* `ad` could be used as an opening application in `mimelist.cfm`

**Comment by Docbroke** [comment]
Thanks.
I have few other suggestions on similar line.

1. allow something like
```
X:^application/.*(open|office)document.*=libreoffice %f &
```
currently with this, libreoffice tries to open file named & alongwith %f
2.  allow to open directories with external applications, ( only when used with `ow` )
```
X:inode/directory=clifm;vifm;pcmanfm;ncdu;rmdir
```
currently directories are hardcoded to be opened with clifm

**Comment by leo-arch** [comment]
That's doable.

**Comment by leo-arch** [comment]
You should now be able to open directories via external applications (with `ow`).

EDIT: This line should work fine:

```sh
X:inode/directory=vifm;pcmanfm;ncdu;rmdir
```

**Comment by Docbroke** [comment]
How to use `ad` in mimelist, it doesn't show up when `ow` is used?

**Comment by leo-arch** [comment]
Not at the moment.

If you add `ad` to some archive line in `mimelist.cfm`, CliFM will use `ad` if no other application is found (or directly `ad` if it is the first listed application).

**Comment by Docbroke** [comment]
using `ow <dir>` and selecting `clifm` creates some loop instead of opening selected dir in another instance of clifm.

**Comment by leo-arch** [comment]
I know. Working on it.

**Comment by Docbroke** [comment]
instead of plain `clifm`, using `$TERMINAL -e clifm` works fine. So not much of a problem.

**Comment by leo-arch** [comment]
That's true. But it's kinda dirty workaround. I'll make it automatic: specifying `clifm` will automatically issue `$TERM -e clifm`.

**Comment by leo-arch** [comment]
```sh
X:^application/.*(open|office)document.*=libreoffice %f &
```

This should be working now (not yet for `ow` though).

**Comment by Docbroke** [comment]
This works
```
X:inode/directory=sakura -e clifm %f &> /dev/null &; sakura -e vifm &> /dev/null &;sakura -e ncdu &> /dev/null &;rmdir
```

**Comment by leo-arch** [comment]
```
sakura -e vifm &
```
throws the same result.

However, just appending an ampersand from the command line works better (at least for now):

```
ow FILE &
```

**Comment by leo-arch** [comment]
```
sakura -e vifm %f &
```

Adding `%f` avoids a shell error message.

I guess I should add this to the default `mimelist.cfm`, by way of example.

EDIT: Still not playing nice with TAB completion.

**Comment by leo-arch** [comment]
TAB completion (in `fzf` mode) should be working now fine with `ow`: the whole input string will be translated using the appropriate command in `mimelist.cfm`.

**Comment by Docbroke** [comment]
```
sakura -e clifm %f &
```
works, but
```
sakura -e clifm %f &>/dev/null &
```
fails with `fzf` tab completion ( it works without `fzf` tab completion)

**Comment by leo-arch** [comment]
Fixed.

**Comment by Docbroke** [comment]
Thanks

**Comment by leo-arch** [comment]
You're welcome @Docbroke. Keep up the good suggestions!
