### ISSUE TITLE
MaxFileNameLen for long view mode

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#82]
I have `MinFileNameTrim=70` and `MaxFileNameLen=40`.
But in long view mode file names are trimmed at length of 40, instead of 70.

**Comment by leo-arch** [comment]
Hi @Docbroke. I know. Yesterday I worked on the long view (Unicode support) all day long.

Today is the turn of `MaxFilenameLen`: currently it does not support Unicode.

As soon as this is fixed, I'll start working on the conflict between `MaxFilenameLen` and `MinFileNameTrim`.

**Comment by leo-arch** [comment]
Should be solved now.
