### ISSUE TITLE
ColorScheme=golden-night not taken into account

### ISSUE THREAD

**Issue by chimay** [leo-arch/CliFM#83]
it's a personal theme located in `colors/golden-night.cfm`

I had to add manually:

```
cs golden-night
```

to the `profile.cfm` of default profile.

**Comment by leo-arch** [comment]
I just created a color scheme named `golden-night` and was able to reproduce the issue. I'll fix it in a few hours.

Thanks for reporting it.

**Comment by leo-arch** [comment]
Try now. It should be working.

**Comment by chimay** [comment]
it's fixed, thanks !

**Comment by leo-arch** [comment]
You're welcome!
