### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#84]
```
src/name_cleaner.c:323:13: error: 'curlen' undeclared (first use in this function); did you mean 'cur_len'?
  323 |         if (curlen == 3 && *p == '.' && *(p + 1) == '.' && !*(p + 2))
      |             ^~~~~~
      |             cur_len

```

**Comment by leo-arch** [comment]
Sorry, my bad. Fixed.

**Comment by Docbroke** [comment]
thanks, it compiles now.

bleach needs some improvement.
```
[1] 13:16 doc:asusalpine ~/tmp
<0> $ bb dkf\ djf\ akj.dd 
dkf djf akj.dd -> dkf_djf_akj.dd

Press 'e' to edit
Is this ok? [y/N] 
[1] 13:17 doc:asusalpine ~/tmp
<0> $ p 7
(0644)-/rw-/r--/r-- 1 doc doc 0B Dec 01 13:16:08 2021 dkf djf akj.dd
Regular file	Blocks: 0	IO Block: 4096	Inode: 7345992
Device: 2054	Uid: 1000 (doc)	Gid: 1000 (doc)
Access: 	Dec 01 13:16:08 2021
Modify: 	Dec 01 13:16:08 2021
Change: 	Dec 01 13:16:08 2021
Size: 		0B
[1] 13:17 doc:asusalpine ~/tmp
<0> $ 
```
if `e` is not pressed to edit, bleach doesn't change filename, `Is this ok? [y/N]` is printed but bleach exits immediately without waiting for reply.

**Comment by leo-arch** [comment]
It defaults to `No`. If you just press <kbd>Enter</kbd> it won't do anything.

Are you pressing <kbd>y</kbd> or just <kbd>Enter</kbd>?

**Comment by Docbroke** [comment]
bleach doesn't wait for me to press `y` or `n`, it just exits after I press enter when it asks `press e to edit`

**Comment by Docbroke** [comment]
if I press `y` when it is asking `press e to edit`, it changes the filename.

**Comment by leo-arch** [comment]
That's the expected behavior. Maybe not as intuitive as I thought though. I'll rework the interface to make it clearer.

**Comment by Docbroke** [comment]
In that case message shall be `Is this Ok? (Y/n/e)` in place of `press e to edit`. 
The message `Is this Ok? (y/n)` comes too late, when there is no chance of changing anything.

**Comment by leo-arch** [comment]
Improved interface. Take a look at it now.

**Comment by Docbroke** [comment]
Interface is fine now.
`edit` is ignored by bleach, filename is changed ignoring the edits

**Comment by leo-arch** [comment]
Weird. I'll give it a try.

**Comment by leo-arch** [comment]
Works fine for me. Could you describe the exact steps you're taking?

Just in case: did you save the changes after editing the temp file?

**Comment by Docbroke** [comment]
Problem is with using `vis` as default editor. If I use `vi` or `featherpad` this works fine. I guess I will have to change my editor.
One more thing, please refresh filelist after bleach.

**Comment by leo-arch** [comment]
I'll try with vis to see why it fails.

**Comment by leo-arch** [comment]
It should be working fine with `vis` now.

Now working on the screen refreshing thing.

**Comment by leo-arch** [comment]
Fixed.

**Comment by Docbroke** [comment]
Thanks, it is working now.
btw., I am testing/learning kakoune now, looks interesting.

**Comment by leo-arch** [comment]
Didn't know about it. Let me know if some issue pops up using this editor.
