### ISSUE TITLE
drive label with space

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#85]
`media` and `mp` commands have trouble when mounted drive have space in their label.
`udevil` mounts this drive creating folder under /media with label name (e.g., /media/data\ 1), but clifm fails to change directory to mounted folder. Manual cd works but `media` and `mp` fails to change directory to mountpoint.

**Comment by leo-arch** [comment]
Give it a try now.

**Comment by Docbroke** [comment]
Not solved.
Output of `lsblk` after mounting sdb1 with `media` command
```
sdb           8:16   1   7.6G  0 disk 
├─sdb1        8:17   1   7.6G  0 part /media/data 1
└─sdb2        8:18   1    32M  0 part 
```
Trying `mp` command
```
<0> $ mp
Mountpoints

1 / [/dev/nvme0n1p3]
2 /boot/efi [/dev/nvme0n1p1]
3 /home [/dev/sda6]
4 /media/data\0401 [/dev/sdb1]

Enter 'q' to quit
Choose a mountpoint: 4
CliFM: /media/data\0401: No such file or directory
```
`media` also fails to `cd` to mount directory automatically
```
<0> $ media
Mounted devices

1 /dev/nvme0n1p3 [/]
2 /dev/nvme0n1p1 [/boot/efi]
3 /dev/sda6 [/home]

Unmounted devices

4 /dev/nvme0n1
5 /dev/nvme0n1p2
6 /dev/sda1
7 /dev/sda3
8 /dev/sda4
9 /dev/sda5
10 /dev/sdb1 [data\x201]
11 /dev/sdb2 [VTOYEFI]

Enter 'q' to quit
Choose a mountpoint/device: 10
[1] 09:09 doc:asusalpine ~
<1> $ 

```
manual `cd` works fine,
```
[ins]└───▶ ls -l /media
total 72K
drwxr-xr-x 2 root   root   4.0K Jul 21 14:23  cdrom
drwx------ 3 doc doc  32K Dec  5 09:09 'data 1'
```

**Comment by leo-arch** [comment]
Thanks for the detailed description. I Think I know where the problem is. I'll try to manually reproduce the issue and fix it.

**Comment by leo-arch** [comment]
Should be fixed now.

**Comment by Docbroke** [comment]
fixed indeed. thanks.
