### ISSUE TITLE
clifm should respect the user's `$EDITOR`

### ISSUE THREAD

**Issue by scottchiefbaker** [leo-arch/CliFM#86]
`clifm` seems to always edit text files using `nano` despite my globally having configured `$EDITOR` to launch `vim`. The `$EDITOR` variable is supported by many programs, and has been a CLI standard for years. `clifm` should respect the users choice if they have `$EDITOR` set, and if not, then fall back to `nano`. Most notably `git` respects the `$EDITOR` variable, and I imagine a lot of people have this set because of that.

More info: https://bash.cyberciti.biz/guide/$EDITOR_variable

**Comment by leo-arch** [comment]
Hi @scottchiefbaker. Yes, you're absolutely right.
It should be quite easy to implement, but one never knows. Expect news in a few days at most, maybe less.

Thanks for your suggestion!

**Comment by leo-arch** [comment]
Done. Give it a try and let me know if some issue comes out.

EDIT: CliFM does not use `nano` by default. It rather parses `mimelist.cfm` looking for available/installed applications matching the corresponding file's MIME type or extension. The first application found is used.

**Comment by Docbroke** [comment]
Now $EDITOR seems to override mimelist.cfm. I think $EDITOR shall be fallback when no app is configured for text files.

EDIT: mimelist.cfm is specific for clifm while $EDITOR is universal environmental variable, which means when clifm is in use mimelist.cfm shall get priority over environmental variable.

**Comment by leo-arch** [comment]
We should simply stick to the standard behavior. I'll take a look at other FM's to see how they behave in this regard.

EDIT:
Maybe allowing `Lira` to understand environment variables would be a sane behavior. Something like this:

```sh
X:text/plain=$EDITOR;nano;vi;blabla
```

**Comment by Docbroke** [comment]
AFAIK, file managers that provide custom opener scripts (vifm/ranger etc.), they give priority to their own .conf files over environmental variables.

**Comment by leo-arch** [comment]
Ok. What about allowing `Lira` to understand environment variables? We could set `$EDITOR` as the first value for plain text files in the default `mimelist.cfm` file. It's up to the user to keep this settings or not.

**Comment by Docbroke** [comment]
1. user shall be able to use $EDITOR /$BROWSER etc. in their mimelist.cfm
2. if no application is defined for text file, $EDITOR or $VISUAL can be used as fallback
3. similarly, $BROWSER may be fallback for web/html things

Default mimelist.cfm may have for example
```
X:^text/.*=$EDITOR;nano;vi
```
EDIT: I missed your edit above, we both have given very similar example.

**Comment by leo-arch** [comment]
Great. Working on it.

**Comment by leo-arch** [comment]
Done. Give it a try now.

I added environments variables (`EDITOR`, `VISUAL`, and `BROWSER`) to the default `mimelist.cfm` file.

**Comment by Docbroke** [comment]
Looks good.
Also add `$TERMINAL`, or allow declaring/exporting variables in mimelist.cfm like `TERMINAL="${TERMINAL:-sakura}"`

**Comment by leo-arch** [comment]
That's exactly what I'm working on right now. The idea is to support _all_ environment variables, either custom or standard ones.

Now trying to make `Lira` work with more complex instructions such as `$TERM -e $EDITOR %f &>/dev/null &`
It will be ready in a few hours.

**Comment by leo-arch** [comment]
Done. `Lira` should be able now to understand all environment variables. For example, you can set a few specific variables only for _CliFM_ and then use them for `Lira`:

```sh
export CLIFM_TERM="sakura" CLIFM_EDITOR="vi" CLIFM_IMG="nsxiv"
```
Then, in the `mimelist.cfm` file:

```sh
X:text/plain=$CLIFM_TERM -e $CLIFM_EDITOR %f &>/dev/null &
X:^image/.*=$CLIFM_IMG &
```

**Comment by Docbroke** [comment]
`$TERMINAL -e $EDITOR %f` fails with filename having spaces. 
`ow` causes force close when `$TERMINAL -e $EDITOR` is used for filetype.

**Comment by leo-arch** [comment]
Cannot reproduce any of these issues. What I can tell, nonetheless, is that `sakura` has problem opening files containing spaces when set to `TERM`. It doesn't happen with other terminals, though, so it might be a problem with `sakura` itself.

Have you tried setting `TERM` to another value?

**Comment by Docbroke** [comment]
Indeed sakura problem. No such issue with lxterminal, so it's time to change terminal.

**Comment by leo-arch** [comment]
Good to know. This should be reported to `sakura` devs.
