### ISSUE TITLE
replace x functions with libc versions

### ISSUE THREAD

**Issue by sundaran1122** [leo-arch/clifm#9]
as of now the codebase uses a lot of these "x functions" eg xstrcmp, xstrcpy, xstrncpy etc. a lot of them appear to be useless. so replacing them with the libc version is better as that allows clifm to share code with other software running on the machine

**Comment by sundaran1122** [comment]
and it reduces the resulting binary size AND makes the code smaller

**Comment by sundaran1122** [comment]
I know that writing your own versions of libc functions is nice for learning but, it does mean we have a lot of dead code

**Comment by leo-arch** [comment]
Let me take a look a it. I remember having replaced some of my x functions and having a crash, for some reason. Each replacement needs to be thoroughly tested.

**Comment by sundaran1122** [comment]
k

**Comment by leo-arch** [comment]
By the way, performance, as I said before, was my first aim. Now maintainability and portability should be made goals as important as performance itself.

**Comment by sundaran1122** [comment]
that's not really what I meant. moving to libc will not reduce perfomance. if anything it will improve it as libc is very effecient.

**Comment by leo-arch** [comment]
I know, I know, I'm not saying moving to libc will reduce performance. On the contrary, I'm saying that portability should be as important as performance itself, and you are pointing out the way to go. And I thank you for that, just as you pointed out the way to go regarding maintainability.

**Comment by leo-arch** [comment]
I removed some of the x functions (only those having an exact libc replacement), and everything seems to be working fine, by now.

**Comment by leo-arch** [comment]
Solved first issue rising from the replacement of my x functions: xstrlen was not properly detecting overlapping source and destination; the error was thrown indeed by libc strlen. My fault, but already solved. More of these errors are expected.

**Comment by leo-arch** [comment]
Well, the thing seems to be quite stable: no new issue arisen. Closing.
