### ISSUE TITLE
issues in using m (move) command

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#90]
I found some difficulties in using `m` command to change file name.
1.  Once you start changing file name, with `m` there is no way to cancel and go back to original name, other than typing it again.
2.  Sometimes ( I don't know how to reproduce), after `m <file>`, when I move to the beginning or middle of filename and start deleting/editing characters, suddenly cursor appears at different location editing something else in the filename.

**Comment by leo-arch** [comment]
Hi @Docbroke,

1. Partially true: delete whatever you typed so far (you can use <kbd>Alt-c</kbd>) and type `q` to cancel and exit. However, I admit there should be an easier, more intuitive way of editing/canceling/exit the rename prompt.
2. Perhaps related to syntax highlighting.

I'll take a look at both issues. Thanks for reporting.

**Comment by leo-arch** [comment]
Now <kbd>Ctrl-x</kbd> quits the rename prompt. Thought not perfect, you can undo changes pressing <kbd>Ctrl-_</kbd> (Control plus underscore).

Sill wasn't able to reproduce the second issue.

**Comment by Docbroke** [comment]
I think `Esc` or `Ctrl-c` to leave the rename prompt will be more intuitive. There is no need for undo, it would be easier to escape and rename again. Too many shortcuts are confusing.
For second issue, try using files with longer names, may be filename spanning two lines. I still don't know how to consistently reproduce that.

**Comment by leo-arch** [comment]
Esc looks fine. I'll try with multiline file names as well.

**Comment by leo-arch** [comment]
The second issue (long file names) should be fixed now.

As to the Esc key, that's tricky: almost all keybindings (including the arrow keys) begin by the escape char (27 dec), so that using Esc to quit the rename prompt implies that you cannot move through the file name using the arrow keys (or jump to the beginning of the line by pressing <kbd>Ctrl-a</kbd>, and so on). For the time being, thereby, Ctrl-x remains (at least it's better than the old 'q').

**Comment by Docbroke** [comment]
`Ctrl-x` doesn't work if `Esc` key is used before it.
keys like arrow key, del, backspace have weird behavior if they are used immediately after `Esc`

**Comment by leo-arch** [comment]
Ok. I'll take a look at it.

**Comment by Docbroke** [comment]
After updating clifm today (after 4 days), I am getting seg faults with `m sel` or `c sel`.

**Comment by leo-arch** [comment]
Ok, I'll fix it. Thanks for reporting Doc.

**Comment by leo-arch** [comment]
Try now. It should be fixed.

**Comment by leo-arch** [comment]
I'm refactoring some code blocks to remove, as much as possible, calls to the system shell: it's a security vulnerability. This is what caused the seg fault you reported. Right now refactoring Lira for the same reason.

**Comment by Docbroke** [comment]
seg fault issue solved.

**Comment by leo-arch** [comment]
Hey @Docbroke! Hope you're doing fine. This issue should be solved now. Could you please give it a try?

**Comment by Docbroke** [comment]
Yes I am fine.
This looks like fixed. closing this.
